package io.github.jdubois.bootui.autoconfigure.graalvm;

import static org.assertj.core.api.Assertions.assertThat;

import io.github.jdubois.bootui.autoconfigure.sourcetree.ProjectSourceTree.Coordinates;
import io.github.jdubois.bootui.core.dto.GraalVmInstallAllResultDto;
import io.github.jdubois.bootui.core.dto.GraalVmInstallResultDto;
import io.github.jdubois.bootui.core.dto.GraalVmReadinessReport;
import io.github.jdubois.bootui.engine.graalvm.GraalVmDependencySettings;
import io.github.jdubois.bootui.engine.graalvm.GraalVmMetadataGenerator;
import io.github.jdubois.bootui.engine.graalvm.GraalVmReadinessScanner;
import io.github.jdubois.bootui.engine.graalvm.ReachabilityMetadataIndex;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Clock;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

class GraalVmControllerTests {

    private static final Coordinates COORDS = new Coordinates("com.example", "demo");

    private GraalVmController controller(GraalVmSourceLayout layout) {
        GraalVmReadinessScanner scanner = GraalVmReadinessScanner.usingClasspath(
                () -> java.util.List.of(),
                new GraalVmDependencySettings(false, 0),
                coordinates -> ReachabilityMetadataIndex.of(java.util.List.of()),
                Clock.systemUTC());
        return new GraalVmController(scanner, new GraalVmMetadataGenerator(), layout);
    }

    @Test
    void reportExposesInstallTargetWhenRunningFromSource(@TempDir Path projectRoot) throws IOException {
        GraalVmController controller = controller(sourceLayout(projectRoot));

        GraalVmReadinessReport report = controller.graalvm();

        assertThat(report.installable()).isTrue();
        assertThat(report.installPath()).contains("META-INF/native-image/com.example/demo");
        assertThat(report.metadataDirectory()).isEqualTo("src/main/resources/META-INF/native-image/com.example/demo/");
    }

    @Test
    void reportExposesReasonWhenNotInstallable(@TempDir Path projectRoot) {
        GraalVmController controller = controller(jarLayout(projectRoot));

        GraalVmReadinessReport report = controller.graalvm();

        assertThat(report.installable()).isFalse();
        assertThat(report.installPath()).contains("packaged jar");
        // Coordinates still resolve without an exploded build (for example from build-info.properties
        // inside a packaged jar), so the recommended directory shows the real groupId/artifactId.
        assertThat(report.metadataDirectory()).isEqualTo("src/main/resources/META-INF/native-image/com.example/demo/");
    }

    @Test
    void installWritesMetadataAndReturnsOk(@TempDir Path projectRoot) throws IOException {
        GraalVmController controller = controller(sourceLayout(projectRoot));

        ResponseEntity<GraalVmInstallResultDto> response = controller.install();

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isNotNull();
        assertThat(response.getBody().installed()).isTrue();
        Path written = projectRoot.resolve(
                "src/main/resources/META-INF/native-image/com.example/demo/reachability-metadata.json");
        assertThat(Files.readString(written, StandardCharsets.UTF_8)).contains("generated by BootUI");
    }

    @Test
    void installReturnsConflictForHandWrittenFile(@TempDir Path projectRoot) throws IOException {
        Path target = Files.createDirectories(
                        projectRoot.resolve("src/main/resources/META-INF/native-image/com.example/demo"))
                .resolve("reachability-metadata.json");
        Files.writeString(target, "{ \"reflection\": [] }", StandardCharsets.UTF_8);
        GraalVmController controller = controller(sourceLayout(projectRoot));

        ResponseEntity<GraalVmInstallResultDto> response = controller.install();

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.CONFLICT);
        assertThat(response.getBody().status()).isEqualTo("EXISTS");
        assertThat(Files.readString(target, StandardCharsets.UTF_8)).isEqualTo("{ \"reflection\": [] }");
    }

    @Test
    void installReturnsUnprocessableWhenRunningFromJar(@TempDir Path projectRoot) throws IOException {
        Files.createDirectories(projectRoot.resolve("src/main/resources"));
        GraalVmController controller = controller(jarLayout(projectRoot));

        ResponseEntity<GraalVmInstallResultDto> response = controller.install();

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.UNPROCESSABLE_CONTENT);
        assertThat(response.getBody().status()).isEqualTo("UNAVAILABLE");
    }

    @Test
    void dockerfileEndpointReturnsTailoredContent(@TempDir Path projectRoot) throws IOException {
        GraalVmController controller = controller(sourceLayout(projectRoot));

        ResponseEntity<byte[]> response = controller.dockerfile();

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        String content = new String(response.getBody(), StandardCharsets.UTF_8);
        assertThat(content).contains("FROM ghcr.io/graalvm/graalvm-community");
        assertThat(content).contains("target/demo");
        assertThat(content).contains("generated by BootUI");
    }

    @Test
    void reportExposesGeneratedDockerfile(@TempDir Path projectRoot) throws IOException {
        GraalVmController controller = controller(sourceLayout(projectRoot));

        GraalVmReadinessReport report = controller.graalvm();

        assertThat(report.dockerfile()).isNotNull();
        assertThat(report.dockerfile().installable()).isTrue();
        assertThat(report.dockerfile().content()).contains("target/demo");
        assertThat(report.dockerfile().installPath()).isEqualTo("Dockerfile-native");
    }

    @Test
    void dockerfileReflectsDetectedGradleBuild(@TempDir Path projectRoot) throws IOException {
        Files.writeString(projectRoot.resolve("build.gradle"), "plugins {}");
        Files.writeString(projectRoot.resolve("gradlew"), "#!/bin/sh");
        GraalVmController controller = controller(sourceLayout(projectRoot));

        String content = controller.graalvm().dockerfile().content();

        assertThat(content).contains("./gradlew nativeCompile");
        assertThat(content).contains("build/native/nativeCompile/demo");
        assertThat(content).doesNotContain("./mvnw");
    }

    @Test
    void installDockerfileWritesToProjectRootAndReturnsOk(@TempDir Path projectRoot) throws IOException {
        GraalVmController controller = controller(sourceLayout(projectRoot));

        ResponseEntity<GraalVmInstallResultDto> response = controller.installDockerfile();

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isNotNull();
        assertThat(response.getBody().installed()).isTrue();
        Path written = projectRoot.resolve("Dockerfile-native");
        assertThat(Files.readString(written, StandardCharsets.UTF_8)).contains("generated by BootUI");
    }

    @Test
    void installDockerfileReturnsUnprocessableWhenRunningFromJar(@TempDir Path projectRoot) {
        GraalVmController controller = controller(jarLayout(projectRoot));

        ResponseEntity<GraalVmInstallResultDto> response = controller.installDockerfile();

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.UNPROCESSABLE_CONTENT);
        assertThat(response.getBody().status()).isEqualTo("UNAVAILABLE");
    }

    @Test
    void installAllWritesBothArtifactsAndReturnsOk(@TempDir Path projectRoot) throws IOException {
        GraalVmController controller = controller(sourceLayout(projectRoot));

        ResponseEntity<GraalVmInstallAllResultDto> response = controller.installAll();

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isNotNull();
        assertThat(response.getBody().installed()).isTrue();
        assertThat(response.getBody().status()).isEqualTo("WRITTEN");
        assertThat(response.getBody().metadata().status()).isEqualTo("WRITTEN");
        assertThat(response.getBody().dockerfile().status()).isEqualTo("WRITTEN");
        Path metadata = projectRoot.resolve(
                "src/main/resources/META-INF/native-image/com.example/demo/reachability-metadata.json");
        Path dockerfile = projectRoot.resolve("Dockerfile-native");
        assertThat(Files.readString(metadata, StandardCharsets.UTF_8)).contains("generated by BootUI");
        assertThat(Files.readString(dockerfile, StandardCharsets.UTF_8)).contains("generated by BootUI");
    }

    @Test
    void installAllReportsMostSevereOutcome(@TempDir Path projectRoot) throws IOException {
        Path target = Files.createDirectories(
                        projectRoot.resolve("src/main/resources/META-INF/native-image/com.example/demo"))
                .resolve("reachability-metadata.json");
        Files.writeString(target, "{ \"reflection\": [] }", StandardCharsets.UTF_8);
        GraalVmController controller = controller(sourceLayout(projectRoot));

        ResponseEntity<GraalVmInstallAllResultDto> response = controller.installAll();

        // The hand-written metadata is left untouched (EXISTS) while the Dockerfile is written, so the
        // combined outcome reflects the more severe EXISTS status.
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.CONFLICT);
        assertThat(response.getBody().installed()).isFalse();
        assertThat(response.getBody().status()).isEqualTo("EXISTS");
        assertThat(response.getBody().metadata().status()).isEqualTo("EXISTS");
        assertThat(response.getBody().dockerfile().status()).isEqualTo("WRITTEN");
        assertThat(Files.readString(target, StandardCharsets.UTF_8)).isEqualTo("{ \"reflection\": [] }");
    }

    @Test
    void installAllReturnsUnprocessableWhenRunningFromJar(@TempDir Path projectRoot) {
        GraalVmController controller = controller(jarLayout(projectRoot));

        ResponseEntity<GraalVmInstallAllResultDto> response = controller.installAll();

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.UNPROCESSABLE_CONTENT);
        assertThat(response.getBody().installed()).isFalse();
        assertThat(response.getBody().status()).isEqualTo("UNAVAILABLE");
    }

    private GraalVmSourceLayout sourceLayout(Path projectRoot) throws IOException {
        Path classes = Files.createDirectories(projectRoot.resolve("target/classes"));
        Files.createDirectories(projectRoot.resolve("src/main/resources"));
        return new GraalVmSourceLayout(() -> projectRoot, () -> Optional.of(toUrl(classes)), () -> Optional.of(COORDS));
    }

    private GraalVmSourceLayout jarLayout(Path projectRoot) {
        return new GraalVmSourceLayout(
                () -> projectRoot, () -> Optional.of(toUrl(Path.of("/tmp/app.jar"))), () -> Optional.of(COORDS));
    }

    private static java.net.URL toUrl(Path path) {
        try {
            return path.toUri().toURL();
        } catch (IOException ex) {
            throw new IllegalStateException(ex);
        }
    }
}
