import subprocess
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / ".github/scripts/check-action-references.sh"
SHA = "0123456789abcdef0123456789abcdef01234567"


class ActionReferenceTests(unittest.TestCase):
    def check_reference(self, reference):
        with tempfile.TemporaryDirectory() as directory:
            workflow = Path(directory) / "workflow.yml"
            workflow.write_text(
                f"jobs:\n  build:\n    steps:\n      - uses: {reference}\n",
                encoding="utf-8",
            )
            return subprocess.run(
                ["bash", str(SCRIPT), str(workflow)],
                capture_output=True,
                text=True,
                check=False,
            )

    def test_trusted_major_tags_and_local_actions_are_accepted(self):
        for reference in (
            "actions/checkout@v7",
            "docker/build-push-action@v6",
            "github/codeql-action/analyze@v3",
            "./.github/actions/local",
        ):
            with self.subTest(reference=reference):
                result = self.check_reference(reference)
                self.assertEqual(result.returncode, 0, result.stderr)

    def test_sha_pins_accept_release_comments_and_generated_annotations(self):
        for action in (
            "actions/checkout",
            "actions/github-script",
            "actions/cache/restore",
            "github/gh-aw-actions/setup",
        ):
            for comment in (
                "v9",
                "v9.0",
                "v9.0.0",
                "v9.0.0-rc.1",
                "v9.0.0 (source v9)",
                "v9.0.0\t(source v9)",
            ):
                with self.subTest(action=action, comment=comment):
                    result = self.check_reference(f"{action}@{SHA} # {comment}")
                    self.assertEqual(result.returncode, 0, result.stderr)

    def test_sha_pins_still_require_a_leading_release_version(self):
        for action in ("actions/checkout", "actions/github-script"):
            for comment in (
                "",
                "latest",
                "release v9.0.0",
                "(source v9)",
                "v9.0.0(source v9)",
                "v9/invalid",
            ):
                with self.subTest(action=action, comment=comment):
                    result = self.check_reference(f"{action}@{SHA} # {comment}")
                    self.assertEqual(result.returncode, 1, result.stderr)
                    self.assertIn("inline release comment", result.stderr)

    def test_mutable_refs_remain_restricted(self):
        for action in ("actions/checkout", "actions/github-script"):
            for ref in ("main", "latest", "v9.0.0", SHA[:7], "g" * 40, SHA + "0"):
                with self.subTest(action=action, ref=ref):
                    result = self.check_reference(f"{action}@{ref} # v9.0.0")
                    self.assertEqual(result.returncode, 1, result.stderr)
                    self.assertIn("full 40-character commit SHA", result.stderr)
        result = self.check_reference("actions/github-script@v9")
        self.assertEqual(result.returncode, 1, result.stderr)
        self.assertIn("Non-allowlisted action", result.stderr)

    def test_quoted_sha_pins_are_accepted(self):
        for quote in ("'", '"'):
            with self.subTest(quote=quote):
                result = self.check_reference(
                    f"{quote}actions/checkout@{SHA}{quote} # v7.0.1 (source v7)"
                )
                self.assertEqual(result.returncode, 0, result.stderr)

    def test_discovery_still_checks_generated_workflows(self):
        with tempfile.TemporaryDirectory() as directory:
            workflow = Path(directory) / ".github/workflows/generated.lock.yml"
            workflow.parent.mkdir(parents=True)
            workflow.write_text(
                "# This file was automatically generated by gh-aw. DO NOT EDIT.\n"
                "jobs:\n  build:\n    steps:\n      - uses: actions/github-script@main\n",
                encoding="utf-8",
            )
            result = subprocess.run(
                ["bash", str(SCRIPT)],
                cwd=directory,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(result.returncode, 1, result.stderr)
            self.assertIn("generated.lock.yml", result.stderr)
            self.assertIn("Non-allowlisted action", result.stderr)


if __name__ == "__main__":
    unittest.main()
