package io.github.jdubois.bootui.autoconfigure.graalvm;

import io.github.jdubois.bootui.autoconfigure.sourcetree.ProjectSourceTree;
import io.github.jdubois.bootui.autoconfigure.sourcetree.ProjectSourceTree.Coordinates;
import io.github.jdubois.bootui.autoconfigure.sourcetree.ProjectSourceTree.InstallOutcome;
import io.github.jdubois.bootui.autoconfigure.sourcetree.ProjectSourceTree.Resolution;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Optional;
import java.util.function.Supplier;
import org.jspecify.annotations.Nullable;

/**
 * Resolves whether the generated {@code reachability-metadata.json} scaffold can be written directly
 * into the host application's source tree, and performs that write.
 *
 * <p>This is the GraalVM-specific layer over the shared {@link ProjectSourceTree}: it adds the
 * GraalVM-recommended metadata location
 * {@code src/main/resources/META-INF/native-image/<groupId>/<artifactId>/reachability-metadata.json}
 * (falling back to a {@code bootui-generated} namespace when Maven coordinates cannot be resolved),
 * while delegating the project-root {@code Dockerfile-native} write and the fail-closed write
 * mechanics to {@link ProjectSourceTree}.
 *
 * <p>Installing in place is only offered when the application is detectably running from an exploded
 * build (e.g. {@code target/classes} via {@code mvn spring-boot:run} or an IDE), <em>not</em> from a
 * packaged fat jar. The write is fail-closed: it is confined under {@code src/main/resources} and
 * never clobbers a file that was not previously generated by BootUI.
 */
final class GraalVmSourceLayout {

    static final String METADATA_FILE = "reachability-metadata.json";
    static final String DOCKERFILE_FILE = "Dockerfile-native";

    private static final String FALLBACK_NAMESPACE = "bootui-generated";
    private static final Path RESOURCES_RELATIVE = Path.of("src", "main", "resources");

    private final Supplier<Path> projectRootSupplier;
    private final Supplier<Optional<URL>> codeSourceSupplier;
    private final Supplier<Optional<Coordinates>> coordinatesSupplier;
    private final ProjectSourceTree sourceTree;

    GraalVmSourceLayout(
            Supplier<Path> projectRootSupplier,
            Supplier<Optional<URL>> codeSourceSupplier,
            Supplier<Optional<Coordinates>> coordinatesSupplier) {
        this.projectRootSupplier = projectRootSupplier;
        this.codeSourceSupplier = codeSourceSupplier;
        this.coordinatesSupplier = coordinatesSupplier;
        this.sourceTree = new ProjectSourceTree(projectRootSupplier, codeSourceSupplier, coordinatesSupplier);
    }

    /** Wraps an existing {@link ProjectSourceTree}, reusing its application-derived suppliers. */
    GraalVmSourceLayout(ProjectSourceTree sourceTree) {
        this.projectRootSupplier = sourceTree::projectRoot;
        this.codeSourceSupplier = sourceTree::codeSource;
        this.coordinatesSupplier = sourceTree::coordinates;
        this.sourceTree = sourceTree;
    }

    /** Resolves where (and whether) the metadata scaffold can be installed. */
    Resolution resolve() {
        Path projectRoot;
        Optional<URL> codeSource;
        Optional<Coordinates> coordinates;
        try {
            projectRoot = projectRootSupplier.get();
            codeSource = codeSourceSupplier.get();
            coordinates = coordinatesSupplier.get();
        } catch (RuntimeException ex) {
            return Resolution.unavailable("The application source layout could not be determined.");
        }
        Optional<Coordinates> safeCoordinates = coordinates == null ? Optional.empty() : coordinates;
        return resolve(projectRoot, codeSource.orElse(null), safeCoordinates);
    }

    /**
     * Generates the install target. Package-private and static so it can be unit tested with explicit
     * inputs against temporary directories.
     */
    static Resolution resolve(
            @Nullable Path projectRoot, @Nullable URL codeSourceLocation, Optional<Coordinates> coordinates) {
        if (projectRoot == null) {
            return Resolution.unavailable("The application working directory could not be determined.");
        }
        if (!ProjectSourceTree.isExplodedClasses(codeSourceLocation)) {
            return Resolution.unavailable(
                    "The application is not running from an exploded build (for example a packaged jar), "
                            + "so there is no source tree to install into.");
        }
        Path root = projectRoot.toAbsolutePath().normalize();
        Path resources = root.resolve(RESOURCES_RELATIVE).normalize();
        if (!Files.isDirectory(resources)) {
            return Resolution.unavailable("No src/main/resources directory was found under " + root + ".");
        }
        if (!Files.isWritable(resources)) {
            return Resolution.unavailable("The src/main/resources directory is not writable.");
        }
        Path target = resources.resolve("META-INF").resolve("native-image");
        Coordinates resolved = coordinates.filter(Coordinates::isValid).orElse(null);
        if (resolved != null) {
            target = target.resolve(ProjectSourceTree.sanitize(resolved.groupId()))
                    .resolve(ProjectSourceTree.sanitize(resolved.artifactId()));
        } else {
            target = target.resolve(FALLBACK_NAMESPACE);
        }
        Path targetFile = target.resolve(METADATA_FILE).normalize();
        if (!targetFile.startsWith(resources)) {
            return Resolution.unavailable("The resolved metadata path escapes src/main/resources.");
        }
        return Resolution.installable(targetFile, root.relativize(targetFile).toString());
    }

    /**
     * Returns the GraalVM-recommended, project-relative metadata directory, substituting the resolved
     * Maven coordinates when they are available.
     *
     * <p>Unlike {@link #resolve()}, this does not require running from an exploded build: coordinates
     * resolve from {@code build-info.properties} (bundled inside a packaged jar) or the project
     * {@code pom.xml}, so the real {@code groupId}/{@code artifactId} are shown even when there is no
     * source tree to install into. The {@code <groupId>}/{@code <artifactId>} placeholders are kept
     * only when no coordinates can be resolved.
     */
    String metadataDirectory() {
        Optional<Coordinates> coordinates;
        try {
            coordinates = coordinatesSupplier.get();
        } catch (RuntimeException ex) {
            coordinates = Optional.empty();
        }
        return metadataDirectory(coordinates == null ? Optional.empty() : coordinates);
    }

    /** Builds the directory snippet from explicit coordinates; package-private for unit testing. */
    static String metadataDirectory(Optional<Coordinates> coordinates) {
        Coordinates resolved = coordinates.filter(Coordinates::isValid).orElse(null);
        String group = resolved != null ? ProjectSourceTree.sanitize(resolved.groupId()) : "<groupId>";
        String artifact = resolved != null ? ProjectSourceTree.sanitize(resolved.artifactId()) : "<artifactId>";
        return "src/main/resources/META-INF/native-image/" + group + "/" + artifact + "/";
    }

    /**
     * Returns the native executable name (the resolved Maven {@code artifactId}, as named by the
     * {@code native-maven-plugin}), or {@code "app"} when coordinates cannot be resolved. Like
     * {@link #metadataDirectory()}, this does not require running from an exploded build.
     */
    String artifactName() {
        return sourceTree.artifactName();
    }

    /** Best-effort absolute project root, or {@code null} when it cannot be determined. */
    @Nullable
    Path projectRoot() {
        return sourceTree.projectRoot();
    }

    /** Resolves whether (and where) the native-image {@code Dockerfile-native} can be written. */
    Resolution resolveDockerfile() {
        return sourceTree.resolveProjectRootFile(DOCKERFILE_FILE);
    }

    /** Resolves the {@code Dockerfile-native} target. Package-private and static for unit testing. */
    static Resolution resolveDockerfile(@Nullable Path projectRoot, @Nullable URL codeSourceLocation) {
        return ProjectSourceTree.resolveProjectRootFile(projectRoot, codeSourceLocation, DOCKERFILE_FILE);
    }

    /** Resolves the target and writes the supplied JSON, refusing to overwrite a non-generated file. */
    InstallOutcome install(String json) {
        return sourceTree.write(
                resolve(),
                json,
                displayPath -> "A reachability-metadata.json already exists at " + displayPath
                        + " and was not generated by BootUI, so it was left untouched. "
                        + "Download the scaffold and merge it by hand instead.",
                displayPath -> "Wrote the reachability metadata scaffold to " + displayPath
                        + ". Review and complete it with the GraalVM tracing agent before relying on it.",
                "Failed to write the reachability metadata: ");
    }

    /**
     * Resolves the project-root {@code Dockerfile-native} target and writes the supplied content,
     * refusing to overwrite a file that BootUI did not previously generate.
     */
    InstallOutcome installDockerfile(String content) {
        return sourceTree.write(
                resolveDockerfile(),
                content,
                displayPath -> "A Dockerfile-native already exists at " + displayPath
                        + " and was not generated by BootUI, so it was left untouched. "
                        + "Download the generated one and merge it by hand instead.",
                displayPath -> "Wrote the native-image Dockerfile to " + displayPath
                        + ". Review it, then build with: docker build -f Dockerfile-native -t native-app .",
                "Failed to write the Dockerfile: ");
    }

    /** Delegates to {@link ProjectSourceTree#isExplodedClasses(URL)}; kept for focused unit tests. */
    static boolean isExplodedClasses(@Nullable URL location) {
        return ProjectSourceTree.isExplodedClasses(location);
    }

    /** Delegates to {@link ProjectSourceTree#coordinatesFromPom(Path)}; kept for focused unit tests. */
    static Optional<Coordinates> coordinatesFromPom(@Nullable Path projectRoot) {
        return ProjectSourceTree.coordinatesFromPom(projectRoot);
    }
}
