package io.github.jdubois.bootui.autoconfigure.crac;

import io.github.jdubois.bootui.autoconfigure.sourcetree.DockerPackageManager;
import io.github.jdubois.bootui.autoconfigure.sourcetree.ProjectBuildSystem;

/**
 * Generates the container assets for a CRaC (Coordinated Restore at Checkpoint) image of the host
 * application the BootUI starter is installed in: a multi-stage {@code Dockerfile-crac} and the
 * {@code checkpoint-and-run.sh} entrypoint it relies on.
 *
 * <p>Unlike the multi-module {@code Dockerfile-crac} at the root of the BootUI project (which builds
 * the sample app together with its reactor modules), this scaffold targets a single-module Spring Boot
 * application. It detects the project's build system from the files in the project root — Maven or
 * Gradle, with or without the wrapper, via the shared {@link ProjectBuildSystem} — and emits the
 * matching build command that produces a runnable Spring Boot jar
 * ({@code ./mvnw}/{@code mvn -DskipTests clean package} or {@code ./gradlew}/{@code gradle bootJar}),
 * copying the resulting jar from the build tool's conventional output directory ({@code target} for
 * Maven, {@code build/libs} for Gradle).</p>
 *
 * <p>The build stage uses a plain JDK (CRaC only matters at runtime) and the runtime stage uses a
 * CRaC-enabled BellSoft Liberica JDK. The build image is Debian-based, so a missing build tool is
 * installed with {@code apt-get} ({@link DockerPackageManager#APT}). The companion
 * {@code checkpoint-and-run.sh} takes a checkpoint on the first start (via
 * {@code spring.context.checkpoint=onRefresh}) and restores it afterwards.</p>
 *
 * <p>Both generated files carry a {@code generated by BootUI} marker so the source-tree writer can
 * tell a previously generated file apart from a hand-written one and refuse to clobber the latter.</p>
 */
final class CracDockerfileGenerator {

    private static final String DEFAULT_ARTIFACT = "app";

    /** The CRaC-specific Dockerfile pieces that depend on the detected build system. */
    private record Variant(String description, String command, String outputDir) {}

    private static Variant variant(ProjectBuildSystem buildSystem) {
        return switch (buildSystem) {
            case MAVEN_WRAPPER -> new Variant("the Maven Wrapper", "./mvnw -DskipTests clean package", "target");
            case MAVEN -> new Variant("Maven", "mvn -DskipTests clean package", "target");
            case GRADLE_WRAPPER -> new Variant("the Gradle Wrapper", "./gradlew bootJar", "build/libs");
            case GRADLE -> new Variant("Gradle", "gradle bootJar", "build/libs");
        };
    }

    String generateDockerfile(String artifactName) {
        return generateDockerfile(artifactName, ProjectBuildSystem.MAVEN_WRAPPER);
    }

    String generateDockerfile(String artifactName, ProjectBuildSystem buildSystem) {
        String artifact = artifactName == null || artifactName.isBlank() ? DEFAULT_ARTIFACT : artifactName.trim();
        ProjectBuildSystem tool = buildSystem == null ? ProjectBuildSystem.MAVEN_WRAPPER : buildSystem;
        Variant variant = variant(tool);
        String setup = tool.dockerSetup(DockerPackageManager.APT);
        return """
                # Multi-stage Dockerfile for a CRaC (Coordinated Restore at Checkpoint) image of %1$s.
                #
                # This scaffold was generated by BootUI for the application the starter is installed in.
                # It assumes a single-module Spring Boot application built with %2$s.
                #
                # CRaC snapshots a fully warmed-up JVM process to disk and restores it in tens of
                # milliseconds. It only works on Linux and needs a CRaC-enabled JDK plus elevated
                # container privileges (CRIU) to take and restore the checkpoint. The companion
                # checkpoint-and-run.sh entrypoint (generated alongside this file and expected at the
                # project root) takes the checkpoint on the first start and restores it afterwards.
                #
                # Build and run (CRIU needs extra privileges; the named volume keeps the checkpoint
                # between restarts, and -p publishes the port so the app is reachable from the host):
                #   docker build -f Dockerfile-crac -t %1$s .
                #   docker run --rm -p 8080:8080 \\
                #     --cap-add=CHECKPOINT_RESTORE --cap-add=SYS_PTRACE --cap-add=SYS_ADMIN \\
                #     -v %1$s-crac:/opt/crac/checkpoint %1$s

                # Build stage (a plain JDK is enough; CRaC only matters at runtime).
                FROM eclipse-temurin:21-jdk-noble AS build

                WORKDIR /app

                # Copy the project (see .dockerignore for exclusions).
                COPY . .

                %3$s

                # Build the repackaged, runnable Spring Boot jar.
                RUN %4$s

                # Move the runnable jar to a known path (the repackaged boot jar, not a *-plain.jar or
                # *.jar.original produced alongside it).
                RUN set -e; \\
                    app_jar=$(find %5$s -maxdepth 1 -type f -name '*.jar' ! -name '*-plain.jar' ! -name '*.jar.original' | head -1); \\
                    if [ -z "$app_jar" ]; then echo "ERROR: Spring Boot jar not found"; ls -laR %5$s | head -40; exit 1; fi; \\
                    cp "$app_jar" /app/app.jar

                # Runtime stage with a CRaC-enabled JDK (BellSoft Liberica with CRaC support).
                FROM bellsoft/liberica-runtime-container:jdk-21-crac-slim-glibc

                WORKDIR /app

                # Where the checkpoint image is written/read. Mount it as a volume so the checkpoint
                # survives container restarts.
                ENV CRAC_CHECKPOINT_DIR=/opt/crac/checkpoint
                ENV APP_JAR=/app/app.jar

                # Copy the repackaged jar and the checkpoint/restore entrypoint generated alongside this file.
                COPY --from=build /app/app.jar ${APP_JAR}
                COPY --from=build /app/checkpoint-and-run.sh /app/checkpoint-and-run.sh

                RUN chmod +x /app/checkpoint-and-run.sh && mkdir -p ${CRAC_CHECKPOINT_DIR}

                EXPOSE 8080

                # Take a checkpoint on the first start, then restore on every start.
                ENTRYPOINT ["/app/checkpoint-and-run.sh"]
                """.formatted(artifact, variant.description(), setup, variant.command(), variant.outputDir());
    }

    /**
     * Generates the {@code checkpoint-and-run.sh} entrypoint. On the first start it takes a CRaC
     * checkpoint of the warmed-up JVM; every later start restores that checkpoint.
     */
    String generateEntrypoint() {
        return """
                #!/bin/sh
                # CRaC (Coordinated Restore at Checkpoint) entrypoint generated by BootUI.
                #
                # On the first start no checkpoint exists yet, so the app is launched with
                # `spring.context.checkpoint=onRefresh`: Spring boots the application context,
                # closes CRaC-aware resources (the Hikari pool, the Lettuce/Redis client, ...),
                # and the JVM writes a full process image into $CRAC_CHECKPOINT_DIR before CRIU
                # terminates the process. Every subsequent start simply restores that image,
                # which brings the application back in a few tens of milliseconds.
                #
                # Taking and restoring a checkpoint needs Linux and elevated container
                # privileges (CRIU); see the generated Dockerfile-crac.
                set -eu

                CRAC_CHECKPOINT_DIR="${CRAC_CHECKPOINT_DIR:-/opt/crac/checkpoint}"
                APP_JAR="${APP_JAR:-/app/app.jar}"

                mkdir -p "$CRAC_CHECKPOINT_DIR"

                # Restore immediately when a previous checkpoint is present.
                if [ -n "$(ls -A "$CRAC_CHECKPOINT_DIR" 2>/dev/null)" ]; then
                  echo "[crac] Restoring the application from the checkpoint in $CRAC_CHECKPOINT_DIR"
                  exec java -XX:CRaCRestoreFrom="$CRAC_CHECKPOINT_DIR"
                fi

                echo "[crac] No checkpoint found; starting the app to create one (spring.context.checkpoint=onRefresh)"
                # CRIU kills the process once the checkpoint is written, so a non-zero exit code
                # here is expected. Inspect the directory rather than the exit code to decide
                # whether the checkpoint succeeded.
                set +e
                java -XX:CRaCCheckpointTo="$CRAC_CHECKPOINT_DIR" \\
                  -Dspring.context.checkpoint=onRefresh \\
                  -jar "$APP_JAR"
                checkpoint_status=$?
                set -e

                if [ -z "$(ls -A "$CRAC_CHECKPOINT_DIR" 2>/dev/null)" ]; then
                  echo "[crac] Checkpoint creation failed (exit code $checkpoint_status). See the log above." >&2
                  echo "[crac] CRaC needs a CRaC-enabled JDK on Linux and CRIU privileges (run the container" >&2
                  echo "[crac] with --privileged or the CHECKPOINT_RESTORE/SYS_PTRACE/SYS_ADMIN capabilities)." >&2
                  exit "$checkpoint_status"
                fi

                echo "[crac] Checkpoint created in $CRAC_CHECKPOINT_DIR; restoring the application"
                exec java -XX:CRaCRestoreFrom="$CRAC_CHECKPOINT_DIR"
                """;
    }
}
