// @ts-check
import {expect, test} from './fixtures.js'

/**
 * Threads renders the same shared Threads.vue on both adapters over a byte-identical DTO; the data is
 * a pure JVM ThreadMXBean snapshot, so a Quarkus app always has live threads to show. These checks
 * pin that the panel renders real content (not just an empty/unavailable shell) on Quarkus.
 */
test.describe('Threads view', () => {
  test('shows a live thread snapshot with state summary and stack traces', async ({openView, page}) => {
    await openView('threads', 'Threads')

    // The sample app always has multiple live threads.
    const rows = page.locator('table.threads-table tbody tr')
    await expect.poll(async () => rows.count()).toBeGreaterThan(3)

    // A per-state count summary is rendered as badges.
    await expect(page.locator('.badge', {hasText: /RUNNABLE:/}).first()).toBeVisible()

    // Expanding a stack trace reveals frames.
    const stackButton = page.getByRole('button', {name: /View stack \d+/}).first()
    await stackButton.click()
    await expect(page.locator('pre.threads-stack').first()).toBeVisible()
  })

  test('filters threads by name', async ({openView, page}) => {
    await openView('threads', 'Threads')

    const rows = page.locator('table.threads-table tbody tr')
    await expect.poll(async () => rows.count()).toBeGreaterThan(3)

    await page.getByPlaceholder(/Filter by name, state, or stack frame/).fill('zzz-no-such-thread')
    await expect(page.locator('text=No threads match your filters.')).toBeVisible()
  })

  test('downloads a raw thread dump generated by the live JVM', async ({openView, page}) => {
    await openView('threads', 'Threads')

    const downloadButton = page.getByRole('button', {name: 'Download dump'})
    await expect(downloadButton).toBeEnabled()

    // The button is a real POST /bootui/api/threads/download that streams a text attachment; Chromium
    // reports that as a Playwright download event rather than a navigation.
    const [download] = await Promise.all([page.waitForEvent('download'), downloadButton.click()])

    expect(download.suggestedFilename()).toBe('thread-dump.txt')
    const stream = await download.createReadStream()
    let content = ''
    for await (const chunk of stream) content += chunk.toString('utf-8')
    expect(content).toContain('RUNNABLE')
  })
})
