package io.github.jdubois.bootui.webfluxsample.transactions;

/** Thrown on purpose by {@link SampleTransactionScenarios#rollBack()} so its transaction rolls back. */
final class SampleTransactionRollbackException extends RuntimeException {

    SampleTransactionRollbackException() {
        super("Expected rollback generated by the transaction sample");
    }
}
