package io.github.jdubois.bootui.core.dto;

/**
 * A container asset generated by the CRaC panel for the host application — the multi-stage
 * {@code Dockerfile-crac} or its {@code checkpoint-and-run.sh} entrypoint — together with whether it
 * can be written directly into the project directory.
 *
 * <p>{@code name} is the file name (for example {@code Dockerfile-crac}). {@code content} is the full
 * file text. {@code installable} is {@code true} when the file can be written to the project root
 * (only possible when the app runs from an exploded build rather than a packaged jar).
 * {@code installPath} is the display-friendly, project-relative path it would be written to, or the
 * reason a direct write is unavailable when {@code installable} is {@code false}.
 */
public record CracGeneratedFileDto(String name, String content, boolean installable, String installPath) {}
