package io.github.jdubois.bootui.autoconfigure.crac;

import static org.assertj.core.api.Assertions.assertThat;

import io.github.jdubois.bootui.autoconfigure.sourcetree.ProjectBuildSystem;
import org.junit.jupiter.api.Test;

class CracDockerfileGeneratorTests {

    private final CracDockerfileGenerator generator = new CracDockerfileGenerator();

    @Test
    void generatesCracDockerfileTailoredToArtifact() {
        String dockerfile = generator.generateDockerfile("my-service");

        assertThat(dockerfile).contains("FROM eclipse-temurin:21-jdk-noble AS build");
        assertThat(dockerfile).contains("FROM bellsoft/liberica-runtime-container:jdk-21-crac-slim-glibc");
        assertThat(dockerfile).contains("./mvnw -DskipTests clean package");
        assertThat(dockerfile).contains("docker build -f Dockerfile-crac -t my-service .");
        assertThat(dockerfile).contains("ENTRYPOINT [\"/app/checkpoint-and-run.sh\"]");
        assertThat(dockerfile).contains("generated by BootUI");
    }

    @Test
    void fallsBackToAppWhenArtifactIsMissing() {
        assertThat(generator.generateDockerfile(null)).contains("image of app.");
        assertThat(generator.generateDockerfile("  ")).contains("image of app.");
    }

    @Test
    void generatesPlainMavenVariant() {
        String dockerfile = generator.generateDockerfile("my-service", ProjectBuildSystem.MAVEN);

        assertThat(dockerfile).contains("mvn -DskipTests clean package");
        assertThat(dockerfile).doesNotContain("./mvnw");
        assertThat(dockerfile).contains("apache-maven");
        // The CRaC build image is Debian-based, so a missing build tool is installed with apt-get.
        assertThat(dockerfile).contains("apt-get install -y --no-install-recommends curl ca-certificates");
        assertThat(dockerfile).doesNotContain("microdnf");
        // The runnable jar lands in target for Maven.
        assertThat(dockerfile).contains("find target -maxdepth 1");
        assertThat(dockerfile).contains("ARG MAVEN_VERSION=3.9.16");
    }

    @Test
    void generatesGradleWrapperVariant() {
        String dockerfile = generator.generateDockerfile("my-service", ProjectBuildSystem.GRADLE_WRAPPER);

        assertThat(dockerfile).contains("chmod +x gradlew");
        assertThat(dockerfile).contains("./gradlew bootJar");
        assertThat(dockerfile).contains("find build/libs -maxdepth 1");
        assertThat(dockerfile).doesNotContain("./mvnw");
    }

    @Test
    void generatesPlainGradleVariant() {
        String dockerfile = generator.generateDockerfile("my-service", ProjectBuildSystem.GRADLE);

        assertThat(dockerfile).contains("gradle bootJar");
        assertThat(dockerfile).doesNotContain("./gradlew");
        assertThat(dockerfile).contains("services.gradle.org");
        assertThat(dockerfile).contains("curl ca-certificates unzip");
        assertThat(dockerfile).contains("find build/libs -maxdepth 1");
        assertThat(dockerfile).contains("ARG GRADLE_VERSION=9.5.1");
    }

    @Test
    void entrypointTakesAndRestoresACheckpoint() {
        String entrypoint = generator.generateEntrypoint();

        assertThat(entrypoint).startsWith("#!/bin/sh");
        assertThat(entrypoint).contains("spring.context.checkpoint=onRefresh");
        assertThat(entrypoint).contains("CRaCCheckpointTo");
        assertThat(entrypoint).contains("CRaCRestoreFrom");
        assertThat(entrypoint).contains("generated by BootUI");
    }
}
