package io.github.jdubois.bootui.engine.graalvm;

import java.util.List;
import java.util.Set;
import java.util.TreeSet;

/**
 * Serializes {@link GraalVmMetadata} into the modern unified GraalVM
 * {@code reachability-metadata.json} format. GraalVM 25's unified schema represents serialization
 * and JNI access as flags on reflection entries, dynamic proxies as structured reflection types, and
 * FFM registrations in a top-level {@code foreign} object.
 *
 * <p>The output is a heuristic scaffold derived from static analysis: it seeds the file that belongs
 * under {@code src/main/resources/META-INF/native-image/<groupId>/<artifactId>/} and is meant to be
 * reviewed and completed with the tracing agent.</p>
 *
 * <p>JSON is written by hand (with strict escaping) to avoid adding a JSON library dependency to the
 * auto-configuration module.</p>
 */
public final class GraalVmMetadataGenerator {

    private static final String INDENT = "  ";

    public String generate(GraalVmMetadata metadata) {
        StringBuilder json = new StringBuilder();
        json.append("{").append('\n');
        appendComment(json, metadata);
        json.append(",").append('\n');
        appendReflection(json, metadata);
        json.append(",").append('\n');
        appendResources(json, metadata.resourceGlobs());
        if (metadata.foreignCallsDetected()) {
            json.append(",").append('\n');
            appendForeign(json);
        }
        json.append('\n').append("}").append('\n');
        return json.toString();
    }

    private void appendComment(StringBuilder json, GraalVmMetadata metadata) {
        List<String> comments = new java.util.ArrayList<>(List.of(
                "Heuristic reachability-metadata.json scaffold generated by BootUI.",
                "Review and complete it with the GraalVM tracing agent before relying on it.",
                "Place it under src/main/resources/META-INF/native-image/<groupId>/<artifactId>/."));
        if (metadata.proxyCallsDetected()) {
            comments.add(
                    "Dynamic proxy calls were detected. Add reflection entries whose type is {\"proxy\":[\"fully.qualified.Interface\"]}; static analysis cannot safely infer runtime-computed interface arrays.");
        }
        if (metadata.unsafeAllocationDetected()) {
            comments.add(
                    "Unsafe.allocateInstance calls were detected. Set unsafeAllocated:true on each actual target type; static analysis cannot safely infer runtime-computed Class arguments.");
        }
        if (metadata.foreignCallsDetected()) {
            comments.add(
                    "FFM Linker usage was detected. Populate foreign.downcalls/upcalls/directUpcalls with the actual FunctionDescriptor layouts; static analysis cannot safely infer runtime-computed layouts.");
        }
        json.append(INDENT).append("\"comment\": [").append('\n');
        for (int i = 0; i < comments.size(); i++) {
            json.append(INDENT).append(INDENT).append(quote(comments.get(i)));
            json.append(i < comments.size() - 1 ? "," : "").append('\n');
        }
        json.append(INDENT).append("]");
    }

    private void appendReflection(StringBuilder json, GraalVmMetadata metadata) {
        Set<String> types = new TreeSet<>();
        types.addAll(metadata.reflectionTypes());
        types.addAll(metadata.serializationTypes());
        types.addAll(metadata.jniTypes());
        json.append(INDENT).append("\"reflection\": [");
        if (types.isEmpty()) {
            json.append("]");
            return;
        }
        json.append('\n');
        int index = 0;
        for (String type : types) {
            json.append(INDENT).append(INDENT).append("{").append('\n');
            json.append(INDENT)
                    .append(INDENT)
                    .append(INDENT)
                    .append("\"condition\": {\"typeReached\": ")
                    .append(quote(type))
                    .append("},")
                    .append('\n');
            json.append(INDENT)
                    .append(INDENT)
                    .append(INDENT)
                    .append("\"type\": ")
                    .append(quote(type))
                    .append(",")
                    .append('\n');
            json.append(INDENT)
                    .append(INDENT)
                    .append(INDENT)
                    .append("\"allDeclaredConstructors\": true,")
                    .append('\n');
            json.append(INDENT)
                    .append(INDENT)
                    .append(INDENT)
                    .append("\"allDeclaredMethods\": true,")
                    .append('\n');
            json.append(INDENT)
                    .append(INDENT)
                    .append(INDENT)
                    .append("\"allDeclaredFields\": true")
                    .append(
                            metadata.serializationTypes().contains(type)
                                            || metadata.jniTypes().contains(type)
                                    ? ","
                                    : "")
                    .append('\n');
            if (metadata.serializationTypes().contains(type)) {
                json.append(INDENT)
                        .append(INDENT)
                        .append(INDENT)
                        .append("\"serializable\": true")
                        .append(metadata.jniTypes().contains(type) ? "," : "")
                        .append('\n');
            }
            if (metadata.jniTypes().contains(type)) {
                json.append(INDENT)
                        .append(INDENT)
                        .append(INDENT)
                        .append("\"jniAccessible\": true")
                        .append('\n');
            }
            json.append(INDENT)
                    .append(INDENT)
                    .append("}")
                    .append(index++ < types.size() - 1 ? "," : "")
                    .append('\n');
        }
        json.append(INDENT).append("]");
    }

    private void appendResources(StringBuilder json, List<String> globs) {
        json.append(INDENT).append("\"resources\": [");
        if (globs.isEmpty()) {
            json.append("]");
            return;
        }
        json.append('\n');
        for (int i = 0; i < globs.size(); i++) {
            json.append(INDENT)
                    .append(INDENT)
                    .append("{\"glob\": ")
                    .append(quote(globs.get(i)))
                    .append("}");
            json.append(i < globs.size() - 1 ? "," : "").append('\n');
        }
        json.append(INDENT).append("]");
    }

    private void appendForeign(StringBuilder json) {
        json.append(INDENT).append("\"foreign\": {").append('\n');
        json.append(INDENT).append(INDENT).append("\"downcalls\": [],").append('\n');
        json.append(INDENT).append(INDENT).append("\"upcalls\": [],").append('\n');
        json.append(INDENT).append(INDENT).append("\"directUpcalls\": []").append('\n');
        json.append(INDENT).append("}");
    }

    private static String quote(String value) {
        StringBuilder sb = new StringBuilder(value.length() + 2);
        sb.append('"');
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            switch (c) {
                case '"' -> sb.append("\\\"");
                case '\\' -> sb.append("\\\\");
                case '\b' -> sb.append("\\b");
                case '\f' -> sb.append("\\f");
                case '\n' -> sb.append("\\n");
                case '\r' -> sb.append("\\r");
                case '\t' -> sb.append("\\t");
                default -> {
                    if (c < 0x20) {
                        sb.append(String.format("\\u%04x", (int) c));
                    } else {
                        sb.append(c);
                    }
                }
            }
        }
        sb.append('"');
        return sb.toString();
    }
}
