package io.github.jdubois.bootui.engine.databaseadvisor;

import static io.github.jdubois.bootui.engine.databaseadvisor.DatabaseAdvisorFixtures.column;
import static io.github.jdubois.bootui.engine.databaseadvisor.DatabaseAdvisorFixtures.context;
import static io.github.jdubois.bootui.engine.databaseadvisor.DatabaseAdvisorFixtures.schema;
import static io.github.jdubois.bootui.engine.databaseadvisor.DatabaseAdvisorFixtures.table;
import static org.assertj.core.api.Assertions.assertThat;

import io.github.jdubois.bootui.core.dto.DatabaseAdvisorRuleResultDto;
import java.sql.DatabaseMetaData;
import java.sql.Types;
import java.util.List;
import org.junit.jupiter.api.Test;

class DatabaseAdvisorSchemaRulesTests {

    @Test
    void aSingleUnknownIndexHasNoDuplicatePairToAssess() {
        IndexModel unknown = new IndexModel(
                "ix",
                List.of(IndexKeyPart.column("id", true)),
                false,
                null,
                null,
                IndexModel.Visibility.UNKNOWN,
                IndexModel.Validity.UNKNOWN);
        DatabaseAdvisorContext context = context(schema(
                "ds",
                Dialect.GENERIC,
                List.of(table(
                        "one", List.of(column("id", "int", Types.INTEGER)), List.of(), List.of(), List.of(unknown)))));
        assertThat(new DuplicateIndexRule().evaluate(context).status()).isEqualTo("SKIPPED");
        assertThat(context.evaluationDiagnostics()).isEmpty();
    }

    @Test
    void missingPrimaryKeyIsAnObservedStructuralReview() {
        TableModel without =
                table("audit", List.of(column("event", "text", Types.VARCHAR)), List.of(), List.of(), List.of());
        TableModel with =
                table("account", List.of(column("id", "int4", Types.INTEGER)), List.of("id"), List.of(), List.of());
        assertThat(evaluate(new MissingPrimaryKeyRule(), without).status()).isEqualTo("VIOLATION");
        assertThat(evaluate(new MissingPrimaryKeyRule(), without)
                        .sampleViolations()
                        .get(0))
                .contains("reported by JDBC")
                .doesNotContain("unsafe");
        assertThat(evaluate(new MissingPrimaryKeyRule(), with).status()).isEqualTo("PASS");
    }

    @Test
    void exclusionsAndUnreadKeysAreSkippedRatherThanPassed() {
        TableModel migration = table("DATABASECHANGELOG", List.of(), List.of(), List.of(), List.of());
        TableModel extension =
                table("ext", List.of(), List.of(), List.of(), List.of()).withPlacement(false, false, true);
        TableModel partition =
                table("part", List.of(), List.of(), List.of(), List.of()).withPlacement(false, true, false);
        for (TableModel excluded : List.of(migration, extension, partition)) {
            assertThat(evaluate(new MissingPrimaryKeyRule(), excluded).status()).isEqualTo("SKIPPED");
        }
        assertThat(evaluate(new MissingPrimaryKeyRule(), incomplete(migration, false, true))
                        .status())
                .isEqualTo("SKIPPED");
    }

    @Test
    void noEligibleTargetsNeverPassesAnyGenericRule() {
        for (DatabaseAdvisorRule rule : List.of(
                new MissingPrimaryKeyRule(),
                new MissingForeignKeyIndexRule(),
                new DuplicateIndexRule(),
                new ForeignKeyTypeMismatchRule(),
                new RedundantPrimaryKeyUniqueIndexRule(),
                new DuplicateForeignKeyRule(),
                new NarrowAutoGeneratedPrimaryKeyRule())) {
            assertThat(rule.evaluate(context(schema("ds", Dialect.GENERIC, List.of())))
                            .status())
                    .as(rule.definition().id())
                    .isEqualTo("SKIPPED");
        }
    }

    @Test
    void foreignKeyAccessPathAcceptsAllLeadingColumnsInEitherOrderAndTrailingExpression() {
        for (List<IndexKeyPart> parts : List.of(
                List.of(IndexKeyPart.column("a", true), IndexKeyPart.column("b", true)),
                List.of(IndexKeyPart.column("b", true), IndexKeyPart.column("a", true)),
                List.of(
                        IndexKeyPart.column("b", true),
                        IndexKeyPart.column("a", true),
                        IndexKeyPart.expression("lower(note)")))) {
            IndexModel index = new IndexModel(
                    "ix", parts, false, "btree", null, IndexModel.Visibility.VISIBLE, IndexModel.Validity.VALID);
            assertThat(evaluate(new MissingForeignKeyIndexRule(), child(List.of(index)))
                            .status())
                    .isEqualTo("PASS");
        }
    }

    @Test
    void incompleteLeadingSetPromptsReviewWithoutPredictingScans() {
        DatabaseAdvisorRuleResultDto result = evaluate(
                new MissingForeignKeyIndexRule(), child(List.of(index("ix", List.of("a"), false, List.of(), null))));
        assertThat(result.status()).isEqualTo("VIOLATION");
        assertThat(result.severity()).isEqualTo(DatabaseAdvisorRuleSupport.MEDIUM);
        assertThat(result.sampleViolations().get(0)).contains("not proof of a table scan");
    }

    @Test
    void prefixPartialUnknownAndTruncatedIndexesCannotProveAnAbsentAccessPath() {
        List<IndexModel> uncertain = List.of(
                new IndexModel(
                        "prefix",
                        List.of(new IndexKeyPart("a", null, true, 10, null)),
                        false,
                        "btree",
                        null,
                        IndexModel.Visibility.VISIBLE,
                        IndexModel.Validity.VALID),
                new IndexModel(
                        "partial",
                        List.of(IndexKeyPart.column("a", true)),
                        false,
                        "btree",
                        "a > 0",
                        IndexModel.Visibility.VISIBLE,
                        IndexModel.Validity.VALID),
                IndexModel.of("unknown", List.of("z"), false));
        for (IndexModel index : uncertain) {
            DatabaseAdvisorContext context = context(schema("ds", Dialect.POSTGRESQL, List.of(child(List.of(index)))));
            assertThat(new MissingForeignKeyIndexRule().evaluate(context).status())
                    .isEqualTo("SKIPPED");
            assertThat(context.evaluationDiagnostics()).isNotEmpty();
        }
        assertThat(evaluate(new MissingForeignKeyIndexRule(), incomplete(child(List.of()), true, false))
                        .status())
                .isEqualTo("SKIPPED");
    }

    @Test
    void mysqlMissingRequiredIndexIsACollectionContradiction() {
        DatabaseAdvisorContext context = context(schema("ds", Dialect.MYSQL, List.of(child(List.of()))));
        assertThat(new MissingForeignKeyIndexRule().evaluate(context).status()).isEqualTo("SKIPPED");
        assertThat(context.evaluationDiagnostics())
                .anySatisfy(diagnostic -> assertThat(diagnostic.message()).contains("reconcile metadata"));
    }

    @Test
    void onlyExactKnownIndexDefinitionsAreDuplicateCandidates() {
        IndexModel first = index("first", List.of("a"), false, List.of("payload"), null);
        IndexModel same = index("same", List.of("a"), false, List.of("payload"), null);
        assertThat(evaluate(new DuplicateIndexRule(), indexed(first, same)).status())
                .isEqualTo("VIOLATION");
        for (IndexModel different : List.of(
                index("longer", List.of("a", "b"), false, List.of("payload"), null),
                index("payload", List.of("a"), false, List.of("other"), null),
                index("unique", List.of("a"), true, List.of("payload"), null),
                index("case", List.of("A"), false, List.of("payload"), null))) {
            assertThat(evaluate(new DuplicateIndexRule(), indexed(first, different))
                            .status())
                    .isEqualTo("PASS");
        }
        assertThat(evaluate(
                                new DuplicateIndexRule(),
                                indexed(
                                        IndexModel.of("x", List.of("a"), false),
                                        IndexModel.of("y", List.of("a"), false)))
                        .status())
                .isEqualTo("SKIPPED");
    }

    @Test
    void intentionalIndexComparisonExclusionsDoNotProduceUnknownWarnings() {
        TableModel table = indexed(
                index("owned", List.of("a"), true, List.of(), "constraint"),
                new IndexModel(
                        "partial",
                        List.of(IndexKeyPart.column("a", true)),
                        false,
                        "btree",
                        "a > 0",
                        IndexModel.Visibility.VISIBLE,
                        IndexModel.Validity.VALID));
        DatabaseAdvisorContext context = context(schema("ds", Dialect.GENERIC, List.of(table)));
        assertThat(new DuplicateIndexRule().evaluate(context).status()).isEqualTo("SKIPPED");
        assertThat(context.evaluationDiagnostics()).isEmpty();
    }

    @Test
    void orderingCollationAndUnknownExpressionsDoNotProveEquivalence() {
        IndexModel first = index("x", List.of("a"), false, List.of(), null);
        IndexModel descending = complete("y", List.of(new IndexKeyPart("a", null, false, null, null)), false);
        IndexModel collation = complete("y", List.of(new IndexKeyPart("a", null, true, null, "special")), false);
        for (IndexModel other : List.of(descending, collation)) {
            assertThat(first.exactDuplicateOf(other)).isFalse();
        }
        IndexModel expression = complete("expr", List.of(IndexKeyPart.expression(null)), false);
        assertThat(expression.exactDuplicateOf(expression)).isFalse();
    }

    @Test
    void primaryKeyBackingIndexIsNeverGuessedFromItsNameOrColumns() {
        TableModel table = table(
                "t",
                List.of(column("a", "int4", Types.INTEGER)),
                List.of("a"),
                List.of(),
                List.of(
                        index("pk_t", List.of("a"), true, List.of(), null),
                        index("extra", List.of("a"), true, List.of(), null)));
        assertThat(table.primaryKeyBackingIndex()).isNull();
        assertThat(evaluate(new RedundantPrimaryKeyUniqueIndexRule(), table).status())
                .isEqualTo("SKIPPED");
        TableModel proven = table.withIndexes(List.of(
                index("actual", List.of("a"), true, List.of(), "pk_t"),
                index("extra", List.of("a"), true, List.of(), null)));
        assertThat(proven.primaryKeyBackingIndex().name()).isEqualTo("actual");
        assertThat(evaluate(new RedundantPrimaryKeyUniqueIndexRule(), proven).status())
                .isEqualTo("VIOLATION");
        assertThat(evaluate(
                                new RedundantPrimaryKeyUniqueIndexRule(),
                                proven.withIndexes(List.of(
                                        proven.indexes().get(0),
                                        index("extra", List.of("a"), true, List.of("payload"), null))))
                        .status())
                .isEqualTo("PASS");
    }

    @Test
    void foreignKeyDuplicateRequiresKnownMatchingActionsAndExactPairedIdentity() {
        ForeignKeyModel first = fk("one", List.of("a", "b"), List.of("x", "y"), 0);
        ForeignKeyModel reordered = fk("two", List.of("b", "a"), List.of("y", "x"), 0);
        assertThat(evaluate(new DuplicateForeignKeyRule(), keys(first, reordered))
                        .status())
                .isEqualTo("VIOLATION");
        for (ForeignKeyModel other : List.of(
                fk("action", List.of("a", "b"), List.of("x", "y"), 1),
                fk("pairs", List.of("a", "b"), List.of("y", "x"), 0),
                fk("case", List.of("A", "b"), List.of("x", "y"), 0),
                new ForeignKeyModel(
                        "deferred",
                        first.columns(),
                        "app",
                        "public",
                        "parent",
                        first.referencedColumns(),
                        0,
                        0,
                        DatabaseMetaData.importedKeyInitiallyDeferred))) {
            assertThat(evaluate(new DuplicateForeignKeyRule(), keys(first, other))
                            .status())
                    .isEqualTo("PASS");
        }
        ForeignKeyModel unknown =
                new ForeignKeyModel("unknown", first.columns(), "app", "public", "parent", first.referencedColumns());
        assertThat(evaluate(new DuplicateForeignKeyRule(), keys(first, unknown)).status())
                .isEqualTo("SKIPPED");
    }

    @Test
    void foreignKeyDuplicatePairsDoNotCollideOnPunctuation() {
        ForeignKeyModel first = fk("one", List.of("a->b"), List.of("c"), 0);
        ForeignKeyModel second = fk("two", List.of("a"), List.of("b->c"), 0);
        assertThat(evaluate(new DuplicateForeignKeyRule(), keys(first, second)).status())
                .isEqualTo("PASS");
    }

    @Test
    void domainNarrowingUsesTheActualAlternateReferencedColumn() {
        TableModel parent = table(
                "parent",
                List.of(column("id", "int8", Types.BIGINT), column("alternate", "int4", Types.INTEGER)),
                List.of("id"),
                List.of(),
                List.of());
        TableModel child = table(
                "child",
                List.of(column("a", "int4", Types.INTEGER)),
                List.of(),
                List.of(fk("fk", List.of("a"), List.of("alternate"), 0)),
                List.of());
        assertThat(new ForeignKeyTypeMismatchRule()
                        .evaluate(context(schema("ds", Dialect.POSTGRESQL, List.of(parent, child))))
                        .status())
                .isEqualTo("PASS");
        TableModel narrowed =
                table("child", List.of(column("a", "int2", Types.SMALLINT)), List.of(), child.foreignKeys(), List.of());
        assertThat(new ForeignKeyTypeMismatchRule()
                        .evaluate(context(schema("ds", Dialect.POSTGRESQL, List.of(parent, narrowed))))
                        .status())
                .isEqualTo("VIOLATION");
    }

    @Test
    void decimalContainmentConsidersBothIntegerAndFractionalCapacity() {
        assertThat(ColumnTypeCompatibility.mismatch(decimal(12, 4), decimal(10, 2)))
                .isNull();
        assertThat(ColumnTypeCompatibility.mismatch(decimal(10, 4), decimal(10, 2)))
                .contains("integer-digit");
        assertThat(ColumnTypeCompatibility.mismatch(decimal(12, 1), decimal(10, 2)))
                .contains("fractional");
        assertThat(ColumnTypeCompatibility.mismatch(decimal(10, null), decimal(10, 2)))
                .isNull();
        assertThat(ColumnTypeCompatibility.comparable(decimal(10, null), decimal(10, 2)))
                .isFalse();
        assertThat(ColumnTypeCompatibility.mismatch(
                        column("a", "varchar", Types.VARCHAR, 20), column("b", "int4", Types.INTEGER)))
                .isNull();
    }

    @Test
    void signedAndUnsignedContainmentDoesNotFlagAWiderSignedChild() {
        assertThat(ColumnTypeCompatibility.mismatch(
                        column("a", "bigint", Types.BIGINT), column("b", "int unsigned", Types.INTEGER)))
                .isNull();
        assertThat(ColumnTypeCompatibility.mismatch(
                        column("a", "int", Types.INTEGER), column("b", "int unsigned", Types.INTEGER)))
                .contains("signedness");
        assertThat(ColumnTypeCompatibility.mismatch(
                        column("a", "bigint unsigned", Types.BIGINT), column("b", "int", Types.INTEGER)))
                .contains("signedness");
    }

    @Test
    void generatedSmallKeyReportsBoundsNotLifetimeRows() {
        for (String type : List.of("smallint", "smallint unsigned", "tinyint")) {
            ColumnModel column =
                    new ColumnModel("id", type, Types.SMALLINT, ColumnModel.Nullability.NOT_NULL, null, null, true);
            DatabaseAdvisorRuleResultDto result = evaluate(
                    new NarrowAutoGeneratedPrimaryKeyRule(),
                    table("t", List.of(column), List.of("id"), List.of(), List.of()));
            assertThat(result.status()).isEqualTo("VIOLATION");
            assertThat(result.severity()).isEqualTo(DatabaseAdvisorRuleSupport.LOW);
            assertThat(result.sampleViolations().get(0))
                    .contains("representable type bounds", "not observed exhaustion")
                    .doesNotContain("distinct values", "rows ever inserted");
        }
        assertThat(evaluate(
                                new NarrowAutoGeneratedPrimaryKeyRule(),
                                table(
                                        "t",
                                        List.of(column("id", "smallint", Types.SMALLINT)),
                                        List.of("id"),
                                        List.of(),
                                        List.of()))
                        .status())
                .isEqualTo("SKIPPED");
    }

    @Test
    void mixedNullabilityRulesAreRetiredForEveryDialect() {
        for (Dialect dialect : Dialect.values()) {
            DatabaseAdvisorContext context = context(schema("ds", dialect, List.of(child(List.of()))));
            assertThat(new CompositeForeignKeyPartialNullabilityRule()
                            .evaluate(context)
                            .status())
                    .isEqualTo("SKIPPED");
            assertThat(new NullableColumnCompositeUniquenessRule()
                            .evaluate(context)
                            .status())
                    .isEqualTo("SKIPPED");
        }
    }

    @Test
    void invisibleUniqueIndexStillEnforcesUniqueness() {
        IndexModel invisible = new IndexModel(
                "u",
                List.of(IndexKeyPart.column("a", true)),
                true,
                "btree",
                null,
                IndexModel.Visibility.INVISIBLE,
                IndexModel.Validity.VALID);
        assertThat(invisible.enforcesUniquenessOver(List.of("a"))).isTrue();
        assertThat(invisible.supportsLeadingEquality(List.of("a"))).isFalse();
    }

    @Test
    void knownUniqueSubsetsAndValuePrefixesAreStrongerThanTheRequestedTuple() {
        IndexModel subset = index("u", List.of("a"), true, List.of(), null);
        assertThat(subset.uniquenessCoverage(List.of("a", "b"))).isEqualTo(IndexModel.UniquenessCoverage.UNKNOWN);
        assertThat(subset.uniquenessCoverage(List.of("a", "b"), true))
                .isEqualTo(IndexModel.UniquenessCoverage.ENFORCED);
        assertThat(subset.uniquenessCoverage(List.of("b"))).isEqualTo(IndexModel.UniquenessCoverage.NOT_ENFORCED);
        IndexModel prefix = new IndexModel(
                "prefix",
                List.of(new IndexKeyPart("a", null, true, 10, null)),
                true,
                "btree",
                null,
                IndexModel.Visibility.INVISIBLE,
                IndexModel.Validity.VALID);
        assertThat(prefix.uniquenessCoverage(List.of("a", "b"))).isEqualTo(IndexModel.UniquenessCoverage.UNKNOWN);
        assertThat(prefix.uniquenessCoverage(List.of("a", "b"), true))
                .isEqualTo(IndexModel.UniquenessCoverage.ENFORCED);
        assertThat(prefix.uniquenessCoverage(List.of("a"))).isEqualTo(IndexModel.UniquenessCoverage.ENFORCED);
        assertThat(IndexModel.of("unknown", List.of("a"), true).uniquenessCoverage(List.of("a")))
                .isEqualTo(IndexModel.UniquenessCoverage.UNKNOWN);
    }

    @Test
    void tableUniqueSubsetRequiresKnownNullSemantics() {
        IndexModel index = index("u", List.of("a"), true, List.of(), null);
        TableModel nullable =
                table("t", List.of(column("a", "int4", Types.INTEGER)), List.of(), List.of(), List.of(index));
        assertThat(nullable.uniquenessCoverage(List.of("a", "b"))).isEqualTo(IndexModel.UniquenessCoverage.UNKNOWN);
        TableModel notNull = table(
                "t",
                List.of(new ColumnModel(
                        "a", "int4", Types.INTEGER, ColumnModel.Nullability.NOT_NULL, null, null, false)),
                List.of(),
                List.of(),
                List.of(index));
        assertThat(notNull.uniquenessCoverage(List.of("a", "b"))).isEqualTo(IndexModel.UniquenessCoverage.ENFORCED);
        IndexModel nullsNotDistinct = new IndexModel(
                "u",
                index.keyParts(),
                true,
                "btree",
                null,
                IndexModel.Visibility.VISIBLE,
                IndexModel.Validity.VALID,
                true,
                false,
                false,
                false);
        assertThat(nullsNotDistinct.uniquenessCoverage(List.of("a", "b")))
                .isEqualTo(IndexModel.UniquenessCoverage.ENFORCED);
    }

    @Test
    void primaryKeySubsetNeedsKnownEnforcementRatherThanJustADeclaredName() {
        TableModel table = table("t", List.of(), List.of("a"), List.of(), List.of());
        assertThat(table.uniquenessCoverage(List.of("a", "b"))).isEqualTo(IndexModel.UniquenessCoverage.UNKNOWN);
        assertThat(table.withMetadata(table.metadata().withPrimaryKeyEnforced(true))
                        .uniquenessCoverage(List.of("a", "b")))
                .isEqualTo(IndexModel.UniquenessCoverage.ENFORCED);
        assertThat(table.withMetadata(table.metadata().withPrimaryKeyEnforced(false))
                        .uniquenessCoverage(List.of("a", "b")))
                .isEqualTo(IndexModel.UniquenessCoverage.NOT_ENFORCED);
    }

    @Test
    void knownDifferentForeignKeyEnforcementAndMatchModesAreNotDuplicates() {
        ForeignKeyModel base = fk("first", List.of("a"), List.of("x"), 0);
        ForeignKeyModel other = fk("second", List.of("a"), List.of("x"), 0);
        assertThat(evaluate(
                                new DuplicateForeignKeyRule(),
                                keys(
                                        base.withEnforcement(true, true, "SIMPLE"),
                                        other.withEnforcement(false, true, "SIMPLE")))
                        .status())
                .isEqualTo("PASS");
        assertThat(evaluate(
                                new DuplicateForeignKeyRule(),
                                keys(
                                        base.withEnforcement(true, true, "SIMPLE"),
                                        other.withEnforcement(true, true, "FULL")))
                        .status())
                .isEqualTo("PASS");
    }

    @Test
    void exactObjectLookupPreservesQualifiersCaseAndAmbiguity() {
        TableModel lower = TableModel.of(
                "app", "public", "t", List.of(column("x", "int4", Types.INTEGER)), List.of(), List.of(), List.of());
        TableModel upper = TableModel.of(
                "app", "public", "T", List.of(column("X", "int4", Types.INTEGER)), List.of(), List.of(), List.of());
        TableModel other = TableModel.of("app", "other", "t", List.of(), List.of(), List.of(), List.of());
        SchemaSnapshot snapshot = schema("ds", Dialect.POSTGRESQL, List.of(lower, upper, other));
        assertThat(snapshot.table("t")).isNull();
        assertThat(snapshot.table("app", "public", "T")).isSameAs(upper);
        assertThat(snapshot.exactTable(null, "public", "t")).isNull();
        assertThat(lower.column("X")).isNull();
        assertThat(snapshot.declaredTablesNamed("app", "public", "\"T\"")).containsExactly(upper);
        assertThat(snapshot.declaredTablesNamed("app", "public", "T")).containsExactly(lower);
        assertThat(snapshot.declaredColumn(lower, "X")).isSameAs(lower.column("x"));
        assertThat(snapshot.declaredColumn(lower, "\"X\"")).isNull();
        assertThat(snapshot.declaredMatches("a\"b", "\"a\"\"b\"")).isTrue();
    }

    @Test
    void unknownAndKnownInsensitiveIdentifierRulesRemainDistinct() {
        SchemaSnapshot unknown = new SchemaSnapshot(
                "ds",
                Dialect.GENERIC,
                "generic",
                DatabaseVersion.UNKNOWN,
                null,
                List.of(),
                VendorFindings.EMPTY,
                List.of(),
                false,
                null);
        assertThat(unknown.declarationCaseKnown("unquoted")).isFalse();
        assertThat(unknown.declarationCaseKnown("\"quoted\"")).isTrue();
        SchemaSnapshot insensitive = new SchemaSnapshot(
                "ds",
                Dialect.GENERIC,
                "generic",
                DatabaseVersion.UNKNOWN,
                "INSENSITIVE",
                List.of(),
                VendorFindings.EMPTY,
                List.of(),
                false,
                null);
        assertThat(insensitive.declaredMatches("Mixed", "MIXED")).isTrue();
        assertThat(insensitive.declaredMatches("Mixed", "\"MIXED\"")).isFalse();
    }

    @Test
    void tableAndVendorTruncationReachSnapshotStatusWithoutRequiringDiagnosticText() {
        TableModel incomplete = incomplete(child(List.of()), true, false);
        assertThat(schema("ds", Dialect.POSTGRESQL, List.of(incomplete)).truncated())
                .isTrue();
        VendorFindings findings = VendorFindings.builder()
                .add(VendorAugmentation.available(VendorFindingKinds.POSTGRES_EXTENSION_TABLES, List.of(), true))
                .build();
        SchemaSnapshot snapshot = schema("ds", Dialect.POSTGRESQL, List.of(), findings);
        assertThat(snapshot.truncated()).isTrue();
        assertThat(snapshot.complete()).isFalse();
    }

    private static ColumnModel decimal(int precision, Integer scale) {
        return new ColumnModel(
                "n", "numeric", Types.NUMERIC, ColumnModel.Nullability.NULLABLE, precision, scale, false);
    }

    private static DatabaseAdvisorRuleResultDto evaluate(DatabaseAdvisorRule rule, TableModel table) {
        return rule.evaluate(context(schema("ds", Dialect.POSTGRESQL, List.of(table))));
    }

    private static ForeignKeyModel fk(String name, List<String> child, List<String> parent, int action) {
        return new ForeignKeyModel(
                name,
                child,
                "app",
                "public",
                "parent",
                parent,
                action,
                action,
                DatabaseMetaData.importedKeyNotDeferrable);
    }

    private static TableModel child(List<IndexModel> indexes) {
        return table(
                "child",
                List.of(column("a", "int4", Types.INTEGER), column("b", "int4", Types.INTEGER)),
                List.of(),
                List.of(fk("fk", List.of("a", "b"), List.of("x", "y"), 0)),
                indexes);
    }

    private static TableModel keys(ForeignKeyModel... foreignKeys) {
        return table("child", List.of(), List.of(), List.of(foreignKeys), List.of());
    }

    private static TableModel indexed(IndexModel... indexes) {
        return table("t", List.of(), List.of(), List.of(), List.of(indexes));
    }

    private static IndexModel index(
            String name, List<String> columns, boolean unique, List<String> included, String backing) {
        return new IndexModel(
                name,
                columns.stream()
                        .map(column -> IndexKeyPart.column(column, true))
                        .toList(),
                unique,
                "btree",
                null,
                IndexModel.Visibility.VISIBLE,
                IndexModel.Validity.VALID,
                false,
                false,
                false,
                false,
                included,
                true,
                true,
                backing);
    }

    private static IndexModel complete(String name, List<IndexKeyPart> parts, boolean unique) {
        return new IndexModel(
                name,
                parts,
                unique,
                "btree",
                null,
                IndexModel.Visibility.VISIBLE,
                IndexModel.Validity.VALID,
                false,
                false,
                false,
                false,
                List.of(),
                true,
                true,
                null);
    }

    private static TableModel incomplete(TableModel table, boolean primaryKeysRead, boolean indexesRead) {
        return new TableModel(
                table.catalog(),
                table.schema(),
                table.name(),
                table.type(),
                table.columns(),
                table.primaryKeyName(),
                table.primaryKeyColumns(),
                table.foreignKeys(),
                table.indexes(),
                table.partitionParent(),
                table.partitionChild(),
                table.extensionOwned(),
                new TableMetadata(true, primaryKeysRead, true, indexesRead, true, List.of("truncated")));
    }
}
