package io.github.jdubois.bootui.autoconfigure.sourcetree;

import java.io.IOException;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.CodeSource;
import java.security.ProtectionDomain;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.function.Supplier;
import org.jspecify.annotations.Nullable;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.info.BuildProperties;
import org.springframework.context.ApplicationContext;
import org.springframework.util.ClassUtils;

/**
 * Shared, fail-closed writer for scaffolding that BootUI generates directly into the host
 * application's own source tree (for example a GraalVM {@code Dockerfile-native} or a CRaC
 * {@code Dockerfile-crac}).
 *
 * <p>Writing in place is only offered when the application is detectably running from an exploded
 * build (e.g. {@code target/classes} via {@code mvn spring-boot:run} or an IDE), <em>not</em> from a
 * packaged fat jar where there is no source tree to write into. Every write is confined to its
 * resolved target and refuses to clobber a file that does not already carry the
 * {@link #GENERATED_MARKER}, so a hand-written file is never overwritten.
 *
 * <p>The class is deliberately feature-agnostic: it resolves the project root, the application's
 * Maven coordinates, and project-root file targets, and performs the guarded write. Feature-specific
 * placement (such as the GraalVM {@code META-INF/native-image} metadata directory) is layered on top
 * by the panels that use it.
 */
public final class ProjectSourceTree {

    /** Substring of a generated file's comment block, used to detect a previously generated file. */
    public static final String GENERATED_MARKER = "generated by BootUI";

    private static final String DEFAULT_ARTIFACT = "app";

    private final Supplier<Path> projectRootSupplier;
    private final Supplier<Optional<URL>> codeSourceSupplier;
    private final Supplier<Optional<Coordinates>> coordinatesSupplier;

    public ProjectSourceTree(
            Supplier<Path> projectRootSupplier,
            Supplier<Optional<URL>> codeSourceSupplier,
            Supplier<Optional<Coordinates>> coordinatesSupplier) {
        this.projectRootSupplier = projectRootSupplier;
        this.codeSourceSupplier = codeSourceSupplier;
        this.coordinatesSupplier = coordinatesSupplier;
    }

    /**
     * Builds the default source tree for a running application: the project root is the process
     * working directory, the code source is the {@code @SpringBootApplication} class's location (used
     * to tell an exploded build from a packaged jar), and the Maven coordinates resolve from
     * {@code build-info.properties} or the project {@code pom.xml}.
     */
    public static ProjectSourceTree forApplication(ApplicationContext applicationContext) {
        return new ProjectSourceTree(
                () -> Path.of(System.getProperty("user.dir", ".")),
                () -> applicationCodeSource(applicationContext),
                () -> coordinates(applicationContext));
    }

    /** Best-effort absolute project root, or {@code null} when it cannot be determined. */
    public @Nullable Path projectRoot() {
        try {
            Path root = projectRootSupplier.get();
            return root == null ? null : root.toAbsolutePath().normalize();
        } catch (RuntimeException ex) {
            return null;
        }
    }

    /** Best-effort code-source location of the host application's main class. */
    public Optional<URL> codeSource() {
        try {
            Optional<URL> codeSource = codeSourceSupplier.get();
            return codeSource == null ? Optional.empty() : codeSource;
        } catch (RuntimeException ex) {
            return Optional.empty();
        }
    }

    /** Best-effort Maven coordinates of the host application. */
    public Optional<Coordinates> coordinates() {
        try {
            Optional<Coordinates> coordinates = coordinatesSupplier.get();
            return coordinates == null ? Optional.empty() : coordinates;
        } catch (RuntimeException ex) {
            return Optional.empty();
        }
    }

    /**
     * Returns the resolved Maven {@code artifactId} (used to name a native executable or container
     * image), or {@code "app"} when coordinates cannot be resolved.
     */
    public String artifactName() {
        return coordinates()
                .filter(Coordinates::isValid)
                .map(resolved -> sanitize(resolved.artifactId()))
                .filter(name -> !name.isBlank())
                .orElse(DEFAULT_ARTIFACT);
    }

    /** Resolves whether (and where) a file named {@code fileName} can be written to the project root. */
    public Resolution resolveProjectRootFile(String fileName) {
        Path projectRoot;
        Optional<URL> codeSource;
        try {
            projectRoot = projectRootSupplier.get();
            codeSource = codeSourceSupplier.get();
        } catch (RuntimeException ex) {
            return Resolution.unavailable("The application source layout could not be determined.");
        }
        return resolveProjectRootFile(projectRoot, codeSource.orElse(null), fileName);
    }

    /** Resolves a project-root file target. Static so it can be unit tested with explicit inputs. */
    public static Resolution resolveProjectRootFile(
            @Nullable Path projectRoot, @Nullable URL codeSourceLocation, String fileName) {
        if (projectRoot == null) {
            return Resolution.unavailable("The application working directory could not be determined.");
        }
        if (!isExplodedClasses(codeSourceLocation)) {
            return Resolution.unavailable(
                    "The application is not running from an exploded build (for example a packaged jar), "
                            + "so there is no project directory to write into.");
        }
        Path root = projectRoot.toAbsolutePath().normalize();
        if (!Files.isDirectory(root)) {
            return Resolution.unavailable("The project directory " + root + " could not be found.");
        }
        if (!Files.isWritable(root)) {
            return Resolution.unavailable("The project directory is not writable.");
        }
        Path targetFile = root.resolve(fileName).normalize();
        if (!root.equals(targetFile.getParent())) {
            return Resolution.unavailable("The resolved path escapes the project directory.");
        }
        return Resolution.installable(targetFile, root.relativize(targetFile).toString());
    }

    /**
     * Honors the resolution outcome, refuses to overwrite a file that does not carry the
     * {@link #GENERATED_MARKER}, creates any missing parent directories, and writes the supplied
     * content. The per-file wording is supplied by the caller.
     *
     * @param resolution the resolved (and validated) install target
     * @param content the file content to write
     * @param existsMessage builds the "left untouched" message from the display path
     * @param writtenMessage builds the success message from the display path
     * @param errorPrefix prefix for the {@code ERROR} message when the write fails
     */
    public InstallOutcome write(
            Resolution resolution,
            String content,
            Function<String, String> existsMessage,
            Function<String, String> writtenMessage,
            String errorPrefix) {
        if (!resolution.installable()) {
            return new InstallOutcome("UNAVAILABLE", resolution.reason(), null);
        }
        Path targetFile = resolution.targetFile();
        String displayPath = resolution.displayPath();
        try {
            if (Files.exists(targetFile)) {
                String existing = Files.readString(targetFile, StandardCharsets.UTF_8);
                if (!existing.contains(GENERATED_MARKER)) {
                    return new InstallOutcome("EXISTS", existsMessage.apply(displayPath), displayPath);
                }
            }
            Path parent = targetFile.getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }
            Files.writeString(targetFile, content, StandardCharsets.UTF_8);
            return new InstallOutcome("WRITTEN", writtenMessage.apply(displayPath), displayPath);
        } catch (IOException ex) {
            return new InstallOutcome("ERROR", errorPrefix + safeMessage(ex), displayPath);
        }
    }

    /**
     * Returns {@code true} when the supplied code-source location is an exploded classes directory
     * (for example {@code target/classes}) rather than a packaged jar.
     */
    public static boolean isExplodedClasses(@Nullable URL location) {
        if (location == null || !"file".equalsIgnoreCase(location.getProtocol())) {
            return false;
        }
        String path = location.getPath();
        if (path == null || path.isBlank()) {
            return false;
        }
        if (path.toLowerCase(Locale.ROOT).endsWith(".jar")) {
            return false;
        }
        try {
            return Files.isDirectory(Path.of(location.toURI()));
        } catch (RuntimeException | java.net.URISyntaxException ex) {
            // Fall back to the trailing-slash convention that exploded class directories use.
            return path.endsWith("/");
        }
    }

    /** Keeps only the characters that are safe in a Maven coordinate path segment. */
    public static String sanitize(String segment) {
        String trimmed = segment.trim();
        StringBuilder sb = new StringBuilder(trimmed.length());
        for (int i = 0; i < trimmed.length(); i++) {
            char c = trimmed.charAt(i);
            if (Character.isLetterOrDigit(c) || c == '.' || c == '-' || c == '_') {
                sb.append(c);
            }
        }
        return sb.toString();
    }

    /**
     * Best-effort resolution of Maven coordinates from the project root {@code pom.xml}, falling back
     * to the {@code <parent>} groupId when the module does not declare its own. Returns empty when no
     * usable coordinates can be parsed.
     */
    public static Optional<Coordinates> coordinatesFromPom(@Nullable Path projectRoot) {
        if (projectRoot == null) {
            return Optional.empty();
        }
        Path pom = projectRoot.resolve("pom.xml");
        if (!Files.isRegularFile(pom)) {
            return Optional.empty();
        }
        String xml;
        try {
            xml = Files.readString(pom, StandardCharsets.UTF_8);
        } catch (IOException ex) {
            return Optional.empty();
        }
        String beforeDependencies = xml;
        int dependencies = xml.indexOf("<dependencies>");
        if (dependencies > 0) {
            beforeDependencies = xml.substring(0, dependencies);
        }
        String parentBlock = firstElement(beforeDependencies, "parent");
        String artifactId = topLevelValue(beforeDependencies, parentBlock, "artifactId");
        String groupId = topLevelValue(beforeDependencies, parentBlock, "groupId");
        if (groupId == null && parentBlock != null) {
            groupId = elementValue(parentBlock, "groupId");
        }
        if (groupId == null || artifactId == null) {
            return Optional.empty();
        }
        Coordinates coordinates = new Coordinates(groupId, artifactId);
        return coordinates.isValid() ? Optional.of(coordinates) : Optional.empty();
    }

    /** Reads a top-level element value, ignoring any occurrence nested inside the {@code <parent>} block. */
    private static @Nullable String topLevelValue(String pom, @Nullable String parentBlock, String element) {
        String withoutParent = parentBlock == null ? pom : pom.replace(parentBlock, "");
        return elementValue(withoutParent, element);
    }

    private static @Nullable String firstElement(String xml, String element) {
        int open = xml.indexOf("<" + element + ">");
        int close = xml.indexOf("</" + element + ">");
        if (open < 0 || close < 0 || close < open) {
            return null;
        }
        return xml.substring(open, close + element.length() + 3);
    }

    private static @Nullable String elementValue(@Nullable String xml, String element) {
        if (xml == null) {
            return null;
        }
        String value = textBetween(firstElement(xml, element), element);
        return value == null || value.isBlank() ? null : value.trim();
    }

    private static @Nullable String textBetween(@Nullable String elementXml, String element) {
        if (elementXml == null) {
            return null;
        }
        String open = "<" + element + ">";
        int start = elementXml.indexOf(open);
        int end = elementXml.indexOf("</" + element + ">");
        if (start < 0 || end < 0) {
            return null;
        }
        return elementXml.substring(start + open.length(), end);
    }

    private static String safeMessage(Throwable ex) {
        String message = ex.getMessage();
        return message == null || message.isBlank() ? ex.getClass().getSimpleName() : message;
    }

    private static Optional<URL> applicationCodeSource(ApplicationContext applicationContext) {
        try {
            Map<String, Object> beans = applicationContext.getBeansWithAnnotation(SpringBootApplication.class);
            for (Object bean : beans.values()) {
                Class<?> userClass = ClassUtils.getUserClass(bean.getClass());
                ProtectionDomain protectionDomain = userClass.getProtectionDomain();
                if (protectionDomain == null) {
                    continue;
                }
                CodeSource codeSource = protectionDomain.getCodeSource();
                if (codeSource != null && codeSource.getLocation() != null) {
                    return Optional.of(codeSource.getLocation());
                }
            }
        } catch (RuntimeException ex) {
            return Optional.empty();
        }
        return Optional.empty();
    }

    private static Optional<Coordinates> coordinates(ApplicationContext applicationContext) {
        try {
            BuildProperties buildProperties =
                    applicationContext.getBeanProvider(BuildProperties.class).getIfAvailable();
            if (buildProperties != null) {
                Coordinates fromBuild = new Coordinates(buildProperties.getGroup(), buildProperties.getArtifact());
                if (fromBuild.isValid()) {
                    return Optional.of(fromBuild);
                }
            }
        } catch (RuntimeException ex) {
            // Fall through to pom parsing.
        }
        return coordinatesFromPom(Path.of(System.getProperty("user.dir", ".")));
    }

    /** Maven coordinates of the host application. */
    public record Coordinates(String groupId, String artifactId) {

        public boolean isValid() {
            return groupId != null && !groupId.isBlank() && artifactId != null && !artifactId.isBlank();
        }
    }

    /** Outcome of resolving an install target. */
    public record Resolution(
            boolean installable,
            @Nullable Path targetFile,
            @Nullable String displayPath,
            @Nullable String reason) {

        public static Resolution unavailable(String reason) {
            return new Resolution(false, null, reason, reason);
        }

        public static Resolution installable(Path targetFile, String displayPath) {
            // Display paths are shown to users and asserted against literals, so normalize the
            // platform file separator to '/' (relativize() yields '\' on Windows).
            String normalized = displayPath == null ? null : displayPath.replace('\\', '/');
            return new Resolution(true, targetFile, normalized, null);
        }
    }

    /** Outcome of an install attempt. */
    public record InstallOutcome(
            String status, String message, @Nullable String path) {}
}
