package io.github.jdubois.bootui.engine.databaseadvisor;

import java.util.List;

final class DatabaseAdvisorRuleRegistry {

    private static final List<DatabaseAdvisorRule> ACTIVE_RULES = List.of(
            // Schema (generic, all dialects)
            new MissingPrimaryKeyRule(),
            new MissingForeignKeyIndexRule(),
            new DuplicateIndexRule(),
            new ForeignKeyTypeMismatchRule(),
            new RedundantPrimaryKeyUniqueIndexRule(),
            new DuplicateForeignKeyRule(),
            new NarrowAutoGeneratedPrimaryKeyRule(),
            // Schema (dialect-specific catalog augmentation)
            new PostgresInvalidIndexRule(),
            new PostgresSequenceExhaustionRule(),
            new PostgresUnvalidatedConstraintRule(),
            new PostgresReplicaIdentityRule(),
            new MySqlNonInnodbEngineRule(),
            new MySqlNonUtf8mb4CharsetRule(),
            new MySqlAutoIncrementExhaustionRule(),
            new OracleUnusableIndexRule(),
            new OracleInvalidConstraintRule(),
            new OracleSequenceExhaustionRule(),
            // Hibernate <-> physical schema cross-reference
            new HibernateMissingTableRule(),
            new HibernateColumnMismatchRule(),
            new HibernateColumnLengthMismatchRule(),
            new HibernateMissingUniqueIndexRule(),
            new HibernateMissingColumnRule(),
            new HibernateMissingForeignKeyConstraintRule(),
            // Runtime SQL observed through the SQL Trace window
            new SqlLiteralConcatenationRule());

    private DatabaseAdvisorRuleRegistry() {}

    static List<DatabaseAdvisorRule> activeRules() {
        return ACTIVE_RULES;
    }
}
