package io.github.jdubois.bootui.engine.databaseadvisor;

import io.github.jdubois.bootui.core.dto.DatabaseAdvisorRuleResultDto;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * A single-column, auto-generated (identity/{@code AUTO_INCREMENT}/serial) primary key typed narrower than a
 * plain 32-bit integer — {@code TINYINT} or {@code SMALLINT}/{@code INT2} — merits a bounded-domain review.
 *
 * <p>This is a structural, design-time risk check, not a usage-based one: it fires the moment the schema is
 * created, before the {@code TINYINT}/{@code SMALLINT} counter has consumed any meaningful fraction of its
 * own tiny range, which is exactly when the type is cheapest to widen. {@code DB-PG-002}/{@code DB-MYSQL-003}
 * (and {@code DB-ORACLE-003}) separately catch a sequence/{@code AUTO_INCREMENT} counter that is already
 * close to its column's actual maximum, at any width.</p>
 *
 * <p>Deliberately narrow in scope: only a single-column primary key that the database itself auto-generates
 * is checked — a manually-assigned {@code TINYINT} key on a small, bounded reference/lookup table (a set of
 * five status codes that will never grow) is a legitimate, common design and not a defect, and a composite
 * primary key's individual column widths are a different, less clear-cut question this rule does not guess
 * at. {@code LOW} because it is a review prompt about future
 * risk, not evidence of an active problem today.</p>
 */
final class NarrowAutoGeneratedPrimaryKeyRule extends AbstractDatabaseAdvisorRule {

    private static final Set<String> TINYINT_NAMES = Set.of("tinyint");
    private static final Set<String> SMALLINT_NAMES = Set.of("smallint", "int2", "smallserial");

    NarrowAutoGeneratedPrimaryKeyRule() {
        super(new DatabaseAdvisorRuleDefinition(
                "DB-SCHEMA-007",
                "Narrow auto-generated primary key",
                DatabaseAdvisorCategory.SCHEMA,
                DatabaseAdvisorRuleSupport.LOW,
                "Detects a single-column, auto-generated (IS_AUTOINCREMENT/identity/serial) primary key typed "
                        + "TINYINT or SMALLINT/INT2, regardless of how many rows the table currently has.",
                "Review whether the representable domain fits the intended bounded population. A deliberately "
                        + "small generated domain is valid. These type bounds do not predict generator headroom, "
                        + "time to exhaustion, or the number of rows ever inserted.",
                "https://www.postgresql.org/docs/current/datatype-numeric.html"));
    }

    @Override
    DatabaseAdvisorRuleResultDto evaluateRule(DatabaseAdvisorContext context) {
        List<String> details = new ArrayList<>();
        int eligible = 0;
        for (SchemaSnapshot schema : context.availableSchemas()) {
            for (TableModel table : DatabaseAdvisorContext.analyzableTables(schema)) {
                if (!table.metadata().primaryKeyRead() || !table.metadata().columnsRead()) {
                    unknown(context, table.qualifiedName() + ": primary-key or column metadata is incomplete.");
                }
                if (!table.metadata().primaryKeyRead()) {
                    continue;
                }
                if (table.primaryKeyColumns().size() == 1) {
                    ColumnModel column = table.column(table.primaryKeyColumns().get(0));
                    if (column != null && column.autoIncrement()) {
                        eligible++;
                    }
                }
                checkTable(schema, table, details);
            }
        }
        return assessed(context, eligible, details);
    }

    private void checkTable(SchemaSnapshot schema, TableModel table, List<String> details) {
        List<String> primaryKeyColumns = table.primaryKeyColumns();
        if (primaryKeyColumns.size() != 1) {
            return;
        }
        ColumnModel column = table.column(primaryKeyColumns.get(0));
        if (column == null || !column.autoIncrement()) {
            return;
        }
        BigInteger capacity = capacity(column);
        if (capacity == null) {
            return;
        }
        details.add(schema.dataSourceName() + ": " + table.qualifiedName() + "." + column.name() + " ("
                + column.describeType() + ") is an auto-generated primary key with representable type bounds "
                + (column.unsigned() ? BigInteger.ZERO : capacity.negate().subtract(BigInteger.ONE))
                + " through " + capacity + ". This is a bounded-domain review, not observed exhaustion.");
    }

    /** The maximum values a narrow (TINYINT/SMALLINT-class) column can hold, or {@code null} otherwise. */
    private BigInteger capacity(ColumnModel column) {
        String normalized = normalizeTypeName(column.typeName());
        if (normalized.isEmpty()) {
            return null;
        }
        boolean unsigned = column.unsigned();
        if (TINYINT_NAMES.contains(normalized)) {
            return unsigned ? BigInteger.valueOf(255) : BigInteger.valueOf(127);
        }
        if (SMALLINT_NAMES.contains(normalized)) {
            return unsigned ? BigInteger.valueOf(65_535) : BigInteger.valueOf(32_767);
        }
        return null;
    }

    private String normalizeTypeName(String typeName) {
        if (typeName == null) {
            return "";
        }
        String normalized = typeName.toLowerCase(Locale.ROOT).trim();
        int parenthesis = normalized.indexOf('(');
        if (parenthesis >= 0) {
            normalized = normalized.substring(0, parenthesis).trim();
        }
        return normalized.replace(" unsigned", "").replace(" zerofill", "").trim();
    }
}
