// @ts-check
import {acceptConfirm, expect, test} from './fixtures.js'

test.describe('REST Client view', () => {
  test('records outbound REST calls generated by the sample app', async ({openView, page}) => {
    await openView('rest-client-trace', 'REST Client')

    // Start from an empty buffer so the assertions below are deterministic.
    const clearButton = page.getByRole('button', {name: 'Clear'})
    if (await clearButton.isEnabled()) {
      await clearButton.click()
      await acceptConfirm(page)
      await expect(page.locator('.alert-success')).toBeVisible()
    }

    // Trigger a real outbound RestClient call: the sample app's cross-service endpoint calls the
    // companion Quarkus sample app, which is not running in this suite, so the call fails fast with a
    // connection error - a deterministic way to generate a captured "failed" entry without depending on
    // another process being up. The sample endpoint itself surfaces that failure as a 500, which is
    // expected here; what matters is that BootUI's interceptor recorded the attempt regardless.
    const response = await page.request.get('/api/sample/quarkus-secure-products')
    expect(response.status()).toBe(500)

    await page.getByTitle('Refresh', {exact: true}).click()

    const recentCalls = page.locator('section').filter({hasText: 'Recent calls'})
    const failedRow = recentCalls.locator('tbody tr.rest-row', {hasText: 'failed'}).first()
    await expect(failedRow).toBeVisible()
    await expect(failedRow).toContainText('RestClient')

    // Expanding the row reveals the call site, thread, and error message.
    await failedRow.click()
    await expect(recentCalls).toContainText('Client')
    await expect(recentCalls).toContainText('Thread')
    await expect(recentCalls).toContainText('Error')
  })

  test('can pause and resume recording', async ({openView, page}) => {
    await openView('rest-client-trace', 'REST Client')

    await page.getByRole('button', {name: 'Pause'}).click()
    await expect(page.locator('.alert-success')).toContainText(/paused/i)
    await expect(page.getByRole('button', {name: 'Resume'})).toBeVisible()

    // Restore recording so the rest of the suite keeps capturing calls.
    await page.getByRole('button', {name: 'Resume'}).click()
    await expect(page.getByRole('button', {name: 'Pause'})).toBeVisible()
  })
})
