package io.github.jdubois.bootui.autoconfigure.crac;

import io.github.jdubois.bootui.autoconfigure.sourcetree.DockerPackageManager;
import io.github.jdubois.bootui.autoconfigure.sourcetree.ProjectBuildSystem;

/**
 * Generates the container assets for a CRaC (Coordinated Restore at Checkpoint) image of the host
 * application the BootUI starter is installed in: a multi-stage {@code Dockerfile-crac} and the
 * {@code checkpoint-and-run.sh} entrypoint it relies on.
 *
 * <p>Unlike the multi-module {@code Dockerfile-crac} at the root of the BootUI project (which builds
 * the sample app together with its reactor modules), this scaffold targets a single-module Spring Boot
 * application. It detects the project's build system from the files in the project root — Maven or
 * Gradle, with or without the wrapper, via the shared {@link ProjectBuildSystem} — and emits the
 * matching build command that produces a runnable Spring Boot jar
 * ({@code ./mvnw}/{@code mvn -DskipTests clean package} or {@code ./gradlew}/{@code gradle bootJar}),
 * copying the resulting jar from the build tool's conventional output directory ({@code target} for
 * Maven, {@code build/libs} for Gradle).</p>
 *
 * <p>The build stage uses a plain JDK (CRaC only matters at runtime) and the runtime stage uses a
 * CRaC-enabled BellSoft Liberica JDK. The build image is Debian-based, so a missing build tool is
 * installed with {@code apt-get} ({@link DockerPackageManager#APT}). The companion
 * {@code checkpoint-and-run.sh} takes a checkpoint on the first start (via
 * {@code spring.context.checkpoint=onRefresh}) and restores it afterwards.</p>
 *
 * <p>Both generated files carry a {@code generated by BootUI} marker so the source-tree writer can
 * tell a previously generated file apart from a hand-written one and refuse to clobber the latter.</p>
 */
final class CracDockerfileGenerator {

    private static final String DEFAULT_ARTIFACT = "app";

    /** The CRaC-specific Dockerfile pieces that depend on the detected build system. */
    private record Variant(String description, String command, String outputDir) {}

    private static Variant variant(ProjectBuildSystem buildSystem) {
        return switch (buildSystem) {
            case MAVEN_WRAPPER -> new Variant("the Maven Wrapper", "./mvnw -DskipTests clean package", "target");
            case MAVEN -> new Variant("Maven", "mvn -DskipTests clean package", "target");
            case GRADLE_WRAPPER -> new Variant("the Gradle Wrapper", "./gradlew bootJar", "build/libs");
            case GRADLE -> new Variant("Gradle", "gradle bootJar", "build/libs");
        };
    }

    String generateDockerfile(String artifactName) {
        return generateDockerfile(artifactName, ProjectBuildSystem.MAVEN_WRAPPER);
    }

    String generateDockerfile(String artifactName, ProjectBuildSystem buildSystem) {
        String artifact = artifactName == null || artifactName.isBlank() ? DEFAULT_ARTIFACT : artifactName.trim();
        ProjectBuildSystem tool = buildSystem == null ? ProjectBuildSystem.MAVEN_WRAPPER : buildSystem;
        Variant variant = variant(tool);
        String setup = tool.dockerSetup(DockerPackageManager.APT);
        return """
                # Multi-stage Dockerfile for a CRaC (Coordinated Restore at Checkpoint) image of %1$s.
                #
                # This scaffold was generated by BootUI for the application the starter is installed in.
                # It assumes a single-module Spring Boot application built with %2$s.
                #
                # This JDK 21 scaffold attempts a startup checkpoint after non-lazy singleton
                # initialization, before lifecycle start; it is not a fully warmed-up application.
                # Early-opened resources may still need checkpoint handling. This CRIU-based
                # recipe uses Linux and CHECKPOINT_RESTORE, SYS_PTRACE, SYS_ADMIN (with Docker's
                # default /proc restrictions) and NET_ADMIN (to recreate network interfaces).
                # Verify the exact JDK, CRIU, kernel and CPU combination separately. The companion
                # checkpoint-and-run.sh entrypoint (generated alongside this file and expected at the
                # project root) takes the checkpoint on the first start and restores it afterwards.
                #
                # Build and run (the named volume keeps the checkpoint
                # between restarts, and -p publishes the port so the app is reachable from the host):
                #   docker build -f Dockerfile-crac -t %1$s .
                #   docker run --rm -p 127.0.0.1:8080:8080 \\
                #     --cap-add=CHECKPOINT_RESTORE --cap-add=SYS_PTRACE --cap-add=SYS_ADMIN --cap-add=NET_ADMIN \\
                #     -v %1$s-crac:/opt/crac/checkpoint %1$s
                # These capabilities grant broad host access. Use this image only for local
                # development on an isolated machine; do not deploy it to production or a shared host.

                # Build stage (a plain JDK is enough; CRaC only matters at runtime).
                FROM eclipse-temurin:21-jdk-noble AS build

                WORKDIR /app

                # Copy the project (see .dockerignore for exclusions).
                COPY . .

                %3$s

                # Build the repackaged, runnable Spring Boot jar.
                RUN %4$s

                # Move the runnable jar to a known path (the repackaged boot jar, not a *-plain.jar or
                # *.jar.original produced alongside it).
                RUN set -e; \\
                    app_jar=$(find %5$s -maxdepth 1 -type f -name '*.jar' ! -name '*-plain.jar' ! -name '*.jar.original' | head -1); \\
                    if [ -z "$app_jar" ]; then echo "ERROR: Spring Boot jar not found"; ls -laR %5$s | head -40; exit 1; fi; \\
                    cp "$app_jar" /app/app.jar

                # Runtime stage with a CRaC-enabled JDK (BellSoft Liberica with CRaC support).
                FROM bellsoft/liberica-runtime-container:jdk-21-crac-slim-glibc

                WORKDIR /app

                # Where the checkpoint image is written/read. Mount it as a volume so the checkpoint
                # survives container restarts.
                ENV CRAC_CHECKPOINT_DIR=/opt/crac/checkpoint
                ENV APP_JAR=/app/app.jar
                # Spring Boot's Hikari checkpoint lifecycle suspends new borrows before draining the pool.
                # This setting alone does not prove pool ownership or cleanup of early-opened resources.
                ENV SPRING_DATASOURCE_HIKARI_ALLOWPOOLSUSPENSION=true

                # Copy the repackaged jar and the checkpoint/restore entrypoint generated alongside this file.
                COPY --from=build /app/app.jar ${APP_JAR}
                COPY --from=build /app/checkpoint-and-run.sh /app/checkpoint-and-run.sh

                RUN chmod +x /app/checkpoint-and-run.sh && mkdir -p ${CRAC_CHECKPOINT_DIR}

                EXPOSE 8080

                # Take a checkpoint on the first start, then restore on every start.
                ENTRYPOINT ["/app/checkpoint-and-run.sh"]
                """.formatted(artifact, variant.description(), setup, variant.command(), variant.outputDir());
    }

    /**
     * Generates the {@code checkpoint-and-run.sh} entrypoint. On the first start it takes a CRaC
     * startup checkpoint; a candidate marker permits a restore attempt, not a validity guarantee.
     */
    String generateEntrypoint() {
        return """
                #!/bin/sh
                # CRaC (Coordinated Restore at Checkpoint) entrypoint generated by BootUI.
                #
                # On the first start no checkpoint exists yet, so the app is launched with
                # `spring.context.checkpoint=onRefresh`: after non-lazy singleton initialization,
                # before lifecycle start and the context-refreshed event. This is not a fully
                # warmed-up application, nor guaranteed cleanup of resources opened during
                # initialization. Hikari's allow-pool-suspension setting alone is not proof of cleanup.
                #
                # Taking and restoring a checkpoint needs Linux and elevated container
                # privileges (CRIU); see the generated Dockerfile-crac.
                set -eu

                CRAC_CHECKPOINT_DIR="${CRAC_CHECKPOINT_DIR-/opt/crac/checkpoint}"
                APP_JAR="${APP_JAR:-/app/app.jar}"
                # JVM flags are applied only while creating the checkpoint. They become part of the
                # saved JVM in this scaffold, which does not forward JAVA_OPTS during restore.
                # Regenerate the checkpoint whenever this recipe's JAVA_OPTS changes.
                JAVA_OPTS="${JAVA_OPTS:-}"

                invalid_checkpoint_path() {
                  echo "[crac] Invalid CRAC_CHECKPOINT_DIR: use an absolute path with letters, digits, '.', '_' or '-', no dot-only components, repeated/trailing separators or symlinks." >&2
                  exit 1
                }
                # Validate before creating or inspecting checkpoint contents. Reject ambiguous paths
                # rather than normalizing them into a different destination.
                case "$CRAC_CHECKPOINT_DIR" in
                  ""|/|*[!a-zA-Z0-9_./-]*|*/|*//*) invalid_checkpoint_path ;;
                  /*) ;;
                  *) invalid_checkpoint_path ;;
                esac
                remaining_path="${CRAC_CHECKPOINT_DIR#/}"
                checked_path=""
                while [ -n "$remaining_path" ]; do
                  component="${remaining_path%%/*}"
                  case "$component" in
                    *[!.]*) ;;
                    *) invalid_checkpoint_path ;;
                  esac
                  checked_path="$checked_path/$component"
                  [ ! -L "$checked_path" ] || invalid_checkpoint_path
                  case "$remaining_path" in
                    */*) remaining_path="${remaining_path#*/}" ;;
                    *) remaining_path="" ;;
                  esac
                done
                mkdir -p "$CRAC_CHECKPOINT_DIR"
                if [ ! -r "$CRAC_CHECKPOINT_DIR" ] || [ ! -x "$CRAC_CHECKPOINT_DIR" ]; then
                  echo "[crac] Checkpoint directory must be readable and searchable; leaving it unchanged." >&2
                  exit 1
                fi

                # inventory.img is only a candidate marker, not an integrity or compatibility
                # certificate. A dump can still fail after writing it; a restore attempt can fail.
                checkpoint_candidate_exists() {
                  [ -f "$CRAC_CHECKPOINT_DIR/inventory.img" ]
                }

                # CRIU writes the reason a dump failed to its own log file (dump*.log), not to
                # stdout, so surface it: without this the container log only shows the JVM's
                # generic "Native checkpoint failed".
                print_criu_dump_log() {
                  for criu_log in "$CRAC_CHECKPOINT_DIR"/dump*.log; do
                    [ -f "$criu_log" ] || continue
                    echo "[crac] ----- CRIU $criu_log (last 50 lines) -----" >&2
                    tail -n 50 "$criu_log" >&2
                  done
                }

                # Do not hide restore failures or fall back to creating another checkpoint.
                if checkpoint_candidate_exists; then
                  echo "[crac] Attempting restore from checkpoint candidate in $CRAC_CHECKPOINT_DIR"
                  exec java -XX:CRaCRestoreFrom="$CRAC_CHECKPOINT_DIR"
                fi

                # Preserve partial images, logs and user files, including hidden files and symlinks.
                for entry in "$CRAC_CHECKPOINT_DIR"/* "$CRAC_CHECKPOINT_DIR"/.[!.]* "$CRAC_CHECKPOINT_DIR"/..?*; do
                  if [ -e "$entry" ] || [ -L "$entry" ]; then
                    echo "[crac] Incomplete checkpoint directory (no inventory.img): $CRAC_CHECKPOINT_DIR; leaving all contents unchanged. Inspect it and select a new empty directory." >&2
                    exit 1
                  fi
                done

                echo "[crac] No checkpoint found; starting the app to create one (spring.context.checkpoint=onRefresh)"
                # CRIU kills the process once the checkpoint is written, so a non-zero exit code
                # here can occur even with a usable image. A marker permits only an attempted
                # restore; neither its presence nor the exit code certifies a successful dump.
                set +e
                java $JAVA_OPTS -XX:CRaCCheckpointTo="$CRAC_CHECKPOINT_DIR" \\
                  -Dspring.context.checkpoint=onRefresh \\
                  -jar "$APP_JAR"
                checkpoint_status=$?
                set -e

                if ! checkpoint_candidate_exists; then
                  echo "[crac] Checkpoint creation failed (exit code $checkpoint_status): no inventory.img candidate marker; preserving all files." >&2
                  print_criu_dump_log
                  echo "[crac] Verify this CRIU recipe's Linux/JDK/CRIU compatibility and CHECKPOINT_RESTORE/SYS_PTRACE/SYS_ADMIN/NET_ADMIN capabilities; these grant broad privileges." >&2
                  # Never fall through to a restore: the image is incomplete and restoring it would
                  # fail with a far more confusing error than the CRIU log printed above.
                  [ "$checkpoint_status" -ne 0 ] || checkpoint_status=1
                  exit "$checkpoint_status"
                fi

                echo "[crac] Checkpoint candidate found in $CRAC_CHECKPOINT_DIR (creation exit code $checkpoint_status); attempting restore"
                exec java -XX:CRaCRestoreFrom="$CRAC_CHECKPOINT_DIR"
                """;
    }
}
