package io.github.jdubois.bootui.autoconfigure.graalvm;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;

class GraalVmDockerfileGeneratorTests {

    private final GraalVmDockerfileGenerator generator = new GraalVmDockerfileGenerator();

    @Test
    void generatesNativeImageDockerfileTailoredToArtifact() {
        String dockerfile = generator.generate("my-service");

        assertThat(dockerfile).contains("FROM ghcr.io/graalvm/graalvm-community:25 AS build");
        assertThat(dockerfile).contains("./mvnw -Pnative -DskipTests clean package");
        assertThat(dockerfile).contains("target/my-service");
        assertThat(dockerfile).contains("ENTRYPOINT [\"./native-app\"]");
        assertThat(dockerfile).contains("generated by BootUI");
    }

    @Test
    void fallsBackToAppWhenArtifactIsMissing() {
        assertThat(generator.generate(null)).contains("target/app");
        assertThat(generator.generate("  ")).contains("target/app");
    }
}
