package io.github.jdubois.bootui.autoconfigure.graalvm;

import static org.assertj.core.api.Assertions.assertThat;

import io.github.jdubois.bootui.autoconfigure.graalvm.GraalVmDockerfileGenerator.BuildTool;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class GraalVmDockerfileGeneratorTests {

    private final GraalVmDockerfileGenerator generator = new GraalVmDockerfileGenerator();

    @Test
    void generatesNativeImageDockerfileTailoredToArtifact() {
        String dockerfile = generator.generate("my-service");

        assertThat(dockerfile).contains("FROM ghcr.io/graalvm/graalvm-community:25 AS build");
        assertThat(dockerfile).contains("./mvnw -Pnative -DskipTests clean native:compile");
        assertThat(dockerfile).contains("target/my-service");
        assertThat(dockerfile).contains("ENTRYPOINT [\"./native-app\"]");
        assertThat(dockerfile).contains("generated by BootUI");
    }

    @Test
    void documentsHowToBuildAndRunWithPublishedPort() {
        String dockerfile = generator.generate("my-service");

        // The header reminds the reader to publish the port (a common gotcha: EXPOSE alone does not).
        assertThat(dockerfile).contains("docker build -f Dockerfile-native -t my-service .");
        assertThat(dockerfile).contains("docker run --rm -p 8080:8080 my-service");
    }

    @Test
    void healthcheckDoesNotDependOnActuator() {
        String dockerfile = generator.generate("my-service");

        // A liveness probe that succeeds on any HTTP response, so it stays green without Actuator.
        assertThat(dockerfile).contains("curl -s -o /dev/null http://localhost:${SERVER_PORT:-8080}/ || exit 1");
        assertThat(dockerfile).doesNotContain("/actuator/health");
    }

    @Test
    void fallsBackToAppWhenArtifactIsMissing() {
        assertThat(generator.generate(null)).contains("target/app");
        assertThat(generator.generate("  ")).contains("target/app");
    }

    @Test
    void generatesPlainMavenVariant() {
        String dockerfile = generator.generate("my-service", BuildTool.MAVEN);

        assertThat(dockerfile).contains("mvn -Pnative -DskipTests clean native:compile");
        assertThat(dockerfile).doesNotContain("./mvnw");
        assertThat(dockerfile).contains("apache-maven");
        assertThat(dockerfile).contains("target/my-service");
        // Installs a known, pinned Maven release exposed as a clear constant.
        assertThat(dockerfile).contains("ARG MAVEN_VERSION=3.9.16");
    }

    @Test
    void generatesGradleWrapperVariant() {
        String dockerfile = generator.generate("my-service", BuildTool.GRADLE_WRAPPER);

        assertThat(dockerfile).contains("chmod +x gradlew");
        assertThat(dockerfile).contains("./gradlew nativeCompile");
        assertThat(dockerfile).contains("build/native/nativeCompile/my-service");
        assertThat(dockerfile).doesNotContain("-Pnative");
    }

    @Test
    void generatesPlainGradleVariant() {
        String dockerfile = generator.generate("my-service", BuildTool.GRADLE);

        assertThat(dockerfile).contains("gradle nativeCompile");
        assertThat(dockerfile).doesNotContain("./gradlew");
        assertThat(dockerfile).contains("services.gradle.org");
        assertThat(dockerfile).contains("build/native/nativeCompile/my-service");
        // Installs a known, pinned Gradle release exposed as a clear constant.
        assertThat(dockerfile).contains("ARG GRADLE_VERSION=9.5.1");
    }

    @Test
    void detectsMavenWrapperWhenMvnwPresent(@TempDir Path projectRoot) throws IOException {
        Files.writeString(projectRoot.resolve("pom.xml"), "<project/>");
        Files.writeString(projectRoot.resolve("mvnw"), "#!/bin/sh");

        assertThat(GraalVmDockerfileGenerator.detect(projectRoot)).isEqualTo(BuildTool.MAVEN_WRAPPER);
    }

    @Test
    void detectsPlainMavenWhenOnlyPomPresent(@TempDir Path projectRoot) throws IOException {
        Files.writeString(projectRoot.resolve("pom.xml"), "<project/>");

        assertThat(GraalVmDockerfileGenerator.detect(projectRoot)).isEqualTo(BuildTool.MAVEN);
    }

    @Test
    void detectsGradleWrapperWhenGradlewPresent(@TempDir Path projectRoot) throws IOException {
        Files.writeString(projectRoot.resolve("build.gradle"), "plugins {}");
        Files.writeString(projectRoot.resolve("gradlew"), "#!/bin/sh");

        assertThat(GraalVmDockerfileGenerator.detect(projectRoot)).isEqualTo(BuildTool.GRADLE_WRAPPER);
    }

    @Test
    void detectsPlainGradleFromKotlinBuildScript(@TempDir Path projectRoot) throws IOException {
        Files.writeString(projectRoot.resolve("build.gradle.kts"), "plugins {}");

        assertThat(GraalVmDockerfileGenerator.detect(projectRoot)).isEqualTo(BuildTool.GRADLE);
    }

    @Test
    void prefersMavenWhenBothBuildSystemsPresent(@TempDir Path projectRoot) throws IOException {
        Files.writeString(projectRoot.resolve("pom.xml"), "<project/>");
        Files.writeString(projectRoot.resolve("mvnw"), "#!/bin/sh");
        Files.writeString(projectRoot.resolve("build.gradle"), "plugins {}");
        Files.writeString(projectRoot.resolve("gradlew"), "#!/bin/sh");

        assertThat(GraalVmDockerfileGenerator.detect(projectRoot)).isEqualTo(BuildTool.MAVEN_WRAPPER);
    }

    @Test
    void defaultsToMavenWrapperWhenNoBuildFilesOrNullRoot(@TempDir Path projectRoot) {
        assertThat(GraalVmDockerfileGenerator.detect(projectRoot)).isEqualTo(BuildTool.MAVEN_WRAPPER);
        assertThat(GraalVmDockerfileGenerator.detect(null)).isEqualTo(BuildTool.MAVEN_WRAPPER);
    }
}
