package io.github.jdubois.bootui.autoconfigure.graalvm;

import static org.assertj.core.api.Assertions.assertThat;

import io.github.jdubois.bootui.autoconfigure.graalvm.GraalVmSourceLayout.Coordinates;
import io.github.jdubois.bootui.autoconfigure.graalvm.GraalVmSourceLayout.InstallOutcome;
import io.github.jdubois.bootui.autoconfigure.graalvm.GraalVmSourceLayout.Resolution;
import java.io.IOException;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class GraalVmSourceLayoutTests {

    private static final Coordinates COORDS = new Coordinates("com.example", "demo");

    @Test
    void resolvesGraalVmRecommendedTargetUnderResources(@TempDir Path projectRoot) throws IOException {
        Path resources = Files.createDirectories(projectRoot.resolve("src/main/resources"));
        URL classes = explodedClasses(projectRoot);

        Resolution resolution = GraalVmSourceLayout.resolve(projectRoot, classes, Optional.of(COORDS));

        assertThat(resolution.installable()).isTrue();
        assertThat(resolution.targetFile())
                .isEqualTo(resources
                        .resolve("META-INF/native-image/com.example/demo/reachability-metadata.json")
                        .normalize());
        assertThat(resolution.displayPath())
                .isEqualTo("src/main/resources/META-INF/native-image/com.example/demo/reachability-metadata.json");
    }

    @Test
    void fallsBackToGeneratedNamespaceWithoutCoordinates(@TempDir Path projectRoot) throws IOException {
        Files.createDirectories(projectRoot.resolve("src/main/resources"));

        Resolution resolution =
                GraalVmSourceLayout.resolve(projectRoot, explodedClasses(projectRoot), Optional.empty());

        assertThat(resolution.installable()).isTrue();
        assertThat(resolution.displayPath()).contains("META-INF/native-image/bootui-generated/");
    }

    @Test
    void metadataDirectorySubstitutesResolvedCoordinates() {
        assertThat(GraalVmSourceLayout.metadataDirectory(Optional.of(COORDS)))
                .isEqualTo("src/main/resources/META-INF/native-image/com.example/demo/");
    }

    @Test
    void metadataDirectoryKeepsPlaceholdersWithoutCoordinates() {
        assertThat(GraalVmSourceLayout.metadataDirectory(Optional.empty()))
                .isEqualTo("src/main/resources/META-INF/native-image/<groupId>/<artifactId>/");
    }

    @Test
    void refusesWhenRunningFromJar(@TempDir Path projectRoot) throws IOException {
        Files.createDirectories(projectRoot.resolve("src/main/resources"));
        URL jar = new URL("file:/tmp/app.jar");

        Resolution resolution = GraalVmSourceLayout.resolve(projectRoot, jar, Optional.of(COORDS));

        assertThat(resolution.installable()).isFalse();
        assertThat(resolution.reason()).contains("packaged jar");
    }

    @Test
    void refusesWhenNoResourcesDirectory(@TempDir Path projectRoot) {
        Resolution resolution =
                GraalVmSourceLayout.resolve(projectRoot, explodedClassesUnchecked(projectRoot), Optional.of(COORDS));

        assertThat(resolution.installable()).isFalse();
        assertThat(resolution.reason()).contains("src/main/resources");
    }

    @Test
    void installWritesGeneratedScaffold(@TempDir Path projectRoot) throws IOException {
        Files.createDirectories(projectRoot.resolve("src/main/resources"));
        GraalVmSourceLayout layout = layout(projectRoot, Optional.of(COORDS));
        String json = "{\n  \"comment\": [\"generated by BootUI\"]\n}\n";

        InstallOutcome outcome = layout.install(json);

        assertThat(outcome.status()).isEqualTo("WRITTEN");
        Path written = projectRoot.resolve(
                "src/main/resources/META-INF/native-image/com.example/demo/reachability-metadata.json");
        assertThat(Files.readString(written, StandardCharsets.UTF_8)).isEqualTo(json);
    }

    @Test
    void installOverwritesPreviouslyGeneratedFile(@TempDir Path projectRoot) throws IOException {
        Path target = Files.createDirectories(
                        projectRoot.resolve("src/main/resources/META-INF/native-image/com.example/demo"))
                .resolve("reachability-metadata.json");
        Files.writeString(target, "{ \"comment\": [\"old, generated by BootUI\"] }", StandardCharsets.UTF_8);
        GraalVmSourceLayout layout = layout(projectRoot, Optional.of(COORDS));

        InstallOutcome outcome = layout.install("{\"new\": true}");

        assertThat(outcome.status()).isEqualTo("WRITTEN");
        assertThat(Files.readString(target, StandardCharsets.UTF_8)).isEqualTo("{\"new\": true}");
    }

    @Test
    void installRefusesToClobberHandWrittenFile(@TempDir Path projectRoot) throws IOException {
        Path target = Files.createDirectories(
                        projectRoot.resolve("src/main/resources/META-INF/native-image/com.example/demo"))
                .resolve("reachability-metadata.json");
        Files.writeString(target, "{ \"reflection\": [] }", StandardCharsets.UTF_8);
        GraalVmSourceLayout layout = layout(projectRoot, Optional.of(COORDS));

        InstallOutcome outcome = layout.install("{\"new\": true}");

        assertThat(outcome.status()).isEqualTo("EXISTS");
        assertThat(Files.readString(target, StandardCharsets.UTF_8)).isEqualTo("{ \"reflection\": [] }");
    }

    @Test
    void installReportsUnavailableForJar(@TempDir Path projectRoot) throws IOException {
        Files.createDirectories(projectRoot.resolve("src/main/resources"));
        GraalVmSourceLayout layout = new GraalVmSourceLayout(
                () -> projectRoot, () -> Optional.of(uncheckedUrl("file:/tmp/app.jar")), () -> Optional.of(COORDS));

        InstallOutcome outcome = layout.install("{}");

        assertThat(outcome.status()).isEqualTo("UNAVAILABLE");
    }

    @Test
    void resolveDockerfileTargetsProjectRoot(@TempDir Path projectRoot) throws IOException {
        Resolution resolution = GraalVmSourceLayout.resolveDockerfile(projectRoot, explodedClasses(projectRoot));

        assertThat(resolution.installable()).isTrue();
        assertThat(resolution.targetFile())
                .isEqualTo(projectRoot.resolve("Dockerfile-native").normalize());
        assertThat(resolution.displayPath()).isEqualTo("Dockerfile-native");
    }

    @Test
    void resolveDockerfileRefusesWhenRunningFromJar(@TempDir Path projectRoot) throws IOException {
        Resolution resolution = GraalVmSourceLayout.resolveDockerfile(projectRoot, new URL("file:/tmp/app.jar"));

        assertThat(resolution.installable()).isFalse();
        assertThat(resolution.reason()).contains("packaged jar");
    }

    @Test
    void installDockerfileWritesToProjectRoot(@TempDir Path projectRoot) throws IOException {
        GraalVmSourceLayout layout = layout(projectRoot, Optional.of(COORDS));
        String content = "# generated by BootUI\nFROM ghcr.io/graalvm/graalvm-community:25\n";

        InstallOutcome outcome = layout.installDockerfile(content);

        assertThat(outcome.status()).isEqualTo("WRITTEN");
        assertThat(Files.readString(projectRoot.resolve("Dockerfile-native"), StandardCharsets.UTF_8))
                .isEqualTo(content);
    }

    @Test
    void installDockerfileRefusesToClobberHandWrittenFile(@TempDir Path projectRoot) throws IOException {
        Path target = projectRoot.resolve("Dockerfile-native");
        Files.writeString(target, "FROM eclipse-temurin:25\n", StandardCharsets.UTF_8);
        GraalVmSourceLayout layout = layout(projectRoot, Optional.of(COORDS));

        InstallOutcome outcome = layout.installDockerfile("# generated by BootUI\n");

        assertThat(outcome.status()).isEqualTo("EXISTS");
        assertThat(Files.readString(target, StandardCharsets.UTF_8)).isEqualTo("FROM eclipse-temurin:25\n");
    }

    @Test
    void installDockerfileOverwritesPreviouslyGeneratedFile(@TempDir Path projectRoot) throws IOException {
        Path target = projectRoot.resolve("Dockerfile-native");
        Files.writeString(target, "# old, generated by BootUI\n", StandardCharsets.UTF_8);
        GraalVmSourceLayout layout = layout(projectRoot, Optional.of(COORDS));

        InstallOutcome outcome = layout.installDockerfile("# generated by BootUI\nFROM scratch\n");

        assertThat(outcome.status()).isEqualTo("WRITTEN");
        assertThat(Files.readString(target, StandardCharsets.UTF_8)).isEqualTo("# generated by BootUI\nFROM scratch\n");
    }

    @Test
    void installDockerfileReportsUnavailableForJar(@TempDir Path projectRoot) {
        GraalVmSourceLayout layout = new GraalVmSourceLayout(
                () -> projectRoot, () -> Optional.of(uncheckedUrl("file:/tmp/app.jar")), () -> Optional.of(COORDS));

        InstallOutcome outcome = layout.installDockerfile("# generated by BootUI\n");

        assertThat(outcome.status()).isEqualTo("UNAVAILABLE");
    }

    @Test
    void artifactNameUsesResolvedArtifactId(@TempDir Path projectRoot) {
        GraalVmSourceLayout layout = layout(projectRoot, Optional.of(COORDS));

        assertThat(layout.artifactName()).isEqualTo("demo");
    }

    @Test
    void artifactNameDefaultsToAppWithoutCoordinates(@TempDir Path projectRoot) {
        GraalVmSourceLayout layout = layout(projectRoot, Optional.empty());

        assertThat(layout.artifactName()).isEqualTo("app");
    }

    @Test
    void coordinatesFromPomReadsModuleThenParent(@TempDir Path projectRoot) throws IOException {
        Files.writeString(projectRoot.resolve("pom.xml"), """
                <project>
                  <parent>
                    <groupId>com.parent</groupId>
                    <artifactId>parent</artifactId>
                  </parent>
                  <artifactId>demo</artifactId>
                  <dependencies>
                    <dependency>
                      <groupId>org.other</groupId>
                      <artifactId>lib</artifactId>
                    </dependency>
                  </dependencies>
                </project>
                """, StandardCharsets.UTF_8);

        Optional<Coordinates> coordinates = GraalVmSourceLayout.coordinatesFromPom(projectRoot);

        assertThat(coordinates).isPresent();
        assertThat(coordinates.get().groupId()).isEqualTo("com.parent");
        assertThat(coordinates.get().artifactId()).isEqualTo("demo");
    }

    @Test
    void isExplodedClassesRejectsJar() throws IOException {
        assertThat(GraalVmSourceLayout.isExplodedClasses(new URL("file:/tmp/app.jar")))
                .isFalse();
        assertThat(GraalVmSourceLayout.isExplodedClasses(null)).isFalse();
    }

    private GraalVmSourceLayout layout(Path projectRoot, Optional<Coordinates> coordinates) {
        return new GraalVmSourceLayout(
                () -> projectRoot, () -> Optional.of(explodedClassesUnchecked(projectRoot)), () -> coordinates);
    }

    private static URL explodedClasses(Path projectRoot) throws IOException {
        Path classes = Files.createDirectories(projectRoot.resolve("target/classes"));
        return classes.toUri().toURL();
    }

    private static URL explodedClassesUnchecked(Path projectRoot) {
        try {
            return explodedClasses(projectRoot);
        } catch (IOException ex) {
            throw new IllegalStateException(ex);
        }
    }

    private static URL uncheckedUrl(String spec) {
        try {
            return new URL(spec);
        } catch (IOException ex) {
            throw new IllegalStateException(ex);
        }
    }
}
