package io.github.jdubois.bootui.autoconfigure.graalvm;

import static org.assertj.core.api.Assertions.assertThat;

import io.github.jdubois.bootui.autoconfigure.sourcetree.ProjectBuildSystem;
import org.junit.jupiter.api.Test;

class GraalVmDockerfileGeneratorTests {

    private final GraalVmDockerfileGenerator generator = new GraalVmDockerfileGenerator();

    @Test
    void generatesNativeImageDockerfileTailoredToArtifact() {
        String dockerfile = generator.generate("my-service");

        assertThat(dockerfile).contains("FROM ghcr.io/graalvm/graalvm-community:25 AS build");
        assertThat(dockerfile).contains("./mvnw -Pnative -DskipTests clean native:compile");
        assertThat(dockerfile).contains("target/my-service");
        assertThat(dockerfile).contains("ENTRYPOINT [\"./native-app\"]");
        assertThat(dockerfile).contains("generated by BootUI");
    }

    @Test
    void documentsHowToBuildAndRunWithPublishedPort() {
        String dockerfile = generator.generate("my-service");

        // The header reminds the reader to publish the port (a common gotcha: EXPOSE alone does not).
        assertThat(dockerfile).contains("docker build -f Dockerfile-native -t my-service .");
        assertThat(dockerfile).contains("docker run --rm -p 8080:8080 my-service");
    }

    @Test
    void healthcheckDoesNotDependOnActuator() {
        String dockerfile = generator.generate("my-service");

        // A liveness probe that succeeds on any HTTP response, so it stays green without Actuator.
        assertThat(dockerfile).contains("curl -s -o /dev/null http://localhost:${SERVER_PORT:-8080}/ || exit 1");
        assertThat(dockerfile).doesNotContain("/actuator/health");
    }

    @Test
    void fallsBackToAppWhenArtifactIsMissing() {
        assertThat(generator.generate(null)).contains("target/app");
        assertThat(generator.generate("  ")).contains("target/app");
    }

    @Test
    void generatesPlainMavenVariant() {
        String dockerfile = generator.generate("my-service", ProjectBuildSystem.MAVEN);

        assertThat(dockerfile).contains("mvn -Pnative -DskipTests clean native:compile");
        assertThat(dockerfile).doesNotContain("./mvnw");
        assertThat(dockerfile).contains("apache-maven");
        assertThat(dockerfile).contains("target/my-service");
        // The GraalVM image is UBI-based, so a missing build tool is installed with microdnf.
        assertThat(dockerfile).contains("microdnf install -y curl tar gzip");
        // Installs a known, pinned Maven release exposed as a clear constant.
        assertThat(dockerfile).contains("ARG MAVEN_VERSION=3.9.16");
    }

    @Test
    void generatesGradleWrapperVariant() {
        String dockerfile = generator.generate("my-service", ProjectBuildSystem.GRADLE_WRAPPER);

        assertThat(dockerfile).contains("chmod +x gradlew");
        assertThat(dockerfile).contains("./gradlew nativeCompile");
        assertThat(dockerfile).contains("build/native/nativeCompile/my-service");
        assertThat(dockerfile).doesNotContain("-Pnative");
    }

    @Test
    void generatesPlainGradleVariant() {
        String dockerfile = generator.generate("my-service", ProjectBuildSystem.GRADLE);

        assertThat(dockerfile).contains("gradle nativeCompile");
        assertThat(dockerfile).doesNotContain("./gradlew");
        assertThat(dockerfile).contains("services.gradle.org");
        assertThat(dockerfile).contains("microdnf install -y curl unzip");
        assertThat(dockerfile).contains("build/native/nativeCompile/my-service");
        // Installs a known, pinned Gradle release exposed as a clear constant.
        assertThat(dockerfile).contains("ARG GRADLE_VERSION=9.5.1");
    }
}
