CREATE TABLE sample_orders (id BIGINT PRIMARY KEY, label VARCHAR(64), INDEX ix_label(label)) ENGINE=InnoDB;
CREATE TABLE sample_audit (id BIGINT PRIMARY KEY, order_id BIGINT) ENGINE=InnoDB;
INSERT INTO sample_orders VALUES (1, 'synthetic-alpha'), (2, 'synthetic-beta');
INSERT INTO sample_audit VALUES (1, 1);
CREATE USER 'reader'@'%' IDENTIFIED BY 'synthetic-fixture-only';
CREATE USER 'metadata_reader'@'%' IDENTIFIED BY 'synthetic-fixture-only';
GRANT SELECT ON bootui_fixture.* TO 'reader'@'%';
GRANT SELECT ON bootui_fixture.* TO 'metadata_reader'@'%';
GRANT SELECT ON performance_schema.global_status TO 'reader'@'%';
GRANT SELECT ON performance_schema.setup_consumers TO 'reader'@'%';
GRANT SELECT ON performance_schema.setup_objects TO 'reader'@'%';
GRANT SELECT ON performance_schema.setup_instruments TO 'reader'@'%';
GRANT SELECT ON performance_schema.threads TO 'reader'@'%';
GRANT SELECT ON performance_schema.data_lock_waits TO 'reader'@'%';
GRANT SELECT ON performance_schema.data_locks TO 'reader'@'%';
GRANT SELECT ON performance_schema.metadata_locks TO 'reader'@'%';
GRANT SELECT ON performance_schema.events_statements_summary_by_digest TO 'reader'@'%';
GRANT SELECT ON performance_schema.table_io_waits_summary_by_table TO 'reader'@'%';
GRANT SELECT ON performance_schema.table_io_waits_summary_by_index_usage TO 'reader'@'%';
GRANT SELECT ON performance_schema.replication_connection_status TO 'reader'@'%';
GRANT SELECT ON performance_schema.replication_applier_status TO 'reader'@'%';
GRANT SELECT ON performance_schema.replication_applier_status_by_worker TO 'reader'@'%';
GRANT SELECT ON performance_schema.replication_applier_status_by_coordinator TO 'reader'@'%';
