package io.github.jdubois.bootui.autoconfigure.crac;

import static org.assertj.core.api.Assertions.assertThat;

import io.github.jdubois.bootui.autoconfigure.sourcetree.ProjectBuildSystem;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledOnOs;
import org.junit.jupiter.api.condition.OS;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.junit.jupiter.params.provider.ValueSource;

class CracDockerfileGeneratorTests {

    private final CracDockerfileGenerator generator = new CracDockerfileGenerator();

    @TempDir
    Path temporaryDirectory;

    @Test
    void generatesCracDockerfileTailoredToArtifact() {
        String dockerfile = generator.generateDockerfile("my-service");

        assertThat(dockerfile).contains("FROM eclipse-temurin:21-jdk-noble AS build");
        assertThat(dockerfile).contains("FROM bellsoft/liberica-runtime-container:jdk-21-crac-slim-glibc");
        assertThat(dockerfile).contains("./mvnw -DskipTests clean package");
        assertThat(dockerfile).contains("docker build -f Dockerfile-crac -t my-service .");
        assertThat(dockerfile)
                .contains("--cap-add=CHECKPOINT_RESTORE --cap-add=SYS_PTRACE --cap-add=SYS_ADMIN --cap-add=NET_ADMIN");
        assertThat(dockerfile).contains("Verify the exact JDK, CRIU, kernel and CPU combination");
        assertThat(dockerfile).contains("docker run --rm -p 127.0.0.1:8080:8080");
        assertThat(dockerfile).contains("before lifecycle start");
        assertThat(dockerfile).contains("does not prove pool ownership");
        assertThat(dockerfile).contains("SPRING_DATASOURCE_HIKARI_ALLOWPOOLSUSPENSION=true");
        assertThat(dockerfile).contains("ENTRYPOINT [\"/app/checkpoint-and-run.sh\"]");
        assertThat(dockerfile).contains("generated by BootUI");
    }

    @Test
    void fallsBackToAppWhenArtifactIsMissing() {
        assertThat(generator.generateDockerfile(null)).contains("image of app.");
        assertThat(generator.generateDockerfile("  ")).contains("image of app.");
    }

    @Test
    void generatesPlainMavenVariant() {
        String dockerfile = generator.generateDockerfile("my-service", ProjectBuildSystem.MAVEN);

        assertThat(dockerfile).contains("mvn -DskipTests clean package");
        assertThat(dockerfile).doesNotContain("./mvnw");
        assertThat(dockerfile).contains("apache-maven");
        // The CRaC build image is Debian-based, so a missing build tool is installed with apt-get.
        assertThat(dockerfile).contains("apt-get install -y --no-install-recommends curl ca-certificates");
        assertThat(dockerfile).doesNotContain("microdnf");
        // The runnable jar lands in target for Maven.
        assertThat(dockerfile).contains("find target -maxdepth 1");
        assertThat(dockerfile).contains("ARG MAVEN_VERSION=3.9.16");
    }

    @Test
    void generatesGradleWrapperVariant() {
        String dockerfile = generator.generateDockerfile("my-service", ProjectBuildSystem.GRADLE_WRAPPER);

        assertThat(dockerfile).contains("chmod +x gradlew");
        assertThat(dockerfile).contains("./gradlew bootJar");
        assertThat(dockerfile).contains("find build/libs -maxdepth 1");
        assertThat(dockerfile).doesNotContain("./mvnw");
    }

    @Test
    void generatesPlainGradleVariant() {
        String dockerfile = generator.generateDockerfile("my-service", ProjectBuildSystem.GRADLE);

        assertThat(dockerfile).contains("gradle bootJar");
        assertThat(dockerfile).doesNotContain("./gradlew");
        assertThat(dockerfile).contains("services.gradle.org");
        assertThat(dockerfile).contains("curl ca-certificates unzip");
        assertThat(dockerfile).contains("find build/libs -maxdepth 1");
        assertThat(dockerfile).contains("ARG GRADLE_VERSION=9.5.1");
    }

    @Test
    void entrypointTakesAndRestoresACheckpoint() {
        String entrypoint = generator.generateEntrypoint();

        assertThat(entrypoint).startsWith("#!/bin/sh");
        assertThat(entrypoint).contains("spring.context.checkpoint=onRefresh");
        assertThat(entrypoint).contains("CRaCCheckpointTo");
        assertThat(entrypoint).contains("CRaCRestoreFrom");
        assertThat(entrypoint).contains("JVM flags are applied only while creating the checkpoint");
        assertThat(entrypoint).contains("java $JAVA_OPTS -XX:CRaCCheckpointTo");
        assertThat(entrypoint).contains("CHECKPOINT_RESTORE/SYS_PTRACE/SYS_ADMIN/NET_ADMIN capabilities");
        assertThat(entrypoint).contains("generated by BootUI");
    }

    @Test
    void sampleComposeRequiresExplicitRetryWithPreservedCheckpointVolume() throws Exception {
        String compose = Files.readString(repositoryFile("docker-compose-crac.yml"));

        assertThat(compose.lines().filter(line -> line.stripLeading().startsWith("restart:")))
                .containsExactly("    restart: \"no\"");
        assertThat(compose).contains("- crac-checkpoint:/opt/crac/checkpoint");
    }

    @Test
    void entrypointDetectsAnIncompleteCheckpointInsteadOfRestoringIt() {
        String entrypoint = generator.generateEntrypoint();

        // A marker permits only an attempted restore; it does not certify a complete image.
        assertThat(entrypoint).contains("[ -f \"$CRAC_CHECKPOINT_DIR/inventory.img\" ]");
        assertThat(entrypoint).contains("checkpoint_candidate_exists");
        assertThat(entrypoint).contains("if ! checkpoint_candidate_exists; then");
        assertThat(entrypoint).contains("not an integrity or compatibility");
        assertThat(entrypoint).doesNotContain("rm -", "checkpoint_is_complete", "discarding");
        // The CRIU log holds the actual reason the dump failed; the JVM only reports a
        // generic "Native checkpoint failed" on stdout.
        assertThat(entrypoint).contains("print_criu_dump_log");
        assertThat(entrypoint).contains("dump*.log");
        // A failed checkpoint must exit non-zero rather than fall through to a restore.
        assertThat(entrypoint).contains("checkpoint_status=1");
        assertThat(entrypoint).contains("exit \"$checkpoint_status\"");
    }

    @ParameterizedTest
    @CsvSource({"false, 0", "true, 0", "false, 37", "true, 37"})
    @EnabledOnOs({OS.LINUX, OS.MAC})
    void candidateRestorePreservesExitStatusWithoutCreatingAgain(boolean sample, int restoreStatus) throws Exception {
        ScriptFixture fixture = scriptFixture(sample);
        Files.createDirectory(fixture.checkpoint());
        Path marker = Files.writeString(fixture.checkpoint().resolve("inventory.img"), "not a certified image");
        Path userFile = Files.writeString(fixture.checkpoint().resolve(".user-file"), "keep me");

        ScriptResult result = runScript(fixture, fixture.checkpoint().toString(), 99, false, restoreStatus);

        assertThat(result.status()).isEqualTo(restoreStatus);
        assertThat(result.output()).contains("Attempting restore from checkpoint candidate");
        assertThat(result.javaArguments()).containsExactly("-XX:CRaCRestoreFrom=" + fixture.checkpoint());
        assertThat(Files.readString(marker)).isEqualTo("not a certified image");
        assertThat(Files.readString(userFile)).isEqualTo("keep me");
    }

    @ParameterizedTest
    @CsvSource({"false, 0, 0", "true, 0, 0", "false, 137, 0", "true, 137, 0", "false, 137, 43", "true, 137, 43"})
    @EnabledOnOs({OS.LINUX, OS.MAC})
    void emptyDirectoryCreatesCandidateThenAttemptsRestore(boolean sample, int createStatus, int restoreStatus)
            throws Exception {
        ScriptFixture fixture = scriptFixture(sample);
        // CRIU can terminate the original JVM even when it has written a usable image.
        ScriptResult result = runScript(fixture, fixture.checkpoint().toString(), createStatus, true, restoreStatus);

        assertThat(result.status()).isEqualTo(restoreStatus);
        assertThat(result.output()).contains("creation exit code " + createStatus, "attempting restore");
        assertThat(result.javaArguments())
                .containsExactly(
                        "-Xmx64m",
                        "-Dfixture=true",
                        "-XX:CRaCCheckpointTo=" + fixture.checkpoint(),
                        "-Dspring.context.checkpoint=onRefresh",
                        "-jar",
                        fixture.root().resolve("app with spaces.jar").toString(),
                        "-XX:CRaCRestoreFrom=" + fixture.checkpoint());
        assertThat(Files.readString(fixture.checkpoint().resolve("inventory.img")))
                .isEqualTo("candidate");
    }

    @ParameterizedTest
    @CsvSource({"false, 0, 1", "true, 0, 1", "false, 23, 23", "true, 23, 23"})
    @EnabledOnOs({OS.LINUX, OS.MAC})
    void failedCreationPreservesFilesAndRefusesRetry(boolean sample, int createStatus, int expectedStatus)
            throws Exception {
        ScriptFixture fixture = scriptFixture(sample);
        Files.createDirectory(fixture.checkpoint());

        ScriptResult result = runScript(fixture, fixture.checkpoint().toString(), createStatus, false, 0);

        assertThat(result.status()).isEqualTo(expectedStatus);
        assertThat(result.output())
                .contains("Checkpoint creation failed", "fake dump diagnostic", "preserving all files");
        assertThat(result.javaArguments())
                .contains("-XX:CRaCCheckpointTo=" + fixture.checkpoint())
                .noneMatch(argument -> argument.startsWith("-XX:CRaCRestoreFrom="));
        assertThat(Files.readString(fixture.checkpoint().resolve(".partial"))).isEqualTo("partial image");
        assertThat(Files.readString(fixture.checkpoint().resolve("dump.log"))).isEqualTo("fake dump diagnostic");

        ScriptResult retry = runScript(fixture, fixture.checkpoint().toString(), 0, true, 0);

        assertThat(retry.status()).isNotZero();
        assertThat(retry.output()).contains("Incomplete checkpoint directory", "leaving all contents unchanged");
        assertThat(retry.javaArguments()).isEqualTo(result.javaArguments());
        assertThat(Files.readString(fixture.checkpoint().resolve(".partial"))).isEqualTo("partial image");
        assertThat(Files.readString(fixture.checkpoint().resolve("dump.log"))).isEqualTo("fake dump diagnostic");
    }

    @ParameterizedTest
    @ValueSource(booleans = {false, true})
    @EnabledOnOs({OS.LINUX, OS.MAC})
    void incompleteDirectoryPreservesHiddenAndUserFilesWithoutCallingJava(boolean sample) throws Exception {
        ScriptFixture fixture = scriptFixture(sample);
        Files.createDirectory(fixture.checkpoint());
        for (String name : List.of(".hidden", "..hidden", "user-file", "pages-1.img", "dump.log")) {
            Files.writeString(fixture.checkpoint().resolve(name), name);
        }
        Path nested = Files.createDirectory(fixture.checkpoint().resolve("user-directory"));
        Files.writeString(nested.resolve("keep"), "nested user data");

        ScriptResult result = runScript(fixture, fixture.checkpoint().toString(), 0, true, 0);

        assertThat(result.status()).isNotZero();
        assertThat(result.output()).contains("Incomplete checkpoint directory", "select a new empty directory");
        assertThat(result.javaArguments()).isEmpty();
        for (String name : List.of(".hidden", "..hidden", "user-file", "pages-1.img", "dump.log")) {
            assertThat(Files.readString(fixture.checkpoint().resolve(name))).isEqualTo(name);
        }
        assertThat(Files.readString(nested.resolve("keep"))).isEqualTo("nested user data");
    }

    @ParameterizedTest
    @ValueSource(booleans = {false, true})
    @EnabledOnOs({OS.LINUX, OS.MAC})
    void hiddenFileOrDanglingLinkAloneMakesDirectoryIncomplete(boolean sample) throws Exception {
        ScriptFixture fixture = scriptFixture(sample);
        Files.createDirectory(fixture.checkpoint());
        Path hidden = Files.writeString(fixture.checkpoint().resolve(".hidden"), "keep");

        assertThat(runScript(fixture, fixture.checkpoint().toString(), 0, true, 0)
                        .status())
                .isNotZero();
        assertThat(Files.readString(hidden)).isEqualTo("keep");
        Files.delete(hidden);
        Path link = Files.createSymbolicLink(fixture.checkpoint().resolve("dangling"), Path.of("missing"));

        ScriptResult result = runScript(fixture, fixture.checkpoint().toString(), 0, true, 0);

        assertThat(result.status()).isNotZero();
        assertThat(result.javaArguments()).isEmpty();
        assertThat(Files.readSymbolicLink(link)).isEqualTo(Path.of("missing"));
    }

    @ParameterizedTest
    @ValueSource(booleans = {false, true})
    @EnabledOnOs({OS.LINUX, OS.MAC})
    void unsafePathsFailBeforeCreatingDirectoriesOrCallingJava(boolean sample) throws Exception {
        ScriptFixture fixture = scriptFixture(sample);
        String missing = fixture.root().resolve("must-not-be-created").toString();
        for (String path : List.of(
                "",
                "/",
                ".",
                "..",
                "...",
                "relative/checkpoint",
                "//",
                "/./",
                "/../",
                missing + "/.",
                missing + "/..",
                missing + "/...",
                missing + "/./child",
                missing + "/../child",
                missing + "//child",
                missing + "/",
                missing + "/with space",
                missing + "/\t",
                missing + "/\n",
                missing + "/*")) {
            ScriptResult result = runScript(fixture, path, 0, true, 0);

            assertThat(result.status()).as("path <%s>", path).isNotZero();
            assertThat(result.output()).contains("Invalid CRAC_CHECKPOINT_DIR");
            assertThat(result.javaArguments()).isEmpty();
            assertThat(Path.of(missing)).doesNotExist();
        }
    }

    @ParameterizedTest
    @ValueSource(booleans = {false, true})
    @EnabledOnOs({OS.LINUX, OS.MAC})
    void symlinkPathsAreRejectedAndNonDirectoryIsNotOverwritten(boolean sample) throws Exception {
        ScriptFixture fixture = scriptFixture(sample);
        Path realDirectory = Files.createDirectory(fixture.root().resolve("real"));
        Files.writeString(realDirectory.resolve("inventory.img"), "candidate");
        Path link = Files.createSymbolicLink(fixture.root().resolve("alias"), realDirectory);
        for (String path : List.of(link.toString(), link + "/child")) {
            ScriptResult result = runScript(fixture, path, 0, true, 0);
            assertThat(result.status()).isNotZero();
            assertThat(result.output()).contains("Invalid CRAC_CHECKPOINT_DIR");
            assertThat(result.javaArguments()).isEmpty();
        }
        assertThat(realDirectory.resolve("child")).doesNotExist();
        assertThat(Files.readString(realDirectory.resolve("inventory.img"))).isEqualTo("candidate");

        Path file = Files.writeString(fixture.checkpoint(), "user data");
        ScriptResult result = runScript(fixture, file.toString(), 0, true, 0);
        assertThat(result.status()).isNotZero();
        assertThat(result.javaArguments()).isEmpty();
        assertThat(Files.readString(file)).isEqualTo("user data");
    }

    private ScriptFixture scriptFixture(boolean sample) throws Exception {
        // Resolve macOS's /var alias: the scripts deliberately refuse symlink path components.
        Path root = temporaryDirectory.toRealPath();
        Path script = root.resolve("checkpoint-and-run.sh");
        Files.writeString(script, sample ? Files.readString(sampleEntrypoint()) : generator.generateEntrypoint());
        Path bin = Files.createDirectory(root.resolve("bin"));
        Path java = Files.writeString(bin.resolve("java"), """
                #!/bin/sh
                set -eu
                printf '%s\\n' "$@" >> "$FAKE_JAVA_LOG"
                for argument do
                  case "$argument" in
                    -XX:CRaCRestoreFrom=*) exit "$FAKE_RESTORE_STATUS" ;;
                    -XX:CRaCCheckpointTo=*) create=true ;;
                  esac
                done
                [ "${create:-false}" = true ] || exit 98
                printf 'fake dump diagnostic' > "$CRAC_CHECKPOINT_DIR/dump.log"
                printf 'partial image' > "$CRAC_CHECKPOINT_DIR/.partial"
                if [ "$FAKE_WRITE_MARKER" = true ]; then
                  printf 'candidate' > "$CRAC_CHECKPOINT_DIR/inventory.img"
                fi
                exit "$FAKE_CREATE_STATUS"
                """);
        assertThat(java.toFile().setExecutable(true)).isTrue();
        // PATH contains only this fake Java and the two utilities the entrypoints require.
        // Never fall back to a real Java executable, even if the fixture is broken.
        Files.createSymbolicLink(bin.resolve("mkdir"), Path.of("/bin/mkdir"));
        Files.createSymbolicLink(bin.resolve("tail"), Path.of("/usr/bin/tail"));
        return new ScriptFixture(root, script, root.resolve("checkpoint"), root.resolve("java-arguments"));
    }

    private static Path sampleEntrypoint() {
        return repositoryFile("bootui-spring-sample-app/src/main/script/checkpoint-and-run.sh");
    }

    private static Path repositoryFile(String relativePath) {
        // Support both reactor-root and module-local Surefire working directories.
        for (Path root = Path.of("").toAbsolutePath(); root != null; root = root.getParent()) {
            Path file = root.resolve(relativePath);
            if (Files.isRegularFile(file)) {
                return file;
            }
        }
        throw new IllegalStateException("Cannot locate repository file: " + relativePath);
    }

    private static ScriptResult runScript(
            ScriptFixture fixture, String checkpointPath, int createStatus, boolean writeMarker, int restoreStatus)
            throws Exception {
        Path output = fixture.root().resolve("output");
        ProcessBuilder builder = new ProcessBuilder("/bin/sh", fixture.script().toString())
                .directory(fixture.root().toFile())
                .redirectErrorStream(true)
                .redirectOutput(output.toFile());
        var environment = builder.environment();
        environment.clear();
        environment.put("PATH", fixture.root().resolve("bin").toString());
        environment.put("LC_ALL", "C");
        environment.put("CRAC_CHECKPOINT_DIR", checkpointPath);
        environment.put("APP_JAR", fixture.root().resolve("app with spaces.jar").toString());
        environment.put("JAVA_OPTS", "-Xmx64m -Dfixture=true");
        environment.put("FAKE_JAVA_LOG", fixture.javaArguments().toString());
        environment.put("FAKE_CREATE_STATUS", Integer.toString(createStatus));
        environment.put("FAKE_WRITE_MARKER", Boolean.toString(writeMarker));
        environment.put("FAKE_RESTORE_STATUS", Integer.toString(restoreStatus));
        Process process = builder.start();
        try {
            assertThat(process.waitFor(10, TimeUnit.SECONDS))
                    .as("entrypoint must finish using only the fake Java executable")
                    .isTrue();
            return new ScriptResult(
                    process.exitValue(),
                    Files.readString(output),
                    Files.exists(fixture.javaArguments()) ? Files.readAllLines(fixture.javaArguments()) : List.of());
        } finally {
            process.destroyForcibly();
        }
    }

    private record ScriptFixture(Path root, Path script, Path checkpoint, Path javaArguments) {}

    private record ScriptResult(int status, String output, List<String> javaArguments) {}
}
