import {flushPromises, mount} from '@vue/test-utils'
import {afterEach, describe, expect, it, vi} from 'vitest'

import Crac from './Crac.vue'

function runtime(overrides = {}) {
  return {
    summary: 'The org.crac API is not on the classpath.',
    jvmName: 'OpenJDK 64-Bit Server VM',
    cracApiPresent: false,
    cracCapableJvm: false,
    checkpointOnRefresh: false,
    checkpointTo: null,
    restoreFrom: null,
    cracJvmArgs: [],
    ...overrides
  }
}

function generatedFiles({installable = true} = {}) {
  const unavailable = 'The application is not running from an exploded build (for example a packaged jar).'
  return [
    {
      name: 'Dockerfile-crac',
      content:
        '# This scaffold was generated by BootUI for demo\nFROM eclipse-temurin:21-jdk-noble AS build\nFROM bellsoft/liberica-runtime-container:jdk-21-crac-slim-glibc\n',
      installable,
      installPath: installable ? 'Dockerfile-crac' : unavailable
    },
    {
      name: 'checkpoint-and-run.sh',
      content: '#!/bin/sh\n# generated by BootUI\njava -XX:CRaCCheckpointTo="$CRAC_CHECKPOINT_DIR"\n',
      installable,
      installPath: installable ? 'checkpoint-and-run.sh' : unavailable
    }
  ]
}

function cracReport({installable = true, status = 'NOT_SCANNED', files} = {}) {
  return {
    localOnly: true,
    disclaimer: 'CRaC disclaimer.',
    runtime: runtime(),
    basePackages: ['com.example'],
    classesAnalyzed: 0,
    checksRun: 0,
    findingsFound: 0,
    severityCounts: [
      {severity: 'HIGH', count: 0},
      {severity: 'MEDIUM', count: 0},
      {severity: 'LOW', count: 0},
      {severity: 'INFO', count: 0}
    ],
    scan: {
      analyzer: 'BootUI CRaC readiness',
      status,
      message: 'Not scanned yet.',
      scannedAt: null,
      checksRun: 0,
      classesAnalyzed: 0,
      findingsFound: 0
    },
    findings: [],
    warnings: [],
    generatedFiles: files ?? generatedFiles({installable})
  }
}

async function mountWithReport(report) {
  vi.stubGlobal(
    'fetch',
    vi.fn(() => Promise.resolve(new Response(JSON.stringify(report), {status: 200})))
  )

  const wrapper = mount(Crac)
  await flushPromises()
  return wrapper
}

function cardByTitle(wrapper, title) {
  return wrapper.findAll('.accordion-item').find((item) => {
    const header = item.find('.accordion-button .fw-semibold')
    return header.exists() && header.text() === title
  })
}

describe('Crac', () => {
  afterEach(() => {
    vi.unstubAllGlobals()
  })

  it('renders the container assets accordion with download links and a Dockerfile preview', async () => {
    const wrapper = await mountWithReport(cracReport())

    expect(wrapper.text()).toContain('Container assets')
    const dockerDownload = wrapper.find('a[href="api/crac/dockerfile"]')
    expect(dockerDownload.exists()).toBe(true)
    expect(dockerDownload.attributes('download')).toBe('Dockerfile-crac')
    const entrypointDownload = wrapper.find('a[href="api/crac/entrypoint"]')
    expect(entrypointDownload.exists()).toBe(true)
    expect(entrypointDownload.attributes('download')).toBe('checkpoint-and-run.sh')
    expect(wrapper.text()).toContain('bellsoft/liberica-runtime-container')
  })

  it('writes both files into the project and reports the per-file outcome', async () => {
    const report = cracReport()
    const fetchMock = vi.fn((url) => {
      if (String(url).includes('api/crac/install/all')) {
        return Promise.resolve(
          new Response(
            JSON.stringify({
              installed: true,
              status: 'WRITTEN',
              message: 'Wrote Dockerfile-crac and checkpoint-and-run.sh into the project directory.',
              dockerfile: {
                installed: true,
                status: 'WRITTEN',
                message: 'Wrote the CRaC Dockerfile',
                path: 'Dockerfile-crac'
              },
              entrypoint: {
                installed: true,
                status: 'WRITTEN',
                message: 'Wrote the CRaC entrypoint',
                path: 'checkpoint-and-run.sh'
              }
            }),
            {status: 200}
          )
        )
      }
      return Promise.resolve(new Response(JSON.stringify(report), {status: 200}))
    })
    vi.stubGlobal('fetch', fetchMock)

    const wrapper = mount(Crac)
    await flushPromises()

    const allCard = cardByTitle(wrapper, 'All files')
    const writeButton = allCard.findAll('button').find((button) => button.text().includes('Write into project'))
    expect(writeButton).toBeDefined()
    await writeButton.trigger('click')
    await flushPromises()

    expect(fetchMock).toHaveBeenCalledWith('api/crac/install/all', {method: 'POST'})
    expect(wrapper.text()).toContain('Wrote Dockerfile-crac and checkpoint-and-run.sh into the project directory.')
    expect(wrapper.text()).toContain('Wrote the CRaC Dockerfile')
    expect(wrapper.text()).toContain('Wrote the CRaC entrypoint')
  })

  it('hides the write buttons and explains when not running from source', async () => {
    const wrapper = await mountWithReport(cracReport({installable: false}))

    const dockerCard = cardByTitle(wrapper, 'Dockerfile-crac')
    const writeButton = dockerCard.findAll('button').find((button) => button.text().includes('Write into project'))
    expect(writeButton).toBeUndefined()
    expect(wrapper.text()).toContain('Direct write unavailable')
  })
})
