import {flushPromises, mount} from '@vue/test-utils'
import {afterEach, describe, expect, it, vi} from 'vitest'

import GraalVm from './GraalVm.vue'

vi.mock('../utils/useConfirm.js', () => ({
  useConfirm: () => ({confirm: () => Promise.resolve(true)})
}))

function finding(id, name, severity, occurrenceCount = 1, status = 'REVIEW', category = 'Reflection') {
  return {
    id,
    name,
    category,
    severity,
    description: `${name} description.`,
    status,
    occurrenceCount,
    sampleOccurrences: occurrenceCount > 0 ? [`${id} detail`] : [],
    recommendation: `${name} recommendation.`
  }
}

function graalvmReport(
  findings,
  {includeDependencies = true, dependencies = [], installable = true, metadataDirectory, dockerfile} = {}
) {
  return {
    localOnly: true,
    disclaimer: 'GraalVM disclaimer.',
    basePackages: ['com.example'],
    includeDependencies,
    classesAnalyzed: 12,
    checksRun: 5,
    findingsFound: findings.length,
    severityCounts: [
      {severity: 'HIGH', count: severityCount(findings, 'HIGH')},
      {severity: 'MEDIUM', count: severityCount(findings, 'MEDIUM')},
      {severity: 'LOW', count: severityCount(findings, 'LOW')},
      {severity: 'INFO', count: severityCount(findings, 'INFO')}
    ],
    scan: {
      analyzer: 'BootUI GraalVM readiness',
      status: 'SCANNED',
      message: 'Readiness checks completed.',
      scannedAt: 1_700_000_000_000,
      checksRun: 5,
      classesAnalyzed: 12,
      findingsFound: findings.length
    },
    findings,
    dependenciesAnalyzed: dependencies.length,
    dependenciesWithoutMetadata: dependencies.filter((dep) => !dep.shipsMetadata).length,
    dependencies,
    warnings: [],
    metadata: {reflectionEntries: 2, serializationEntries: 1, resourceEntries: 3},
    installable,
    installPath: installable
      ? 'src/main/resources/META-INF/native-image/com.example/demo/reachability-metadata.json'
      : 'The application is not running from an exploded build (for example a packaged jar).',
    metadataDirectory: metadataDirectory ?? 'src/main/resources/META-INF/native-image/com.example/demo/',
    dockerfile: dockerfile ?? {
      content:
        '# This scaffold was generated by BootUI for demo\nFROM ghcr.io/graalvm/graalvm-community:25 AS build\nENTRYPOINT ["./native-app"]\n',
      installable,
      installPath: installable
        ? 'Dockerfile-native'
        : 'The application is not running from an exploded build (for example a packaged jar).'
    }
  }
}

function severityCount(findings, severity) {
  return findings.filter((item) => item.severity === severity).length
}

async function mountWithReport(report) {
  vi.stubGlobal(
    'fetch',
    vi.fn(() => Promise.resolve(new Response(JSON.stringify(report), {status: 200})))
  )

  const wrapper = mount(GraalVm)
  await flushPromises()
  return wrapper
}

function cardByTitle(wrapper, title) {
  return wrapper.findAll('.accordion-item').find((item) => {
    const header = item.find('.accordion-button .fw-semibold')
    return header.exists() && header.text() === title
  })
}

describe('GraalVm', () => {
  afterEach(() => {
    vi.unstubAllGlobals()
  })

  it('shows readiness concerns sorted by severity with a metadata download link', async () => {
    const wrapper = await mountWithReport(
      graalvmReport([
        finding('GRAAL-REFLECT-001', 'Medium severity concern', 'MEDIUM', 3),
        finding('GRAAL-RES-001', 'Low severity concern', 'LOW', 1)
      ])
    )

    expect(wrapper.text()).toContain('Scan complete')
    expect(wrapper.text()).toContain('2 concerns, sorted by importance')
    expect(wrapper.text()).toContain('What happened:')
    expect(wrapper.text()).toContain('3 occurrences found for this check.')
    expect(wrapper.findAll('.list-group-item h3').map((title) => title.text())).toEqual([
      'Medium severity concern',
      'Low severity concern'
    ])
    const download = wrapper.find('a[href="api/graalvm/metadata"]')
    expect(download.exists()).toBe(true)
    expect(download.attributes('download')).toBe('reachability-metadata.json')
  })

  it('shows an empty state when no readiness concerns are found', async () => {
    const wrapper = await mountWithReport(graalvmReport([]))

    expect(wrapper.text()).toContain('No native-image readiness concerns found')
  })

  it('shows check evaluation errors instead of dropping them', async () => {
    const errorFinding = finding('GRAAL-ERROR-001', 'Broken readiness check', 'HIGH', 0, 'ERROR')
    errorFinding.sampleOccurrences = ['Check could not be evaluated: missing bytecode.']

    const wrapper = await mountWithReport(graalvmReport([errorFinding]))

    expect(wrapper.text()).toContain('Broken readiness check')
    expect(wrapper.text()).toContain('ERROR')
    expect(wrapper.text()).toContain('Check could not be evaluated: missing bytecode.')
  })

  it('lists surveyed dependencies and their metadata signal', async () => {
    const wrapper = await mountWithReport(
      graalvmReport([], {
        dependencies: [
          {name: 'org.example:with-metadata', shipsMetadata: true, note: ''},
          {
            name: 'org.example:no-metadata',
            shipsMetadata: false,
            note: 'No native-image metadata',
            repositoryMetadata: false,
            repositoryMetadataVersion: '0.9.0',
            repositoryTestedVersions: '0.9.0, 0.9.1',
            repositoryUrl:
              'https://github.com/oracle/graalvm-reachability-metadata/tree/master/metadata/org.example/no-metadata'
          }
        ]
      })
    )

    expect(wrapper.text()).toContain('1 of 2 dependencies ship bundled metadata')
    expect(wrapper.text()).toContain('org.example:with-metadata')
    expect(wrapper.text()).toContain('org.example:no-metadata')
    expect(wrapper.text()).toContain('Repository entry')
    expect(wrapper.text()).toContain('covered')
    expect(wrapper.text()).toContain('partial')
    expect(wrapper.text()).toContain('Repository metadata exists for a different version')
    expect(wrapper.text()).not.toContain('Metadata file')
  })

  it('hides the dependency section when dependencies were not surveyed', async () => {
    const wrapper = await mountWithReport(graalvmReport([], {includeDependencies: false}))

    expect(wrapper.text()).not.toContain('Dependency reachability metadata')
  })

  it('shows the resolved coordinates in the scaffold placement path', async () => {
    const wrapper = await mountWithReport(graalvmReport([], {installable: false}))

    expect(wrapper.text()).toContain('src/main/resources/META-INF/native-image/com.example/demo/')
  })

  it('keeps the groupId/artifactId placeholders when coordinates are unresolved', async () => {
    const wrapper = await mountWithReport(
      graalvmReport([], {metadataDirectory: 'src/main/resources/META-INF/native-image/<groupId>/<artifactId>/'})
    )

    expect(wrapper.text()).toContain('src/main/resources/META-INF/native-image/<groupId>/<artifactId>/')
  })

  it('shows scan warnings surfaced by the backend', async () => {
    const report = graalvmReport([])
    report.warnings = ['Dependency metadata survey could not be completed.']

    const wrapper = await mountWithReport(report)

    expect(wrapper.text()).toContain('Scan warnings.')
    expect(wrapper.text()).toContain('Dependency metadata survey could not be completed.')
  })

  it('installs the metadata into the source tree and reports the written path', async () => {
    const report = graalvmReport([finding('GRAAL-REFLECT-001', 'Concern', 'MEDIUM', 1)])
    const fetchMock = vi.fn((url) => {
      if (String(url).includes('api/graalvm/install')) {
        return Promise.resolve(
          new Response(
            JSON.stringify({
              installed: true,
              status: 'WRITTEN',
              message: 'Wrote the reachability metadata scaffold to src/main/resources/META-INF/...',
              path: 'src/main/resources/META-INF/...'
            }),
            {status: 200}
          )
        )
      }
      return Promise.resolve(new Response(JSON.stringify(report), {status: 200}))
    })
    vi.stubGlobal('fetch', fetchMock)

    const wrapper = mount(GraalVm)
    await flushPromises()

    const metadataCard = cardByTitle(wrapper, 'reachability-metadata.json')
    const installButton = metadataCard.findAll('button').find((button) => button.text().includes('Write into project'))
    expect(installButton).toBeDefined()
    await installButton.trigger('click')
    await flushPromises()

    expect(fetchMock).toHaveBeenCalledWith('api/graalvm/install', {method: 'POST'})
    expect(wrapper.text()).toContain('Wrote the reachability metadata scaffold')
  })

  it('hides the install button when the app is not running from source', async () => {
    const wrapper = await mountWithReport(
      graalvmReport([finding('GRAAL-REFLECT-001', 'Concern', 'MEDIUM', 1)], {installable: false})
    )

    const metadataCard = cardByTitle(wrapper, 'reachability-metadata.json')
    const installButton = metadataCard.findAll('button').find((button) => button.text().includes('Write into project'))
    expect(installButton).toBeUndefined()
    expect(wrapper.text()).toContain('Direct install unavailable')
  })

  it('renders the Dockerfile-native card with a download link and preview', async () => {
    const wrapper = await mountWithReport(graalvmReport([finding('GRAAL-REFLECT-001', 'Concern', 'MEDIUM', 1)]))

    expect(wrapper.text()).toContain('Dockerfile-native')
    const download = wrapper.find('a[href="api/graalvm/dockerfile"]')
    expect(download.exists()).toBe(true)
    expect(download.attributes('download')).toBe('Dockerfile-native')
    expect(wrapper.text()).toContain('FROM ghcr.io/graalvm/graalvm-community')
  })

  it('writes the Dockerfile to the project root and reports the result', async () => {
    const report = graalvmReport([finding('GRAAL-REFLECT-001', 'Concern', 'MEDIUM', 1)])
    const fetchMock = vi.fn((url) => {
      if (String(url).includes('api/graalvm/dockerfile/install')) {
        return Promise.resolve(
          new Response(
            JSON.stringify({
              installed: true,
              status: 'WRITTEN',
              message: 'Wrote Dockerfile-native to the project root.',
              path: 'Dockerfile-native'
            }),
            {status: 200}
          )
        )
      }
      return Promise.resolve(new Response(JSON.stringify(report), {status: 200}))
    })
    vi.stubGlobal('fetch', fetchMock)

    const wrapper = mount(GraalVm)
    await flushPromises()

    const dockerCard = cardByTitle(wrapper, 'Dockerfile-native')
    const writeButton = dockerCard.findAll('button').find((button) => button.text().includes('Write into project'))
    expect(writeButton).toBeDefined()
    await writeButton.trigger('click')
    await flushPromises()

    expect(fetchMock).toHaveBeenCalledWith('api/graalvm/dockerfile/install', {method: 'POST'})
    expect(wrapper.text()).toContain('Wrote Dockerfile-native to the project root.')
  })

  it('hides the Dockerfile write button when the app is not running from source', async () => {
    const wrapper = await mountWithReport(
      graalvmReport([finding('GRAAL-REFLECT-001', 'Concern', 'MEDIUM', 1)], {installable: false})
    )

    const dockerCard = cardByTitle(wrapper, 'Dockerfile-native')
    const writeButton = dockerCard.findAll('button').find((button) => button.text().includes('Write into project'))
    expect(writeButton).toBeUndefined()
    expect(wrapper.text()).toContain('Direct write unavailable')
  })

  it('opens the combined drawer by default and summarises the one-step write', async () => {
    const wrapper = await mountWithReport(graalvmReport([finding('GRAAL-REFLECT-001', 'Concern', 'MEDIUM', 1)]))

    const bothCard = cardByTitle(wrapper, 'All files')
    expect(bothCard).toBeDefined()
    expect(bothCard.find('.accordion-collapse').classes()).toContain('show')
    expect(wrapper.text()).toContain("writes both directly into the project's source tree")
    const writeButton = bothCard.findAll('button').find((button) => button.text().includes('Write into project'))
    expect(writeButton).toBeDefined()
  })

  it('writes both files into the project source tree in a single action', async () => {
    const report = graalvmReport([finding('GRAAL-REFLECT-001', 'Concern', 'MEDIUM', 1)])
    const fetchMock = vi.fn((url) => {
      if (String(url).includes('api/graalvm/install/all')) {
        return Promise.resolve(
          new Response(
            JSON.stringify({
              installed: true,
              status: 'WRITTEN',
              message: 'Wrote reachability-metadata.json and Dockerfile-native into the project source tree.',
              metadata: {installed: true, status: 'WRITTEN', message: 'Wrote the metadata scaffold.', path: 'a'},
              dockerfile: {installed: true, status: 'WRITTEN', message: 'Wrote the Dockerfile.', path: 'b'}
            }),
            {status: 200}
          )
        )
      }
      return Promise.resolve(new Response(JSON.stringify(report), {status: 200}))
    })
    vi.stubGlobal('fetch', fetchMock)

    const wrapper = mount(GraalVm)
    await flushPromises()

    const bothCard = cardByTitle(wrapper, 'All files')
    const writeButton = bothCard.findAll('button').find((button) => button.text().includes('Write into project'))
    expect(writeButton).toBeDefined()
    await writeButton.trigger('click')
    await flushPromises()

    expect(fetchMock).toHaveBeenCalledWith('api/graalvm/install/all', {method: 'POST'})
    expect(wrapper.text()).toContain('Wrote reachability-metadata.json and Dockerfile-native')
    expect(wrapper.text()).toContain('Wrote the metadata scaffold.')
    expect(wrapper.text()).toContain('Wrote the Dockerfile.')
  })

  it('hides the combined write button when the app is not running from source', async () => {
    const wrapper = await mountWithReport(
      graalvmReport([finding('GRAAL-REFLECT-001', 'Concern', 'MEDIUM', 1)], {installable: false})
    )

    const bothCard = cardByTitle(wrapper, 'All files')
    const writeButton = bothCard.findAll('button').find((button) => button.text().includes('Write into project'))
    expect(writeButton).toBeUndefined()
    expect(bothCard.text()).toContain('Direct write unavailable')
  })

  function concernTitles(wrapper) {
    return wrapper.findAll('.list-group-item h3').map((title) => title.text())
  }

  function severityFilterButton(wrapper, severity) {
    return wrapper
      .findAll('[aria-label="Filter concerns by severity"] button')
      .find((button) => button.text().startsWith(severity))
  }

  describe('concern filtering', () => {
    it('does not render the filter bar until a scan finds concerns', async () => {
      const wrapper = await mountWithReport(graalvmReport([]))

      expect(wrapper.find('input[aria-label="Search concerns"]').exists()).toBe(false)
      expect(wrapper.find('select[aria-label="Filter by category"]').exists()).toBe(false)
    })

    it('filters concerns by severity and reflects the visible count', async () => {
      const wrapper = await mountWithReport(
        graalvmReport([
          finding('GRAAL-HIGH-001', 'High concern', 'HIGH'),
          finding('GRAAL-MED-001', 'Medium concern', 'MEDIUM'),
          finding('GRAAL-LOW-001', 'Low concern', 'LOW')
        ])
      )

      const highButton = severityFilterButton(wrapper, 'HIGH')
      expect(highButton).toBeDefined()
      await highButton.trigger('click')

      expect(concernTitles(wrapper)).toEqual(['High concern'])
      expect(wrapper.text()).toContain('Showing 1 of 3 concerns')
    })

    it('filters concerns by category', async () => {
      const wrapper = await mountWithReport(
        graalvmReport([
          finding('GRAAL-REFLECT-001', 'Reflection concern', 'HIGH', 1, 'REVIEW', 'Reflection'),
          finding('GRAAL-RES-001', 'Resource concern', 'LOW', 1, 'REVIEW', 'Resources')
        ])
      )

      await wrapper.find('select[aria-label="Filter by category"]').setValue('Resources')

      expect(concernTitles(wrapper)).toEqual(['Resource concern'])
    })

    it('filters concerns by free-text search and clears back to all concerns', async () => {
      const wrapper = await mountWithReport(
        graalvmReport([
          finding('GRAAL-HIGH-001', 'Dynamic proxy concern', 'HIGH'),
          finding('GRAAL-LOW-001', 'Resource bundle concern', 'LOW')
        ])
      )

      await wrapper.find('input[aria-label="Search concerns"]').setValue('proxy')
      expect(concernTitles(wrapper)).toEqual(['Dynamic proxy concern'])

      const clear = wrapper.findAll('button').find((button) => button.text() === 'Clear filters')
      await clear.trigger('click')
      expect(concernTitles(wrapper)).toEqual(['Dynamic proxy concern', 'Resource bundle concern'])
    })

    it('shows a no-match empty state when filters exclude every concern', async () => {
      const wrapper = await mountWithReport(graalvmReport([finding('GRAAL-MED-001', 'Medium concern', 'MEDIUM')]))

      await wrapper.find('input[aria-label="Search concerns"]').setValue('no-such-concern')

      expect(wrapper.text()).toContain('No concerns match the active filters')
    })
  })
})
