package io.github.jdubois.bootui.autoconfigure.graalvm;

import java.io.IOException;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import java.util.Optional;
import java.util.function.Supplier;

/**
 * Resolves whether the generated {@code reachability-metadata.json} scaffold can be written directly
 * into the host application's source tree, and performs that write.
 *
 * <p>Installing in place is only offered when the application is detectably running from an exploded
 * build (e.g. {@code target/classes} via {@code mvn spring-boot:run} or an IDE), <em>not</em> from a
 * packaged fat jar. The target is the GraalVM-recommended location
 * {@code src/main/resources/META-INF/native-image/<groupId>/<artifactId>/reachability-metadata.json}
 * (falling back to a {@code bootui-generated} namespace when Maven coordinates cannot be resolved).
 *
 * <p>The write is fail-closed: it is confined under {@code src/main/resources} and never clobbers a
 * file that was not previously generated by BootUI.
 */
final class GraalVmSourceLayout {

    static final String METADATA_FILE = "reachability-metadata.json";
    /** Substring of the generated file's comment block, used to detect a previously generated file. */
    static final String GENERATED_MARKER = "generated by BootUI";

    private static final String FALLBACK_NAMESPACE = "bootui-generated";
    private static final Path RESOURCES_RELATIVE = Path.of("src", "main", "resources");

    private final Supplier<Path> projectRootSupplier;
    private final Supplier<Optional<URL>> codeSourceSupplier;
    private final Supplier<Optional<Coordinates>> coordinatesSupplier;

    GraalVmSourceLayout(
            Supplier<Path> projectRootSupplier,
            Supplier<Optional<URL>> codeSourceSupplier,
            Supplier<Optional<Coordinates>> coordinatesSupplier) {
        this.projectRootSupplier = projectRootSupplier;
        this.codeSourceSupplier = codeSourceSupplier;
        this.coordinatesSupplier = coordinatesSupplier;
    }

    /** Resolves where (and whether) the metadata scaffold can be installed. */
    Resolution resolve() {
        Path projectRoot;
        Optional<URL> codeSource;
        Optional<Coordinates> coordinates;
        try {
            projectRoot = projectRootSupplier.get();
            codeSource = codeSourceSupplier.get();
            coordinates = coordinatesSupplier.get();
        } catch (RuntimeException ex) {
            return Resolution.unavailable("The application source layout could not be determined.");
        }
        Optional<Coordinates> safeCoordinates = coordinates == null ? Optional.empty() : coordinates;
        return resolve(projectRoot, codeSource.orElse(null), safeCoordinates);
    }

    /**
     * Generates the install target. Package-private and static so it can be unit tested with explicit
     * inputs against temporary directories.
     */
    static Resolution resolve(Path projectRoot, URL codeSourceLocation, Optional<Coordinates> coordinates) {
        if (projectRoot == null) {
            return Resolution.unavailable("The application working directory could not be determined.");
        }
        if (!isExplodedClasses(codeSourceLocation)) {
            return Resolution.unavailable(
                    "The application is not running from an exploded build (for example a packaged jar), "
                            + "so there is no source tree to install into.");
        }
        Path root = projectRoot.toAbsolutePath().normalize();
        Path resources = root.resolve(RESOURCES_RELATIVE).normalize();
        if (!Files.isDirectory(resources)) {
            return Resolution.unavailable("No src/main/resources directory was found under " + root + ".");
        }
        if (!Files.isWritable(resources)) {
            return Resolution.unavailable("The src/main/resources directory is not writable.");
        }
        Path target = resources.resolve("META-INF").resolve("native-image");
        Coordinates resolved = coordinates.filter(Coordinates::isValid).orElse(null);
        if (resolved != null) {
            target = target.resolve(sanitize(resolved.groupId())).resolve(sanitize(resolved.artifactId()));
        } else {
            target = target.resolve(FALLBACK_NAMESPACE);
        }
        Path targetFile = target.resolve(METADATA_FILE).normalize();
        if (!targetFile.startsWith(resources)) {
            return Resolution.unavailable("The resolved metadata path escapes src/main/resources.");
        }
        return Resolution.installable(targetFile, root.relativize(targetFile).toString());
    }

    /** Resolves the target and writes the supplied JSON, refusing to overwrite a non-generated file. */
    InstallOutcome install(String json) {
        Resolution resolution = resolve();
        if (!resolution.installable()) {
            return new InstallOutcome("UNAVAILABLE", resolution.reason(), null);
        }
        Path targetFile = resolution.targetFile();
        String displayPath = resolution.displayPath();
        try {
            if (Files.exists(targetFile)) {
                String existing = Files.readString(targetFile, StandardCharsets.UTF_8);
                if (!existing.contains(GENERATED_MARKER)) {
                    return new InstallOutcome(
                            "EXISTS",
                            "A reachability-metadata.json already exists at " + displayPath
                                    + " and was not generated by BootUI, so it was left untouched. "
                                    + "Download the scaffold and merge it by hand instead.",
                            displayPath);
                }
            }
            Files.createDirectories(targetFile.getParent());
            Files.writeString(targetFile, json, StandardCharsets.UTF_8);
            return new InstallOutcome(
                    "WRITTEN",
                    "Wrote the reachability metadata scaffold to " + displayPath
                            + ". Review and complete it with the GraalVM tracing agent before relying on it.",
                    displayPath);
        } catch (IOException ex) {
            return new InstallOutcome(
                    "ERROR", "Failed to write the reachability metadata: " + safeMessage(ex), displayPath);
        }
    }

    /**
     * Returns {@code true} when the supplied code-source location is an exploded classes directory
     * (for example {@code target/classes}) rather than a packaged jar.
     */
    static boolean isExplodedClasses(URL location) {
        if (location == null || !"file".equalsIgnoreCase(location.getProtocol())) {
            return false;
        }
        String path = location.getPath();
        if (path == null || path.isBlank()) {
            return false;
        }
        if (path.toLowerCase(Locale.ROOT).endsWith(".jar")) {
            return false;
        }
        try {
            return Files.isDirectory(Path.of(location.toURI()));
        } catch (RuntimeException | java.net.URISyntaxException ex) {
            // Fall back to the trailing-slash convention that exploded class directories use.
            return path.endsWith("/");
        }
    }

    private static String sanitize(String segment) {
        String trimmed = segment.trim();
        StringBuilder sb = new StringBuilder(trimmed.length());
        for (int i = 0; i < trimmed.length(); i++) {
            char c = trimmed.charAt(i);
            if (Character.isLetterOrDigit(c) || c == '.' || c == '-' || c == '_') {
                sb.append(c);
            }
        }
        return sb.toString();
    }

    /**
     * Best-effort resolution of Maven coordinates from the project root {@code pom.xml}, falling back
     * to the {@code <parent>} groupId when the module does not declare its own. Returns empty when no
     * usable coordinates can be parsed.
     */
    static Optional<Coordinates> coordinatesFromPom(Path projectRoot) {
        if (projectRoot == null) {
            return Optional.empty();
        }
        Path pom = projectRoot.resolve("pom.xml");
        if (!Files.isRegularFile(pom)) {
            return Optional.empty();
        }
        String xml;
        try {
            xml = Files.readString(pom, StandardCharsets.UTF_8);
        } catch (IOException ex) {
            return Optional.empty();
        }
        String beforeDependencies = xml;
        int dependencies = xml.indexOf("<dependencies>");
        if (dependencies > 0) {
            beforeDependencies = xml.substring(0, dependencies);
        }
        String parentBlock = firstElement(beforeDependencies, "parent");
        String artifactId = topLevelValue(beforeDependencies, parentBlock, "artifactId");
        String groupId = topLevelValue(beforeDependencies, parentBlock, "groupId");
        if (groupId == null && parentBlock != null) {
            groupId = elementValue(parentBlock, "groupId");
        }
        if (groupId == null || artifactId == null) {
            return Optional.empty();
        }
        Coordinates coordinates = new Coordinates(groupId, artifactId);
        return coordinates.isValid() ? Optional.of(coordinates) : Optional.empty();
    }

    /** Reads a top-level element value, ignoring any occurrence nested inside the {@code <parent>} block. */
    private static String topLevelValue(String pom, String parentBlock, String element) {
        String withoutParent = parentBlock == null ? pom : pom.replace(parentBlock, "");
        return elementValue(withoutParent, element);
    }

    private static String firstElement(String xml, String element) {
        int open = xml.indexOf("<" + element + ">");
        int close = xml.indexOf("</" + element + ">");
        if (open < 0 || close < 0 || close < open) {
            return null;
        }
        return xml.substring(open, close + element.length() + 3);
    }

    private static String elementValue(String xml, String element) {
        if (xml == null) {
            return null;
        }
        String value = textBetween(firstElement(xml, element), element);
        return value == null || value.isBlank() ? null : value.trim();
    }

    private static String textBetween(String elementXml, String element) {
        if (elementXml == null) {
            return null;
        }
        String open = "<" + element + ">";
        int start = elementXml.indexOf(open);
        int end = elementXml.indexOf("</" + element + ">");
        if (start < 0 || end < 0) {
            return null;
        }
        return elementXml.substring(start + open.length(), end);
    }

    private static String safeMessage(Throwable ex) {
        String message = ex.getMessage();
        return message == null || message.isBlank() ? ex.getClass().getSimpleName() : message;
    }

    /** Maven coordinates used to namespace the metadata directory. */
    record Coordinates(String groupId, String artifactId) {

        boolean isValid() {
            return groupId != null && !groupId.isBlank() && artifactId != null && !artifactId.isBlank();
        }
    }

    /** Outcome of resolving the install target. */
    record Resolution(boolean installable, Path targetFile, String displayPath, String reason) {

        static Resolution unavailable(String reason) {
            return new Resolution(false, null, reason, reason);
        }

        static Resolution installable(Path targetFile, String displayPath) {
            return new Resolution(true, targetFile, displayPath, null);
        }
    }

    /** Outcome of an install attempt. */
    record InstallOutcome(String status, String message, String path) {}
}
