package io.github.jdubois.bootui.autoconfigure.graalvm;

/**
 * Generates a multi-stage {@code Dockerfile-native} that builds a GraalVM native image of the host
 * application the BootUI starter is installed in.
 *
 * <p>Unlike the multi-module {@code Dockerfile-native} at the root of the BootUI project (which builds
 * the sample app together with its reactor modules), this scaffold targets a single-module Spring Boot
 * application: it builds with {@code ./mvnw -Pnative -DskipTests clean package} and copies the native
 * executable that the {@code native-maven-plugin} names after the module {@code artifactId}.</p>
 *
 * <p>The generated content carries a {@code generated by BootUI} marker so the source-tree writer can
 * tell a previously generated file apart from a hand-written one and refuse to clobber the latter.</p>
 */
final class GraalVmDockerfileGenerator {

    private static final String DEFAULT_ARTIFACT = "app";

    String generate(String artifactName) {
        String artifact = artifactName == null || artifactName.isBlank() ? DEFAULT_ARTIFACT : artifactName.trim();
        return """
                # Multi-stage Dockerfile for a GraalVM native image of %1$s.
                #
                # This scaffold was generated by BootUI for the application the starter is installed in.
                # It assumes a single-module Maven project built with the Maven Wrapper and the `native`
                # profile that spring-boot-starter-parent provides.
                #
                # Requires GraalVM 25+ for Spring Boot 4 (GraalVM 25 = JDK 25).

                # Build stage with GraalVM 25 (includes the native-image toolchain, JDK 25)
                FROM ghcr.io/graalvm/graalvm-community:25 AS build

                WORKDIR /app

                # Copy the project (see .dockerignore for exclusions).
                COPY . .
                RUN chmod +x mvnw

                # Build the native executable. The `native` profile runs Spring Boot's process-aot goal,
                # downloads GraalVM reachability metadata and then compiles the native image during the
                # `package` phase.
                RUN ./mvnw -Pnative -DskipTests clean package

                # Move the native executable to a known path (the native-maven-plugin names it after the
                # module artifactId, i.e. %1$s).
                RUN if [ -f target/%1$s ]; then \\
                      cp target/%1$s native-app; \\
                    else \\
                      native_exe=$(find target -maxdepth 1 -type f -executable ! -name '*.jar' ! -name '*.jar.original' | head -1) && \\
                      if [ -n "$native_exe" ]; then cp "$native_exe" native-app; \\
                      else echo "ERROR: Native executable not found"; ls -laR target | head -40; exit 1; fi; \\
                    fi

                # Runtime stage with Debian slim (includes glibc + zlib needed by the binary)
                FROM debian:12-slim

                # Install curl for healthchecks
                RUN apt-get update && \\
                    apt-get install -y --no-install-recommends curl && \\
                    rm -rf /var/lib/apt/lists/*

                # Create a non-root user
                RUN useradd -m -u 1001 springboot

                WORKDIR /app

                # Copy the native executable from the build stage
                COPY --from=build --chown=springboot:springboot /app/native-app native-app

                USER springboot

                EXPOSE 8080

                # Health check using Spring Boot Actuator
                HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \\
                    CMD curl -f http://localhost:${SERVER_PORT:-8080}/actuator/health || exit 1

                # Run the native application
                ENTRYPOINT ["./native-app"]
                """.formatted(artifact);
    }
}
