package io.github.jdubois.bootui.autoconfigure.graalvm;

import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates a multi-stage {@code Dockerfile-native} that builds a GraalVM native image of the host
 * application the BootUI starter is installed in.
 *
 * <p>Unlike the multi-module {@code Dockerfile-native} at the root of the BootUI project (which builds
 * the sample app together with its reactor modules), this scaffold targets a single-module Spring Boot
 * application. It detects the project's build system from the files in the project root — Maven or
 * Gradle, with or without the wrapper — and emits the matching native build command
 * ({@code ./mvnw}/{@code mvn -Pnative -DskipTests clean native:compile} or
 * {@code ./gradlew}/{@code gradle nativeCompile}), copying the resulting executable from the build
 * tool's conventional output directory ({@code target} for Maven, {@code build/native/nativeCompile}
 * for Gradle).</p>
 *
 * <p>The Maven variants invoke the {@code native:compile} goal rather than {@code package}: the goal
 * forks a {@code package}-phase build (running Spring Boot's AOT processing and producing the jar)
 * and then compiles the native image. This works for an ordinary single-module Spring Boot app that
 * only inherits {@code spring-boot-starter-parent}'s {@code native} profile, which on its own does
 * <em>not</em> bind the native-image compilation to {@code package} (that binding requires the
 * {@code native-maven-plugin} to be declared with {@code <extensions>true</extensions>} or an explicit
 * {@code compile-no-fork} execution). A bare {@code clean package} would therefore finish without ever
 * producing the executable.</p>
 *
 * <p>The generated content carries a {@code generated by BootUI} marker so the source-tree writer can
 * tell a previously generated file apart from a hand-written one and refuse to clobber the latter.</p>
 */
final class GraalVmDockerfileGenerator {

    private static final String DEFAULT_ARTIFACT = "app";

    /** Maven release installed in the build stage when the project carries no Maven Wrapper. */
    private static final String MAVEN_VERSION = "3.9.16";

    /** Gradle release installed in the build stage when the project carries no Gradle Wrapper. */
    private static final String GRADLE_VERSION = "9.5.1";

    /**
     * The build system the generated Dockerfile drives. Each variant carries the human-readable
     * description used in the file header, the in-image setup step (make the wrapper executable, or
     * install the build tool when the project has none), the native build command, and the directory
     * the native executable lands in.
     */
    enum BuildTool {
        MAVEN_WRAPPER(
                "the Maven Wrapper and the `native` profile that spring-boot-starter-parent provides",
                """
                # Make the Maven Wrapper executable.
                RUN chmod +x mvnw""",
                "./mvnw -Pnative -DskipTests clean native:compile",
                "target"),
        MAVEN(
                "Maven and the `native` profile that spring-boot-starter-parent provides",
                """
                # Maven is not bundled in the GraalVM image and the project has no Maven Wrapper, so
                # install a known Maven release. It builds with the image's GraalVM JDK via JAVA_HOME.
                ARG MAVEN_VERSION=%s
                RUN microdnf install -y curl tar gzip && microdnf clean all && \\
                    curl -fsSL "https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz" -o /tmp/maven.tar.gz && \\
                    tar -xzf /tmp/maven.tar.gz -C /opt && rm /tmp/maven.tar.gz && \\
                    ln -s "/opt/apache-maven-${MAVEN_VERSION}/bin/mvn" /usr/local/bin/mvn""".formatted(MAVEN_VERSION),
                "mvn -Pnative -DskipTests clean native:compile",
                "target"),
        GRADLE_WRAPPER(
                "the Gradle Wrapper and the GraalVM `org.graalvm.buildtools.native` plugin",
                """
                # Make the Gradle Wrapper executable.
                RUN chmod +x gradlew""",
                "./gradlew nativeCompile",
                "build/native/nativeCompile"),
        GRADLE(
                "Gradle and the GraalVM `org.graalvm.buildtools.native` plugin",
                """
                # Gradle is not bundled in the GraalVM image and the project has no Gradle Wrapper, so
                # install a known Gradle release. It builds with the image's GraalVM JDK via JAVA_HOME.
                ARG GRADLE_VERSION=%s
                RUN microdnf install -y curl unzip && microdnf clean all && \\
                    curl -fsSL "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip" -o /tmp/gradle.zip && \\
                    unzip -q /tmp/gradle.zip -d /opt && rm /tmp/gradle.zip && \\
                    ln -s "/opt/gradle-${GRADLE_VERSION}/bin/gradle" /usr/local/bin/gradle""".formatted(GRADLE_VERSION),
                "gradle nativeCompile",
                "build/native/nativeCompile");

        private final String description;
        private final String setup;
        private final String command;
        private final String outputDir;

        BuildTool(String description, String setup, String command, String outputDir) {
            this.description = description;
            this.setup = setup;
            this.command = command;
            this.outputDir = outputDir;
        }
    }

    /**
     * Detects the build system from the files in the project root. Prefers the wrapper when its script
     * is present; falls back to the Maven Wrapper layout when nothing is recognised (preserving the
     * historical default) and prefers Maven on the rare projects that carry both build systems.
     */
    static BuildTool detect(Path projectRoot) {
        if (projectRoot == null) {
            return BuildTool.MAVEN_WRAPPER;
        }
        boolean mavenWrapper = isRegularFile(projectRoot, "mvnw");
        boolean maven = mavenWrapper || isRegularFile(projectRoot, "pom.xml");
        boolean gradleWrapper = isRegularFile(projectRoot, "gradlew");
        boolean gradle = gradleWrapper
                || isRegularFile(projectRoot, "build.gradle")
                || isRegularFile(projectRoot, "build.gradle.kts")
                || isRegularFile(projectRoot, "settings.gradle")
                || isRegularFile(projectRoot, "settings.gradle.kts");
        if (gradle && !maven) {
            return gradleWrapper ? BuildTool.GRADLE_WRAPPER : BuildTool.GRADLE;
        }
        if (maven) {
            return mavenWrapper ? BuildTool.MAVEN_WRAPPER : BuildTool.MAVEN;
        }
        return BuildTool.MAVEN_WRAPPER;
    }

    private static boolean isRegularFile(Path projectRoot, String name) {
        try {
            return Files.isRegularFile(projectRoot.resolve(name));
        } catch (RuntimeException ex) {
            return false;
        }
    }

    String generate(String artifactName) {
        return generate(artifactName, BuildTool.MAVEN_WRAPPER);
    }

    String generate(String artifactName, BuildTool buildTool) {
        String artifact = artifactName == null || artifactName.isBlank() ? DEFAULT_ARTIFACT : artifactName.trim();
        BuildTool tool = buildTool == null ? BuildTool.MAVEN_WRAPPER : buildTool;
        return """
                # Multi-stage Dockerfile for a GraalVM native image of %1$s.
                #
                # This scaffold was generated by BootUI for the application the starter is installed in.
                # It assumes a single-module Spring Boot application built with %2$s.
                #
                # Requires GraalVM 25+ for Spring Boot 4 (GraalVM 25 = JDK 25).
                #
                # Build and run (publish the port with -p so the app is reachable from the host;
                # EXPOSE alone does not publish it):
                #   docker build -f Dockerfile-native -t %1$s .
                #   docker run --rm -p 8080:8080 %1$s

                # Build stage with GraalVM 25 (includes the native-image toolchain, JDK 25)
                FROM ghcr.io/graalvm/graalvm-community:25 AS build

                WORKDIR /app

                # Copy the project (see .dockerignore for exclusions).
                COPY . .

                %3$s

                # Build the native executable. This runs Spring Boot's AOT processing, downloads the
                # GraalVM reachability metadata and then compiles the native image.
                RUN %4$s

                # Move the native executable to a known path (named after the module/project, i.e. %1$s).
                RUN if [ -f %5$s/%1$s ]; then \\
                      cp %5$s/%1$s native-app; \\
                    else \\
                      native_exe=$(find %5$s -maxdepth 1 -type f -executable ! -name '*.jar' ! -name '*.jar.original' | head -1) && \\
                      if [ -n "$native_exe" ]; then cp "$native_exe" native-app; \\
                      else echo "ERROR: Native executable not found"; ls -laR %5$s | head -40; exit 1; fi; \\
                    fi

                # Runtime stage with Debian slim (includes glibc + zlib needed by the binary)
                FROM debian:12-slim

                # Install curl for healthchecks
                RUN apt-get update && \\
                    apt-get install -y --no-install-recommends curl && \\
                    rm -rf /var/lib/apt/lists/*

                # Create a non-root user
                RUN useradd -m -u 1001 springboot

                WORKDIR /app

                # Copy the native executable from the build stage
                COPY --from=build --chown=springboot:springboot /app/native-app native-app

                USER springboot

                EXPOSE 8080

                # Liveness check: succeeds once the embedded web server accepts connections and returns
                # any HTTP response. It does not require Spring Boot Actuator to be on the classpath, so it
                # stays green even when the management endpoints are not web-exposed.
                HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \\
                    CMD curl -s -o /dev/null http://localhost:${SERVER_PORT:-8080}/ || exit 1

                # Run the native application
                ENTRYPOINT ["./native-app"]
                """.formatted(artifact, tool.description, tool.setup, tool.command, tool.outputDir);
    }
}
