package io.github.jdubois.bootui.autoconfigure.graalvm;

import java.util.List;

/**
 * Serializes {@link GraalVmMetadata} into the modern unified GraalVM
 * {@code reachability-metadata.json} format. Each reflection and serialization entry carries a
 * {@code condition.typeReached} guard so the registration only activates when the type is actually
 * reachable, as recommended by GraalVM.
 *
 * <p>The output is a heuristic scaffold derived from static analysis: it seeds the file that belongs
 * under {@code src/main/resources/META-INF/native-image/<groupId>/<artifactId>/} and is meant to be
 * reviewed and completed with the tracing agent.</p>
 *
 * <p>JSON is written by hand (with strict escaping) to avoid adding a JSON library dependency to the
 * auto-configuration module.</p>
 */
final class GraalVmMetadataGenerator {

    private static final String INDENT = "  ";
    private static final List<String> COMMENT = List.of(
            "Heuristic reachability-metadata.json scaffold generated by BootUI.",
            "Review and complete it with the GraalVM tracing agent before relying on it.",
            "Place it under src/main/resources/META-INF/native-image/<groupId>/<artifactId>/.");

    String generate(GraalVmMetadata metadata) {
        StringBuilder json = new StringBuilder();
        json.append("{").append('\n');
        appendComment(json);
        json.append(",").append('\n');
        appendReflection(json, metadata.reflectionTypes());
        json.append(",").append('\n');
        appendSerialization(json, metadata.serializationTypes());
        json.append(",").append('\n');
        appendResources(json, metadata.resourceGlobs());
        json.append('\n').append("}").append('\n');
        return json.toString();
    }

    private void appendComment(StringBuilder json) {
        json.append(INDENT).append("\"comment\": [").append('\n');
        for (int i = 0; i < COMMENT.size(); i++) {
            json.append(INDENT).append(INDENT).append(quote(COMMENT.get(i)));
            json.append(i < COMMENT.size() - 1 ? "," : "").append('\n');
        }
        json.append(INDENT).append("]");
    }

    private void appendReflection(StringBuilder json, List<String> types) {
        json.append(INDENT).append("\"reflection\": [");
        if (types.isEmpty()) {
            json.append("]");
            return;
        }
        json.append('\n');
        for (int i = 0; i < types.size(); i++) {
            String type = types.get(i);
            json.append(INDENT).append(INDENT).append("{").append('\n');
            json.append(INDENT)
                    .append(INDENT)
                    .append(INDENT)
                    .append("\"condition\": {\"typeReached\": ")
                    .append(quote(type))
                    .append("},")
                    .append('\n');
            json.append(INDENT)
                    .append(INDENT)
                    .append(INDENT)
                    .append("\"type\": ")
                    .append(quote(type))
                    .append(",")
                    .append('\n');
            json.append(INDENT)
                    .append(INDENT)
                    .append(INDENT)
                    .append("\"allDeclaredConstructors\": true,")
                    .append('\n');
            json.append(INDENT)
                    .append(INDENT)
                    .append(INDENT)
                    .append("\"allDeclaredMethods\": true,")
                    .append('\n');
            json.append(INDENT)
                    .append(INDENT)
                    .append(INDENT)
                    .append("\"allDeclaredFields\": true")
                    .append('\n');
            json.append(INDENT)
                    .append(INDENT)
                    .append("}")
                    .append(i < types.size() - 1 ? "," : "")
                    .append('\n');
        }
        json.append(INDENT).append("]");
    }

    private void appendSerialization(StringBuilder json, List<String> types) {
        json.append(INDENT).append("\"serialization\": [");
        if (types.isEmpty()) {
            json.append("]");
            return;
        }
        json.append('\n');
        for (int i = 0; i < types.size(); i++) {
            String type = types.get(i);
            json.append(INDENT)
                    .append(INDENT)
                    .append("{\"condition\": {\"typeReached\": ")
                    .append(quote(type))
                    .append("}, \"type\": ")
                    .append(quote(type))
                    .append("}");
            json.append(i < types.size() - 1 ? "," : "").append('\n');
        }
        json.append(INDENT).append("]");
    }

    private void appendResources(StringBuilder json, List<String> globs) {
        json.append(INDENT).append("\"resources\": [");
        if (globs.isEmpty()) {
            json.append("]");
            return;
        }
        json.append('\n');
        for (int i = 0; i < globs.size(); i++) {
            json.append(INDENT)
                    .append(INDENT)
                    .append("{\"glob\": ")
                    .append(quote(globs.get(i)))
                    .append("}");
            json.append(i < globs.size() - 1 ? "," : "").append('\n');
        }
        json.append(INDENT).append("]");
    }

    private static String quote(String value) {
        StringBuilder sb = new StringBuilder(value.length() + 2);
        sb.append('"');
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            switch (c) {
                case '"' -> sb.append("\\\"");
                case '\\' -> sb.append("\\\\");
                case '\b' -> sb.append("\\b");
                case '\f' -> sb.append("\\f");
                case '\n' -> sb.append("\\n");
                case '\r' -> sb.append("\\r");
                case '\t' -> sb.append("\\t");
                default -> {
                    if (c < 0x20) {
                        sb.append(String.format("\\u%04x", (int) c));
                    } else {
                        sb.append(c);
                    }
                }
            }
        }
        sb.append('"');
        return sb.toString();
    }
}
