package io.github.jdubois.bootui.autoconfigure.graalvm;

import io.github.jdubois.bootui.autoconfigure.sourcetree.DockerPackageManager;
import io.github.jdubois.bootui.autoconfigure.sourcetree.ProjectBuildSystem;

/**
 * Generates a multi-stage {@code Dockerfile-native} that builds a GraalVM native image of the host
 * application the BootUI starter is installed in.
 *
 * <p>Unlike the multi-module {@code Dockerfile-native} at the root of the BootUI project (which builds
 * the sample app together with its reactor modules), this scaffold targets a single-module Spring Boot
 * application. It detects the project's build system from the files in the project root — Maven or
 * Gradle, with or without the wrapper, via the shared {@link ProjectBuildSystem} — and emits the
 * matching native build command
 * ({@code ./mvnw}/{@code mvn -Pnative -DskipTests clean native:compile} or
 * {@code ./gradlew}/{@code gradle nativeCompile}), copying the resulting executable from the build
 * tool's conventional output directory ({@code target} for Maven, {@code build/native/nativeCompile}
 * for Gradle).</p>
 *
 * <p>The Maven variants invoke the {@code native:compile} goal rather than {@code package}: the goal
 * forks a {@code package}-phase build (running Spring Boot's AOT processing and producing the jar)
 * and then compiles the native image. This works for an ordinary single-module Spring Boot app that
 * only inherits {@code spring-boot-starter-parent}'s {@code native} profile, which on its own does
 * <em>not</em> bind the native-image compilation to {@code package} (that binding requires the
 * {@code native-maven-plugin} to be declared with {@code <extensions>true</extensions>} or an explicit
 * {@code compile-no-fork} execution). A bare {@code clean package} would therefore finish without ever
 * producing the executable.</p>
 *
 * <p>The build stage runs on a UBI-based GraalVM image, so a missing build tool is installed with
 * {@code microdnf} ({@link DockerPackageManager#MICRODNF}).</p>
 *
 * <p>The generated content carries a {@code generated by BootUI} marker so the source-tree writer can
 * tell a previously generated file apart from a hand-written one and refuse to clobber the latter.</p>
 */
final class GraalVmDockerfileGenerator {

    private static final String DEFAULT_ARTIFACT = "app";

    /** The GraalVM-specific Dockerfile pieces that depend on the detected build system. */
    private record Variant(String description, String command, String outputDir) {}

    private static Variant variant(ProjectBuildSystem buildSystem) {
        return switch (buildSystem) {
            case MAVEN_WRAPPER ->
                new Variant(
                        "the Maven Wrapper and the `native` profile that spring-boot-starter-parent provides",
                        "./mvnw -Pnative -DskipTests clean native:compile",
                        "target");
            case MAVEN ->
                new Variant(
                        "Maven and the `native` profile that spring-boot-starter-parent provides",
                        "mvn -Pnative -DskipTests clean native:compile",
                        "target");
            case GRADLE_WRAPPER ->
                new Variant(
                        "the Gradle Wrapper and the GraalVM `org.graalvm.buildtools.native` plugin",
                        "./gradlew nativeCompile",
                        "build/native/nativeCompile");
            case GRADLE ->
                new Variant(
                        "Gradle and the GraalVM `org.graalvm.buildtools.native` plugin",
                        "gradle nativeCompile",
                        "build/native/nativeCompile");
        };
    }

    String generate(String artifactName) {
        return generate(artifactName, ProjectBuildSystem.MAVEN_WRAPPER);
    }

    String generate(String artifactName, ProjectBuildSystem buildSystem) {
        String artifact = artifactName == null || artifactName.isBlank() ? DEFAULT_ARTIFACT : artifactName.trim();
        ProjectBuildSystem tool = buildSystem == null ? ProjectBuildSystem.MAVEN_WRAPPER : buildSystem;
        Variant variant = variant(tool);
        String setup = tool.dockerSetup(DockerPackageManager.MICRODNF);
        return """
                # Multi-stage Dockerfile for a GraalVM native image of %1$s.
                #
                # This scaffold was generated by BootUI for the application the starter is installed in.
                # It assumes a single-module Spring Boot application built with %2$s.
                #
                # Requires GraalVM 25+ for Spring Boot 4 (GraalVM 25 = JDK 25).
                #
                # Build and run (publish the port with -p so the app is reachable from the host;
                # EXPOSE alone does not publish it):
                #   docker build -f Dockerfile-native -t %1$s .
                #   docker run --rm -p 8080:8080 %1$s

                # Build stage with GraalVM 25 (includes the native-image toolchain, JDK 25)
                FROM ghcr.io/graalvm/graalvm-community:25 AS build

                WORKDIR /app

                # Copy the project (see .dockerignore for exclusions).
                COPY . .

                %3$s

                # Build the native executable. This runs Spring Boot's AOT processing, downloads the
                # GraalVM reachability metadata and then compiles the native image.
                RUN %4$s

                # Move the native executable to a known path (named after the module/project, i.e. %1$s).
                RUN if [ -f %5$s/%1$s ]; then \\
                      cp %5$s/%1$s native-app; \\
                    else \\
                      native_exe=$(find %5$s -maxdepth 1 -type f -executable ! -name '*.jar' ! -name '*.jar.original' | head -1) && \\
                      if [ -n "$native_exe" ]; then cp "$native_exe" native-app; \\
                      else echo "ERROR: Native executable not found"; ls -laR %5$s | head -40; exit 1; fi; \\
                    fi

                # Runtime stage with Debian slim (includes glibc + zlib needed by the binary)
                FROM debian:12-slim

                # Install curl for healthchecks
                RUN apt-get update && \\
                    apt-get install -y --no-install-recommends curl && \\
                    rm -rf /var/lib/apt/lists/*

                # Create a non-root user
                RUN useradd -m -u 1001 springboot

                WORKDIR /app

                # Copy the native executable from the build stage
                COPY --from=build --chown=springboot:springboot /app/native-app native-app

                USER springboot

                EXPOSE 8080

                # Liveness check: succeeds once the embedded web server accepts connections and returns
                # any HTTP response. It does not require Spring Boot Actuator to be on the classpath, so it
                # stays green even when the management endpoints are not web-exposed.
                HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \\
                    CMD curl -s -o /dev/null http://localhost:${SERVER_PORT:-8080}/ || exit 1

                # Run the native application
                ENTRYPOINT ["./native-app"]
                """.formatted(artifact, variant.description(), setup, variant.command(), variant.outputDir());
    }
}
