// @ts-check
import {expect, test} from './fixtures.js'

test.describe('SQL Trace view', () => {
  test('records SQL executions generated by the sample app', async ({openView, page}) => {
    page.on('dialog', (dialog) => dialog.accept())

    await openView('sql-trace', 'SQL Trace')

    // Start from an empty buffer so the assertions below are deterministic.
    const clearButton = page.getByRole('button', {name: 'Clear'})
    if (await clearButton.isEnabled()) {
      await clearButton.click()
      await expect(page.locator('.alert-success')).toBeVisible()
    }

    // Trigger a real, uncached SELECT against sample_products via the sample app's product search.
    const response = await page.request.get('/api/sample/product-search?term=console')
    expect(response.status()).toBe(200)

    await page.getByTitle('Refresh', {exact: true}).click()

    const executions = page.locator('section').filter({hasText: 'Recent executions'})
    await expect(executions.locator('.badge', {hasText: 'SELECT'}).first()).toBeVisible()
    await expect(executions).toContainText('sample_products')

    // Expanding a row reveals the full statement and connection metadata.
    const selectRow = executions.locator('tbody tr.sql-row', {hasText: 'sample_products'}).first()
    await selectRow.click()
    await expect(executions).toContainText('Connection')
    await expect(executions).toContainText('Thread')
  })

  test('can pause and resume recording', async ({openView, page}) => {
    await openView('sql-trace', 'SQL Trace')

    await page.getByRole('button', {name: 'Pause'}).click()
    await expect(page.locator('.alert-success')).toContainText(/paused/i)
    await expect(page.getByRole('button', {name: 'Resume'})).toBeVisible()

    // Restore recording so the rest of the suite keeps capturing queries.
    await page.getByRole('button', {name: 'Resume'}).click()
    await expect(page.getByRole('button', {name: 'Pause'})).toBeVisible()
  })
})
